(** This GCode was generated by ReplicatorG 0040 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2013/05/24 14:06:21 (-0700) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
M109 S110 T0 (set HBP temperature)
M104 S220 T0 (set extruder temperature) (temp updated by printOMatic)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.6      (Position Height)
M108 R5.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P2000     (Create Anchor)
(**** end of start.gcode ****)
M73 P1 (display progress)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
(<created> 13.05.24|14:6 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.1 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.1 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
(<operatingFeedRatePerSecond> 40.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 40.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 55.0 </travelFeedRatePerSecond>)
(<edgeWidth> 0.4 </edgeWidth>)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
M73 P2 (display progress)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning False </setting>)
(<setting> cool Turn_Fan_Off_at_Ending False </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.82 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
M73 P3 (display progress)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 0 </setting>)
M73 P4 (display progress)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 0 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular True </setting>)
(<setting> fill Line False </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 1.0 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
M73 P5 (display progress)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: True </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 1 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 2 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
M73 P6 (display progress)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None False </setting>)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere True </setting>)
(<setting> raft Exterior_Only False </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 40.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 40.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 55.0 </setting>)
(</settings>)
(<timeStampPreface> 20130524_140619 </timeStampPreface>)
M73 P7 (display progress)
(<procedureName> carve </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
(<crafting>)
;M113 S1.0
;M108 R24.0
(<raftPerimeter>)
(<raftPoint> X14.76 Y5.94 </raftPoint>)
(<raftPoint> X-3.907 Y5.94 </raftPoint>)
(<raftPoint> X-4.542 Y1.964 </raftPoint>)
(<raftPoint> X-9.36 Y-3.28 </raftPoint>)
(<raftPoint> X-9.36 Y-5.94 </raftPoint>)
(<raftPoint> X14.76 Y-5.94 </raftPoint>)
(</raftPerimeter>)
(<raftPerimeter>)
(<raftPoint> X14.76 Y0.556 </raftPoint>)
M73 P8 (display progress)
(<raftPoint> X10.148 Y0.353 </raftPoint>)
(<raftPoint> X6.978 Y-3.129 </raftPoint>)
(<raftPoint> X3.702 Y-4.786 </raftPoint>)
(<raftPoint> X2.859 Y-5.389 </raftPoint>)
(<raftPoint> X3.504 Y-5.94 </raftPoint>)
(<raftPoint> X14.76 Y-5.94 </raftPoint>)
(</raftPerimeter>)
(<raftPerimeter>)
(<raftPoint> X15.267 Y5.717 </raftPoint>)
(<raftPoint> X14.532 Y6.108 </raftPoint>)
(<raftPoint> X3.725 Y6.108 </raftPoint>)
(<raftPoint> X0.125 Y7.908 </raftPoint>)
(<raftPoint> X-12.807 Y7.908 </raftPoint>)
(<raftPoint> X-15.267 Y5.631 </raftPoint>)
(<raftPoint> X-15.267 Y-5.717 </raftPoint>)
(<raftPoint> X-14.532 Y-6.108 </raftPoint>)
(<raftPoint> X14.532 Y-6.108 </raftPoint>)
(<raftPoint> X15.267 Y-5.717 </raftPoint>)
(</raftPerimeter>)
(<layer> 0.176 )
G1 X-14.67 Y-5.49 Z0.18 F3300.0
G1 F1200.0
G1 E1.0
G1 F3300.0
M101
G1 X-14.67 Y5.49 Z0.18 F371.901 E1.769
M73 P9 (display progress)
G1 X-11.73 Y7.29 Z0.18 F371.901 E2.01
G1 X-11.73 Y-5.49 Z0.18 F371.901 E2.905
G1 X-8.8 Y-5.49 Z0.18 F371.901 E3.11
G1 X-8.8 Y7.29 Z0.18 F371.901 E4.005
G1 X-5.87 Y7.29 Z0.18 F371.901 E4.21
G1 X-5.87 Y-5.49 Z0.18 F371.901 E5.105
G1 X-2.93 Y-5.49 Z0.18 F371.901 E5.311
G1 X-2.93 Y7.29 Z0.18 F371.901 E6.205
G1 X0.0 Y7.29 Z0.18 F371.901 E6.411
G1 X0.0 Y-5.49 Z0.18 F371.901 E7.306
G1 X2.93 Y-5.49 Z0.18 F371.901 E7.511
G1 X2.93 Y5.49 Z0.18 F371.901 E8.28
G1 X5.87 Y5.49 Z0.18 F371.901 E8.485
G1 X5.87 Y-5.49 Z0.18 F371.901 E9.254
G1 X8.8 Y-5.49 Z0.18 F371.901 E9.46
G1 X8.8 Y5.49 Z0.18 F371.901 E10.228
G1 X11.73 Y5.49 Z0.18 F371.901 E10.434
G1 X11.73 Y-5.49 Z0.18 F371.901 E11.203
G1 X14.67 Y-5.49 Z0.18 F371.901 E11.408
G1 X14.67 Y5.49 Z0.18 F371.901 E12.177
G1 F1200.0
G1 E11.177
G1 F371.901
M103
;M108 R28.0
M73 P10 (display progress)
(</layer>)
(<layer> 0.364 )
G1 X-14.74 Y0.0 Z0.36 F3300.0
G1 F1200.0
G1 E12.177
G1 F3300.0
M101
G1 X14.74 Y0.0 Z0.36 F1111.111 E12.983
G1 X14.74 Y-1.8 Z0.36 F1111.111 E13.032
G1 X-14.74 Y-1.8 Z0.36 F1111.111 E13.838
G1 X-14.74 Y-3.6 Z0.36 F1111.111 E13.888
G1 X14.74 Y-3.6 Z0.36 F1111.111 E14.694
G1 X14.74 Y-5.4 Z0.36 F1111.111 E14.743
G1 X-14.74 Y-5.4 Z0.36 F1111.111 E15.549
G1 F1200.0
G1 E14.549
G1 F1111.111
M103
G1 X-14.74 Y1.8 Z0.36 F3300.0
G1 F1200.0
G1 E15.549
G1 F3300.0
M101
G1 X14.74 Y1.8 Z0.36 F1111.111 E16.356
G1 X14.74 Y3.6 Z0.36 F1111.111 E16.405
G1 X-14.74 Y3.6 Z0.36 F1111.111 E17.211
M73 P11 (display progress)
G1 X-14.74 Y5.4 Z0.36 F1111.111 E17.26
G1 X14.74 Y5.4 Z0.36 F1111.111 E18.067
G1 F1200.0
G1 E17.067
G1 F1111.111
M103
G1 X0.07 Y7.2 Z0.36 F3300.0
G1 F1200.0
G1 E18.067
G1 F3300.0
M101
G1 X-11.8 Y7.2 Z0.36 F1111.111 E18.391
G1 F1200.0
G1 E17.391
G1 F1111.111
M103
;M108 R28.0
(</layer>)
(<layer> 0.544 )
G1 X-14.74 Y0.0 Z0.54 F3300.0
G1 F1200.0
G1 E18.391
G1 F3300.0
M101
G1 X14.74 Y0.0 Z0.54 F1111.111 E19.198
G1 X14.74 Y-1.8 Z0.54 F1111.111 E19.247
M73 P12 (display progress)
G1 X-14.74 Y-1.8 Z0.54 F1111.111 E20.053
G1 X-14.74 Y-3.6 Z0.54 F1111.111 E20.102
G1 X14.74 Y-3.6 Z0.54 F1111.111 E20.909
G1 X14.74 Y-5.4 Z0.54 F1111.111 E20.958
G1 X-14.74 Y-5.4 Z0.54 F1111.111 E21.764
G1 F1200.0
G1 E20.764
G1 F1111.111
M103
G1 X-14.74 Y1.8 Z0.54 F3300.0
G1 F1200.0
G1 E21.764
G1 F3300.0
M101
G1 X14.74 Y1.8 Z0.54 F1111.111 E22.57
G1 X14.74 Y3.6 Z0.54 F1111.111 E22.619
G1 X-14.74 Y3.6 Z0.54 F1111.111 E23.426
G1 X-14.74 Y5.4 Z0.54 F1111.111 E23.475
G1 X14.74 Y5.4 Z0.54 F1111.111 E24.281
G1 F1200.0
G1 E23.281
G1 F1111.111
M103
G1 X0.07 Y7.2 Z0.54 F3300.0
G1 F1200.0
G1 E24.281
M73 P13 (display progress)
G1 F3300.0
M101
G1 X-11.8 Y7.2 Z0.54 F1111.111 E24.606
G1 F1200.0
G1 E23.606
G1 F1111.111
M103
;M108 R22.4
(</layer>)
(<raftLayerEnd> </raftLayerEnd>)
(<layer> 0.63 )
(<supportLayer>)
G1 X-8.97 Y-5.4 Z0.63 F3300.0
G1 F1200.0
G1 E24.606
G1 F3300.0
M101
G1 X14.3 Y-5.4 Z0.63 F2160.0 E24.868
G1 X14.46 Y-3.6 Z0.63 F2160.0 E24.888
G1 X-8.97 Y-3.6 Z0.63 F2160.0 E25.152
G1 F1200.0
G1 E24.152
G1 F2160.0
M103
G1 X-7.06 Y-1.8 Z0.63 F3300.0
G1 F1200.0
M73 P14 (display progress)
G1 E25.152
G1 F3300.0
M101
G1 X14.31 Y-1.8 Z0.63 F2160.0 E25.393
G1 X14.16 Y0.0 Z0.63 F2160.0 E25.413
G1 X-5.63 Y0.0 Z0.63 F2160.0 E25.636
G1 F1200.0
G1 E24.636
G1 F2160.0
M103
G1 X-4.2 Y1.8 Z0.63 F3300.0
G1 F1200.0
G1 E25.636
G1 F3300.0
M101
G1 X14.38 Y1.8 Z0.63 F2160.0 E25.845
G1 X14.3 Y3.6 Z0.63 F2160.0 E25.865
G1 X-2.78 Y3.6 Z0.63 F2160.0 E26.057
G1 F1200.0
G1 E25.196
G1 F2160.0
M103
G1 X-3.22 Y4.33 Z0.63 F3300.0
G1 X-3.07 Y4.31 Z0.63 F3300.0
G1 X-3.25 Y5.4 Z0.63 F3300.0
G1 F1200.0
M73 P15 (display progress)
G1 E26.057
G1 F3300.0
M101
G1 X13.95 Y5.4 Z0.63 F2160.0 E26.251
G1 F1200.0
G1 E25.251
G1 F2160.0
M103
;M108 R18.0
(</supportLayer>)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.377 Y2.233 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.377 Y3.911 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-10.832 Y3.888 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.171 Y3.714 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.441 Y3.201 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.461 Y-3.151 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.426 Y-3.347 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.362 Y-3.498 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.268 Y-3.635 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-11.133 Y-3.764 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-10.959 Y-3.862 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-10.802 Y-3.91 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.377 Y-3.926 Z0.63 </boundaryPoint>)
M73 P16 (display progress)
(<boundaryPoint> X-9.377 Y-2.248 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.926 Y-2.248 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-2.635 Y4.426 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-2.771 Y4.71 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-6.925 Y4.732 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.123 Y4.695 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.271 Y4.633 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.4 Y4.545 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.54 Y4.396 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.635 Y4.232 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.684 Y4.067 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-7.699 Y2.233 Z0.63 </boundaryPoint>)
(<edge> outer )
G1 X-11.18 Y-3.4 Z0.63 F3300.0
G1 F1200.0
G1 E26.251
G1 F3300.0
M101
G1 X-11.12 Y-3.5 Z0.63 F1080.0 E26.253
G1 X-11.01 Y-3.6 Z0.63 F1080.0 E26.256
G1 X-10.88 Y-3.68 Z0.63 F1080.0 E26.259
G1 X-10.77 Y-3.71 Z0.63 F1080.0 E26.261
G1 X-9.58 Y-3.72 Z0.63 F1080.0 E26.282
G1 X-9.58 Y-2.05 Z0.63 F1080.0 E26.313
G1 X-8.02 Y-2.05 Z0.63 F1080.0 E26.341
G1 X-2.87 Y4.45 Z0.63 F1080.0 E26.491
M73 P17 (display progress)
G1 X-2.9 Y4.51 Z0.63 F1080.0 E26.492
G1 X-6.91 Y4.53 Z0.63 F1080.0 E26.564
G1 X-7.07 Y4.5 Z0.63 F1080.0 E26.567
G1 X-7.17 Y4.46 Z0.63 F1080.0 E26.569
G1 X-7.27 Y4.39 Z0.63 F1080.0 E26.572
G1 X-7.38 Y4.28 Z0.63 F1080.0 E26.574
G1 X-7.45 Y4.15 Z0.63 F1080.0 E26.577
G1 X-7.48 Y4.04 Z0.63 F1080.0 E26.579
G1 X-7.5 Y2.03 Z0.63 F1080.0 E26.615
G1 X-9.58 Y2.03 Z0.63 F1080.0 E26.653
G1 X-9.58 Y3.71 Z0.63 F1080.0 E26.683
G1 X-10.78 Y3.69 Z0.63 F1080.0 E26.705
G1 X-11.02 Y3.56 Z0.63 F1080.0 E26.71
G1 X-11.24 Y3.15 Z0.63 F1080.0 E26.718
G1 X-11.26 Y-3.13 Z0.63 F1080.0 E26.832
G1 X-11.23 Y-3.29 Z0.63 F1080.0 E26.835
G1 X-11.19 Y-3.4 Z0.63 F1080.0 E26.837
G1 X-11.18 Y-3.4 Z0.63 F1080.0 E26.837
G1 F1200.0
G1 E26.652
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
M73 P18 (display progress)
(<infillPoint> X-9.577 Y2.033 Z0.05 </infillPoint>)
(<infillPoint> X-9.577 Y3.708 Z0.05 </infillPoint>)
(<infillPoint> X-10.782 Y3.689 Z0.05 </infillPoint>)
(<infillPoint> X-11.023 Y3.565 Z0.05 </infillPoint>)
(<infillPoint> X-11.241 Y3.151 Z0.05 </infillPoint>)
(<infillPoint> X-11.261 Y-3.134 Z0.05 </infillPoint>)
(<infillPoint> X-11.233 Y-3.29 Z0.05 </infillPoint>)
(<infillPoint> X-11.186 Y-3.401 Z0.05 </infillPoint>)
(<infillPoint> X-11.115 Y-3.505 Z0.05 </infillPoint>)
(<infillPoint> X-11.013 Y-3.602 Z0.05 </infillPoint>)
(<infillPoint> X-10.88 Y-3.677 Z0.05 </infillPoint>)
(<infillPoint> X-10.771 Y-3.71 Z0.05 </infillPoint>)
(<infillPoint> X-9.577 Y-3.724 Z0.05 </infillPoint>)
(<infillPoint> X-9.577 Y-2.048 Z0.05 </infillPoint>)
(<infillPoint> X-8.023 Y-2.048 Z0.05 </infillPoint>)
(<infillPoint> X-2.869 Y4.452 Z0.05 </infillPoint>)
(<infillPoint> X-2.897 Y4.511 Z0.05 </infillPoint>)
(<infillPoint> X-6.907 Y4.532 Z0.05 </infillPoint>)
(<infillPoint> X-7.065 Y4.502 Z0.05 </infillPoint>)
(<infillPoint> X-7.175 Y4.456 Z0.05 </infillPoint>)
(<infillPoint> X-7.269 Y4.392 Z0.05 </infillPoint>)
(<infillPoint> X-7.378 Y4.276 Z0.05 </infillPoint>)
(<infillPoint> X-7.45 Y4.152 Z0.05 </infillPoint>)
(<infillPoint> X-7.484 Y4.037 Z0.05 </infillPoint>)
(<infillPoint> X-7.501 Y2.033 Z0.05 </infillPoint>)
M73 P19 (display progress)
(</infillBoundary>)
;M108 R32.0
G1 X-10.0 Y-3.36 Z0.63 F3300.0
G1 F1200.0
G1 E26.837
G1 F3300.0
M101
G1 X-10.0 Y3.34 Z0.63 F2160.0 E26.945
G1 X-10.4 Y3.42 Z0.63 F2160.0 E26.951
G1 X-10.4 Y-3.43 Z0.63 F2160.0 E27.062
G1 X-10.8 Y-3.4 Z0.63 F2160.0 E27.068
G1 X-10.8 Y3.37 Z0.63 F2160.0 E27.177
G1 F1200.0
G1 E26.177
G1 F2160.0
M103
G1 X-9.58 Y2.03 Z0.63 F3300.0
G1 X-7.5 Y2.03 Z0.63 F3300.0
G1 X-7.2 Y3.4 Z0.63 F3300.0
G1 F1200.0
G1 E27.177
G1 F3300.0
M101
G1 X-7.2 Y-0.56 Z0.63 F2160.0 E27.24
G1 X-7.6 Y-1.06 Z0.63 F2160.0 E27.251
G1 X-7.6 Y1.75 Z0.63 F2160.0 E27.296
M73 P20 (display progress)
G1 X-8.0 Y1.75 Z0.63 F2160.0 E27.302
G1 X-8.0 Y-1.57 Z0.63 F2160.0 E27.356
G1 X-8.4 Y-1.77 Z0.63 F2160.0 E27.363
G1 X-8.4 Y1.75 Z0.63 F2160.0 E27.42
G1 X-8.8 Y1.75 Z0.63 F2160.0 E27.426
G1 X-8.8 Y-1.77 Z0.63 F2160.0 E27.483
G1 X-9.2 Y-1.77 Z0.63 F2160.0 E27.489
G1 X-9.2 Y1.75 Z0.63 F2160.0 E27.546
G1 X-9.6 Y1.75 Z0.63 F2160.0 E27.552
G1 X-9.6 Y-1.77 Z0.63 F2160.0 E27.609
G1 F1200.0
G1 E26.609
G1 F2160.0
M103
G1 X-3.6 Y3.98 Z0.63 F3300.0
G1 F1200.0
G1 E27.609
G1 F3300.0
M101
G1 X-3.6 Y4.23 Z0.63 F2160.0 E27.613
G1 X-4.0 Y4.23 Z0.63 F2160.0 E27.619
G1 X-4.0 Y3.48 Z0.63 F2160.0 E27.631
G1 X-4.4 Y2.97 Z0.63 F2160.0 E27.642
G1 X-4.4 Y4.23 Z0.63 F2160.0 E27.662
G1 X-4.8 Y4.23 Z0.63 F2160.0 E27.669
G1 X-4.8 Y2.47 Z0.63 F2160.0 E27.697
M73 P21 (display progress)
G1 X-5.2 Y1.96 Z0.63 F2160.0 E27.707
G1 X-5.2 Y4.23 Z0.63 F2160.0 E27.744
G1 X-5.6 Y4.23 Z0.63 F2160.0 E27.75
G1 X-5.6 Y1.46 Z0.63 F2160.0 E27.795
G1 X-6.0 Y0.95 Z0.63 F2160.0 E27.805
G1 X-6.0 Y4.23 Z0.63 F2160.0 E27.858
G1 X-6.4 Y4.23 Z0.63 F2160.0 E27.864
G1 X-6.4 Y0.45 Z0.63 F2160.0 E27.925
G1 X-6.8 Y-0.06 Z0.63 F2160.0 E27.936
G1 X-6.8 Y4.23 Z0.63 F2160.0 E28.004
G1 F1200.0
G1 E27.004
G1 F2160.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
;M108 R28.0
(<layer> 0.73 )
(<supportLayer>)
G1 X3.29 Y-5.4 Z0.73 F3300.0
G1 F1200.0
G1 E28.004
G1 F3300.0
M101
M73 P22 (display progress)
G1 X14.3 Y-5.4 Z0.73 F2400.0 E28.144
G1 X14.46 Y-3.6 Z0.73 F2400.0 E28.167
G1 X7.46 Y-3.6 Z0.73 F2400.0 E28.255
G1 F1200.0
G1 E27.255
G1 F2400.0
M103
G1 X8.89 Y-1.8 Z0.73 F3300.0
G1 F1200.0
G1 E28.255
G1 F3300.0
M101
G1 X14.31 Y-1.8 Z0.73 F2400.0 E28.324
G1 X14.16 Y0.0 Z0.73 F2400.0 E28.347
G1 X10.31 Y0.0 Z0.73 F2400.0 E28.396
G1 F1200.0
G1 E27.396
G1 F2400.0
M103
;M108 R20.0
(</supportLayer>)
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.378 Y2.234 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.378 Y3.912 Z0.73 </boundaryPoint>)
M73 P23 (display progress)
(<boundaryPoint> X-10.818 Y3.891 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.171 Y3.715 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.433 Y3.234 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.462 Y-3.147 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.42 Y-3.363 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.364 Y-3.494 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.254 Y-3.648 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.136 Y-3.761 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-10.941 Y-3.867 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-10.803 Y-3.91 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.378 Y-3.925 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.378 Y-2.248 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.7 Y-2.248 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.711 Y-3.958 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.669 Y-4.171 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.611 Y-4.307 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.507 Y-4.454 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.383 Y-4.571 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.198 Y-4.675 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.054 Y-4.719 Z0.73 </boundaryPoint>)
(<boundaryPoint> X6.058 Y-4.719 Z0.73 </boundaryPoint>)
(<boundaryPoint> X10.942 Y1.439 Z0.73 </boundaryPoint>)
(<boundaryPoint> X10.697 Y4.171 Z0.73 </boundaryPoint>)
(<boundaryPoint> X10.499 Y4.484 Z0.73 </boundaryPoint>)
(<boundaryPoint> X10.206 Y4.672 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-6.926 Y4.732 Z0.73 </boundaryPoint>)
M73 P24 (display progress)
(<boundaryPoint> X-7.143 Y4.687 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.272 Y4.633 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.384 Y4.557 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.553 Y4.375 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.635 Y4.233 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.687 Y4.048 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-7.7 Y2.234 Z0.73 </boundaryPoint>)
(<edge> outer )
G1 X9.42 Y0.16 Z0.73 F3300.0
G1 X-7.3 Y-2.62 Z0.73 F3300.0
G1 X-11.26 Y-3.13 Z0.73 F3300.0
G1 F1200.0
G1 E28.396
G1 F3300.0
M101
G1 X-11.23 Y-3.3 Z0.73 F1200.0 E28.399
G1 X-11.19 Y-3.4 Z0.73 F1200.0 E28.401
G1 X-11.1 Y-3.52 Z0.73 F1200.0 E28.404
G1 X-11.02 Y-3.6 Z0.73 F1200.0 E28.406
G1 X-10.86 Y-3.68 Z0.73 F1200.0 E28.409
G1 X-10.77 Y-3.71 Z0.73 F1200.0 E28.411
G1 X-9.58 Y-3.72 Z0.73 F1200.0 E28.432
G1 X-9.58 Y-2.05 Z0.73 F1200.0 E28.462
G1 X-7.5 Y-2.05 Z0.73 F1200.0 E28.5
G1 X-7.51 Y-3.94 Z0.73 F1200.0 E28.534
G1 X-7.48 Y-4.11 Z0.73 F1200.0 E28.537
M73 P25 (display progress)
G1 X-7.43 Y-4.21 Z0.73 F1200.0 E28.539
G1 X-7.36 Y-4.32 Z0.73 F1200.0 E28.542
G1 X-7.26 Y-4.41 Z0.73 F1200.0 E28.544
G1 X-7.12 Y-4.49 Z0.73 F1200.0 E28.547
G1 X-7.02 Y-4.52 Z0.73 F1200.0 E28.549
G1 X5.96 Y-4.52 Z0.73 F1200.0 E28.784
G1 X10.74 Y1.5 Z0.73 F1200.0 E28.923
G1 X10.5 Y4.11 Z0.73 F1200.0 E28.97
G1 X10.35 Y4.34 Z0.73 F1200.0 E28.975
G1 X10.15 Y4.47 Z0.73 F1200.0 E28.98
G1 X-6.91 Y4.53 Z0.73 F1200.0 E29.288
G1 X-7.08 Y4.5 Z0.73 F1200.0 E29.291
G1 X-7.18 Y4.46 Z0.73 F1200.0 E29.293
G1 X-7.25 Y4.4 Z0.73 F1200.0 E29.295
G1 X-7.39 Y4.25 Z0.73 F1200.0 E29.298
G1 X-7.45 Y4.16 Z0.73 F1200.0 E29.301
G1 X-7.49 Y4.02 Z0.73 F1200.0 E29.303
G1 X-7.5 Y2.03 Z0.73 F1200.0 E29.339
G1 X-9.58 Y2.03 Z0.73 F1200.0 E29.377
G1 X-9.58 Y3.71 Z0.73 F1200.0 E29.407
G1 X-10.77 Y3.69 Z0.73 F1200.0 E29.428
G1 X-11.03 Y3.56 Z0.73 F1200.0 E29.434
G1 X-11.23 Y3.18 Z0.73 F1200.0 E29.441
G1 X-11.26 Y-3.13 Z0.73 F1200.0 E29.556
G1 X-11.26 Y-3.13 Z0.73 F1200.0
G1 F1200.0
M73 P26 (display progress)
G1 E28.556
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.578 Y2.034 Z0.15 </infillPoint>)
(<infillPoint> X-9.578 Y3.709 Z0.15 </infillPoint>)
(<infillPoint> X-10.77 Y3.692 Z0.15 </infillPoint>)
(<infillPoint> X-11.025 Y3.564 Z0.15 </infillPoint>)
(<infillPoint> X-11.233 Y3.183 Z0.15 </infillPoint>)
(<infillPoint> X-11.262 Y-3.128 Z0.15 </infillPoint>)
(<infillPoint> X-11.228 Y-3.304 Z0.15 </infillPoint>)
(<infillPoint> X-11.189 Y-3.395 Z0.15 </infillPoint>)
(<infillPoint> X-11.102 Y-3.517 Z0.15 </infillPoint>)
(<infillPoint> X-11.017 Y-3.598 Z0.15 </infillPoint>)
(<infillPoint> X-10.863 Y-3.682 Z0.15 </infillPoint>)
(<infillPoint> X-10.772 Y-3.71 Z0.15 </infillPoint>)
(<infillPoint> X-9.578 Y-3.723 Z0.15 </infillPoint>)
(<infillPoint> X-9.578 Y-2.048 Z0.15 </infillPoint>)
(<infillPoint> X-7.499 Y-2.048 Z0.15 </infillPoint>)
(<infillPoint> X-7.511 Y-3.939 Z0.15 </infillPoint>)
(<infillPoint> X-7.477 Y-4.112 Z0.15 </infillPoint>)
(<infillPoint> X-7.435 Y-4.209 Z0.15 </infillPoint>)
(<infillPoint> X-7.355 Y-4.322 Z0.15 </infillPoint>)
M73 P27 (display progress)
(<infillPoint> X-7.264 Y-4.409 Z0.15 </infillPoint>)
(<infillPoint> X-7.119 Y-4.49 Z0.15 </infillPoint>)
(<infillPoint> X-7.024 Y-4.519 Z0.15 </infillPoint>)
(<infillPoint> X5.961 Y-4.519 Z0.15 </infillPoint>)
(<infillPoint> X10.736 Y1.501 Z0.15 </infillPoint>)
(<infillPoint> X10.502 Y4.105 Z0.15 </infillPoint>)
(<infillPoint> X10.354 Y4.34 Z0.15 </infillPoint>)
(<infillPoint> X10.147 Y4.472 Z0.15 </infillPoint>)
(<infillPoint> X-6.906 Y4.532 Z0.15 </infillPoint>)
(<infillPoint> X-7.084 Y4.495 Z0.15 </infillPoint>)
(<infillPoint> X-7.176 Y4.456 Z0.15 </infillPoint>)
(<infillPoint> X-7.253 Y4.404 Z0.15 </infillPoint>)
(<infillPoint> X-7.391 Y4.255 Z0.15 </infillPoint>)
(<infillPoint> X-7.449 Y4.155 Z0.15 </infillPoint>)
(<infillPoint> X-7.487 Y4.02 Z0.15 </infillPoint>)
(<infillPoint> X-7.501 Y2.034 Z0.15 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.58 Y-2.05 Z0.73 F3300.0
G1 X9.19 Y-0.0 Z0.73 F3300.0
G1 F1200.0
G1 E29.556
G1 F3300.0
M101
G1 X-10.96 Y0.0 Z0.73 F2400.0 E29.92
M73 P28 (display progress)
G1 X-10.96 Y-0.4 Z0.73 F2400.0 E29.927
G1 X8.87 Y-0.4 Z0.73 F2400.0 E30.286
G1 X8.55 Y-0.8 Z0.73 F2400.0 E30.295
G1 X-10.96 Y-0.8 Z0.73 F2400.0 E30.648
G1 X-10.96 Y-1.2 Z0.73 F2400.0 E30.655
G1 X8.24 Y-1.2 Z0.73 F2400.0 E31.002
G1 X7.92 Y-1.6 Z0.73 F2400.0 E31.012
G1 X-10.96 Y-1.6 Z0.73 F2400.0 E31.353
G1 X-10.96 Y-2.0 Z0.73 F2400.0 E31.36
G1 X-9.86 Y-2.0 Z0.73 F2400.0 E31.38
G1 X-9.86 Y-2.4 Z0.73 F2400.0 E31.388
G1 X-10.96 Y-2.4 Z0.73 F2400.0 E31.407
G1 X-10.96 Y-2.8 Z0.73 F2400.0 E31.415
G1 X-9.86 Y-2.8 Z0.73 F2400.0 E31.435
G1 X-9.86 Y-3.2 Z0.73 F2400.0 E31.442
G1 X-10.96 Y-3.2 Z0.73 F2400.0 E31.462
G1 F1200.0
G1 E30.462
G1 F2400.0
M103
G1 X-10.96 Y0.4 Z0.73 F3300.0
G1 F1200.0
G1 E31.462
G1 F3300.0
M101
G1 X9.51 Y0.4 Z0.73 F2400.0 E31.832
M73 P29 (display progress)
G1 X9.82 Y0.8 Z0.73 F2400.0 E31.841
G1 X-10.96 Y0.8 Z0.73 F2400.0 E32.217
G1 X-10.96 Y1.2 Z0.73 F2400.0 E32.224
G1 X10.14 Y1.2 Z0.73 F2400.0 E32.606
G1 X10.45 Y1.6 Z0.73 F2400.0 E32.615
G1 X-10.96 Y1.6 Z0.73 F2400.0 E33.002
G1 X-10.95 Y2.0 Z0.73 F2400.0 E33.009
G1 X-9.86 Y2.0 Z0.73 F2400.0 E33.029
G1 X-9.86 Y2.4 Z0.73 F2400.0 E33.036
G1 X-10.95 Y2.4 Z0.73 F2400.0 E33.056
G1 X-10.95 Y2.8 Z0.73 F2400.0 E33.063
G1 X-9.86 Y2.8 Z0.73 F2400.0 E33.083
G1 X-9.86 Y3.2 Z0.73 F2400.0 E33.09
G1 X-10.9 Y3.2 Z0.73 F2400.0 E33.109
G1 F1200.0
G1 E32.109
G1 F2400.0
M103
G1 X-9.58 Y2.03 Z0.73 F3300.0
G1 X-7.22 Y2.0 Z0.73 F3300.0
G1 F1200.0
G1 E33.109
G1 F3300.0
M101
G1 X10.41 Y2.0 Z0.73 F2400.0 E33.428
G1 X10.37 Y2.4 Z0.73 F2400.0 E33.435
M73 P30 (display progress)
G1 X-7.21 Y2.4 Z0.73 F2400.0 E33.754
G1 X-7.21 Y2.8 Z0.73 F2400.0 E33.761
G1 X10.34 Y2.8 Z0.73 F2400.0 E34.078
G1 X10.3 Y3.2 Z0.73 F2400.0 E34.085
G1 X-7.2 Y3.2 Z0.73 F2400.0 E34.402
G1 X-7.2 Y3.6 Z0.73 F2400.0 E34.409
G1 X10.27 Y3.6 Z0.73 F2400.0 E34.725
G1 X10.23 Y4.0 Z0.73 F2400.0 E34.732
G1 X-7.19 Y4.0 Z0.73 F2400.0 E35.048
G1 F1200.0
G1 E34.048
G1 F2400.0
M103
G1 X-7.22 Y-2.0 Z0.73 F3300.0
G1 F1200.0
G1 E35.048
G1 F3300.0
M101
G1 X7.6 Y-2.0 Z0.73 F2400.0 E35.316
G1 X7.29 Y-2.4 Z0.73 F2400.0 E35.325
G1 X-7.21 Y-2.4 Z0.73 F2400.0 E35.587
G1 X-7.21 Y-2.8 Z0.73 F2400.0 E35.594
G1 X6.97 Y-2.8 Z0.73 F2400.0 E35.851
G1 X6.65 Y-3.2 Z0.73 F2400.0 E35.86
G1 X-7.21 Y-3.2 Z0.73 F2400.0 E36.111
G1 X-7.21 Y-3.6 Z0.73 F2400.0 E36.118
M73 P31 (display progress)
G1 X6.33 Y-3.6 Z0.73 F2400.0 E36.363
G1 X6.02 Y-4.0 Z0.73 F2400.0 E36.372
G1 X-7.21 Y-4.0 Z0.73 F2400.0 E36.611
G1 F1200.0
G1 E35.611
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 0.83 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-7.701 Y2.234 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.379 Y2.234 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.379 Y3.912 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-10.805 Y3.894 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.172 Y3.715 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.425 Y3.267 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.448 Y3.161 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.463 Y-3.143 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.414 Y-3.378 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.367 Y-3.49 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.241 Y-3.661 Z0.83 </boundaryPoint>)
M73 P32 (display progress)
(<boundaryPoint> X-11.139 Y-3.758 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-10.922 Y-3.873 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-10.803 Y-3.909 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.379 Y-3.925 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.379 Y-2.247 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.701 Y-2.247 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.712 Y-3.954 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.662 Y-4.189 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.612 Y-4.307 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.494 Y-4.467 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.386 Y-4.568 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.182 Y-4.68 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.058 Y-4.717 Z0.83 </boundaryPoint>)
(<boundaryPoint> X10.837 Y-4.715 Z0.83 </boundaryPoint>)
(<boundaryPoint> X11.2 Y-4.534 Z0.83 </boundaryPoint>)
(<boundaryPoint> X11.407 Y-4.249 Z0.83 </boundaryPoint>)
(<boundaryPoint> X10.697 Y4.171 Z0.83 </boundaryPoint>)
(<boundaryPoint> X10.524 Y4.445 Z0.83 </boundaryPoint>)
(<boundaryPoint> X10.194 Y4.676 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-6.926 Y4.733 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.272 Y4.634 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.368 Y4.568 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.566 Y4.355 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.636 Y4.233 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-7.701 Y3.912 Z0.83 </boundaryPoint>)
(<edge> outer )
M73 P33 (display progress)
;M108 R20.0
G1 X-7.5 Y-2.05 Z0.83 F3300.0
G1 X-9.58 Y-2.05 Z0.83 F3300.0
G1 X-11.04 Y-3.57 Z0.83 F3300.0
G1 F1200.0
G1 E36.611
G1 F3300.0
M101
G1 X-11.02 Y-3.59 Z0.83 F1200.0 E36.612
G1 X-10.85 Y-3.69 Z0.83 F1200.0 E36.616
G1 X-10.77 Y-3.71 Z0.83 F1200.0 E36.617
G1 X-9.58 Y-3.72 Z0.83 F1200.0 E36.639
G1 X-9.58 Y-2.05 Z0.83 F1200.0 E36.669
G1 X-7.5 Y-2.05 Z0.83 F1200.0 E36.706
G1 X-7.51 Y-3.93 Z0.83 F1200.0 E36.741
G1 X-7.47 Y-4.13 Z0.83 F1200.0 E36.744
G1 X-7.44 Y-4.21 Z0.83 F1200.0 E36.746
G1 X-7.34 Y-4.33 Z0.83 F1200.0 E36.749
G1 X-7.27 Y-4.41 Z0.83 F1200.0 E36.75
G1 X-7.1 Y-4.49 Z0.83 F1200.0 E36.754
G1 X-7.03 Y-4.52 Z0.83 F1200.0 E36.755
G1 X10.79 Y-4.51 Z0.83 F1200.0 E37.078
G1 X11.07 Y-4.38 Z0.83 F1200.0 E37.083
G1 X11.2 Y-4.19 Z0.83 F1200.0 E37.087
G1 X10.5 Y4.11 Z0.83 F1200.0 E37.238
G1 X10.38 Y4.3 Z0.83 F1200.0 E37.242
M73 P34 (display progress)
G1 X10.13 Y4.48 Z0.83 F1200.0 E37.248
G1 X-6.9 Y4.53 Z0.83 F1200.0 E37.556
G1 X-7.19 Y4.45 Z0.83 F1200.0 E37.561
G1 X-7.24 Y4.42 Z0.83 F1200.0 E37.562
G1 X-7.4 Y4.24 Z0.83 F1200.0 E37.567
G1 X-7.45 Y4.16 Z0.83 F1200.0 E37.568
G1 X-7.5 Y3.89 Z0.83 F1200.0 E37.573
G1 X-7.5 Y2.03 Z0.83 F1200.0 E37.607
G1 X-9.58 Y2.03 Z0.83 F1200.0 E37.644
G1 X-9.58 Y3.71 Z0.83 F1200.0 E37.675
G1 X-10.76 Y3.69 Z0.83 F1200.0 E37.696
G1 X-11.03 Y3.56 Z0.83 F1200.0 E37.701
G1 X-11.24 Y3.19 Z0.83 F1200.0 E37.709
G1 X-11.25 Y3.14 Z0.83 F1200.0 E37.71
G1 X-11.26 Y-3.12 Z0.83 F1200.0 E37.823
G1 X-11.22 Y-3.32 Z0.83 F1200.0 E37.827
G1 X-11.19 Y-3.39 Z0.83 F1200.0 E37.828
G1 X-11.09 Y-3.53 Z0.83 F1200.0 E37.831
G1 X-11.04 Y-3.57 Z0.83 F1200.0 E37.833
G1 F1200.0
G1 E36.833
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
M73 P35 (display progress)
(<infillBoundary>)
(<infillPoint> X-7.501 Y2.034 Z0.25 </infillPoint>)
(<infillPoint> X-9.579 Y2.034 Z0.25 </infillPoint>)
(<infillPoint> X-9.579 Y3.709 Z0.25 </infillPoint>)
(<infillPoint> X-10.758 Y3.695 Z0.25 </infillPoint>)
(<infillPoint> X-11.028 Y3.563 Z0.25 </infillPoint>)
(<infillPoint> X-11.236 Y3.195 Z0.25 </infillPoint>)
(<infillPoint> X-11.248 Y3.139 Z0.25 </infillPoint>)
(<infillPoint> X-11.263 Y-3.123 Z0.25 </infillPoint>)
(<infillPoint> X-11.222 Y-3.318 Z0.25 </infillPoint>)
(<infillPoint> X-11.192 Y-3.391 Z0.25 </infillPoint>)
(<infillPoint> X-11.09 Y-3.528 Z0.25 </infillPoint>)
(<infillPoint> X-11.021 Y-3.594 Z0.25 </infillPoint>)
(<infillPoint> X-10.846 Y-3.687 Z0.25 </infillPoint>)
(<infillPoint> X-10.772 Y-3.709 Z0.25 </infillPoint>)
(<infillPoint> X-9.579 Y-3.723 Z0.25 </infillPoint>)
(<infillPoint> X-9.579 Y-2.047 Z0.25 </infillPoint>)
(<infillPoint> X-7.5 Y-2.047 Z0.25 </infillPoint>)
(<infillPoint> X-7.512 Y-3.934 Z0.25 </infillPoint>)
(<infillPoint> X-7.47 Y-4.129 Z0.25 </infillPoint>)
(<infillPoint> X-7.437 Y-4.207 Z0.25 </infillPoint>)
(<infillPoint> X-7.344 Y-4.333 Z0.25 </infillPoint>)
(<infillPoint> X-7.268 Y-4.405 Z0.25 </infillPoint>)
(<infillPoint> X-7.104 Y-4.494 Z0.25 </infillPoint>)
(<infillPoint> X-7.029 Y-4.517 Z0.25 </infillPoint>)
(<infillPoint> X10.79 Y-4.515 Z0.25 </infillPoint>)
M73 P36 (display progress)
(<infillPoint> X11.067 Y-4.377 Z0.25 </infillPoint>)
(<infillPoint> X11.201 Y-4.192 Z0.25 </infillPoint>)
(<infillPoint> X10.502 Y4.106 Z0.25 </infillPoint>)
(<infillPoint> X10.376 Y4.304 Z0.25 </infillPoint>)
(<infillPoint> X10.131 Y4.476 Z0.25 </infillPoint>)
(<infillPoint> X-6.898 Y4.533 Z0.25 </infillPoint>)
(<infillPoint> X-7.186 Y4.451 Z0.25 </infillPoint>)
(<infillPoint> X-7.237 Y4.416 Z0.25 </infillPoint>)
(<infillPoint> X-7.404 Y4.236 Z0.25 </infillPoint>)
(<infillPoint> X-7.446 Y4.162 Z0.25 </infillPoint>)
(<infillPoint> X-7.501 Y3.892 Z0.25 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-10.0 Y3.34 Z0.83 F3300.0
G1 F1200.0
G1 E37.833
G1 F3300.0
M101
G1 X-10.0 Y-3.35 Z0.83 F2400.0 E37.954
G1 X-10.4 Y-3.43 Z0.83 F2400.0 E37.961
G1 X-10.4 Y3.42 Z0.83 F2400.0 E38.085
G1 X-10.8 Y3.36 Z0.83 F2400.0 E38.092
G1 X-10.8 Y-3.39 Z0.83 F2400.0 E38.215
G1 F1200.0
G1 E37.215
M73 P37 (display progress)
G1 F2400.0
M103
G1 X-7.6 Y1.75 Z0.83 F3300.0
G1 F1200.0
G1 E38.215
G1 F3300.0
M101
G1 X-7.6 Y-1.77 Z0.83 F2400.0 E38.278
G1 X-8.0 Y-1.77 Z0.83 F2400.0 E38.286
G1 X-8.0 Y1.75 Z0.83 F2400.0 E38.349
G1 X-8.4 Y1.75 Z0.83 F2400.0 E38.356
G1 X-8.4 Y-1.77 Z0.83 F2400.0 E38.42
G1 X-8.8 Y-1.77 Z0.83 F2400.0 E38.427
G1 X-8.8 Y1.75 Z0.83 F2400.0 E38.491
G1 X-9.2 Y1.75 Z0.83 F2400.0 E38.498
G1 X-9.2 Y-1.77 Z0.83 F2400.0 E38.562
G1 X-9.6 Y-1.77 Z0.83 F2400.0 E38.569
G1 X-9.6 Y1.75 Z0.83 F2400.0 E38.633
G1 F1200.0
G1 E37.633
G1 F2400.0
M103
G1 X-7.5 Y2.03 Z0.83 F3300.0
G1 X-7.2 Y3.96 Z0.83 F3300.0
G1 F1200.0
G1 E38.633
M73 P38 (display progress)
G1 F3300.0
M101
G1 X-7.2 Y-4.04 Z0.83 F2400.0 E38.778
G1 X-6.8 Y-4.24 Z0.83 F2400.0 E38.786
G1 X-6.8 Y4.25 Z0.83 F2400.0 E38.939
G1 X-6.4 Y4.25 Z0.83 F2400.0 E38.946
G1 X-6.4 Y-4.24 Z0.83 F2400.0 E39.1
G1 X-6.0 Y-4.24 Z0.83 F2400.0 E39.107
G1 X-6.0 Y4.25 Z0.83 F2400.0 E39.261
G1 X-5.6 Y4.25 Z0.83 F2400.0 E39.268
G1 X-5.6 Y-4.24 Z0.83 F2400.0 E39.422
G1 X-5.2 Y-4.24 Z0.83 F2400.0 E39.429
G1 X-5.2 Y4.25 Z0.83 F2400.0 E39.582
G1 X-4.8 Y4.25 Z0.83 F2400.0 E39.589
G1 X-4.8 Y-4.24 Z0.83 F2400.0 E39.743
G1 X-4.4 Y-4.24 Z0.83 F2400.0 E39.75
G1 X-4.4 Y4.25 Z0.83 F2400.0 E39.904
G1 X-4.0 Y4.24 Z0.83 F2400.0 E39.911
G1 X-4.0 Y-4.24 Z0.83 F2400.0 E40.064
G1 X-3.6 Y-4.24 Z0.83 F2400.0 E40.071
G1 X-3.6 Y4.24 Z0.83 F2400.0 E40.225
G1 X-3.2 Y4.24 Z0.83 F2400.0 E40.232
G1 X-3.2 Y-4.24 Z0.83 F2400.0 E40.385
G1 X-2.8 Y-4.24 Z0.83 F2400.0 E40.393
G1 X-2.8 Y4.24 Z0.83 F2400.0 E40.546
G1 X-2.4 Y4.24 Z0.83 F2400.0 E40.553
M73 P39 (display progress)
G1 X-2.4 Y-4.24 Z0.83 F2400.0 E40.706
G1 X-2.0 Y-4.24 Z0.83 F2400.0 E40.714
G1 X-2.0 Y4.24 Z0.83 F2400.0 E40.867
G1 X-1.6 Y4.24 Z0.83 F2400.0 E40.874
G1 X-1.6 Y-4.24 Z0.83 F2400.0 E41.027
G1 X-1.2 Y-4.24 Z0.83 F2400.0 E41.035
G1 X-1.2 Y4.23 Z0.83 F2400.0 E41.188
G1 X-0.8 Y4.23 Z0.83 F2400.0 E41.195
G1 X-0.8 Y-4.24 Z0.83 F2400.0 E41.348
G1 X-0.4 Y-4.24 Z0.83 F2400.0 E41.356
G1 X-0.4 Y4.23 Z0.83 F2400.0 E41.509
G1 X0.0 Y4.23 Z0.83 F2400.0 E41.516
G1 X-0.0 Y-4.24 Z0.83 F2400.0 E41.669
G1 X0.4 Y-4.24 Z0.83 F2400.0 E41.676
G1 X0.4 Y4.23 Z0.83 F2400.0 E41.829
G1 X0.8 Y4.23 Z0.83 F2400.0 E41.837
G1 X0.8 Y-4.24 Z0.83 F2400.0 E41.99
G1 X1.2 Y-4.24 Z0.83 F2400.0 E41.997
G1 X1.2 Y4.23 Z0.83 F2400.0 E42.15
G1 X1.6 Y4.22 Z0.83 F2400.0 E42.157
G1 X1.6 Y-4.24 Z0.83 F2400.0 E42.31
G1 X2.0 Y-4.24 Z0.83 F2400.0 E42.318
G1 X2.0 Y4.22 Z0.83 F2400.0 E42.471
G1 X2.4 Y4.22 Z0.83 F2400.0 E42.478
G1 X2.4 Y-4.24 Z0.83 F2400.0 E42.631
G1 X2.8 Y-4.24 Z0.83 F2400.0 E42.638
M73 P40 (display progress)
G1 X2.8 Y4.22 Z0.83 F2400.0 E42.791
G1 X3.2 Y4.22 Z0.83 F2400.0 E42.798
G1 X3.2 Y-4.24 Z0.83 F2400.0 E42.951
G1 X3.6 Y-4.24 Z0.83 F2400.0 E42.958
G1 X3.6 Y4.22 Z0.83 F2400.0 E43.111
G1 X4.0 Y4.22 Z0.83 F2400.0 E43.119
G1 X4.0 Y-4.24 Z0.83 F2400.0 E43.271
G1 X4.4 Y-4.24 Z0.83 F2400.0 E43.279
G1 X4.4 Y4.21 Z0.83 F2400.0 E43.432
G1 X4.8 Y4.21 Z0.83 F2400.0 E43.439
G1 X4.8 Y-4.24 Z0.83 F2400.0 E43.592
G1 X5.2 Y-4.24 Z0.83 F2400.0 E43.599
G1 X5.2 Y4.21 Z0.83 F2400.0 E43.752
G1 X5.6 Y4.21 Z0.83 F2400.0 E43.759
G1 X5.6 Y-4.24 Z0.83 F2400.0 E43.912
G1 X6.0 Y-4.24 Z0.83 F2400.0 E43.919
G1 X6.0 Y4.21 Z0.83 F2400.0 E44.072
G1 X6.4 Y4.21 Z0.83 F2400.0 E44.079
G1 X6.4 Y-4.24 Z0.83 F2400.0 E44.232
G1 X6.8 Y-4.24 Z0.83 F2400.0 E44.239
G1 X6.8 Y4.21 Z0.83 F2400.0 E44.392
G1 X7.2 Y4.21 Z0.83 F2400.0 E44.399
G1 X7.2 Y-4.24 Z0.83 F2400.0 E44.552
G1 X7.6 Y-4.24 Z0.83 F2400.0 E44.559
G1 X7.6 Y4.21 Z0.83 F2400.0 E44.712
G1 X8.0 Y4.2 Z0.83 F2400.0 E44.719
M73 P41 (display progress)
G1 X8.0 Y-4.24 Z0.83 F2400.0 E44.871
G1 X8.4 Y-4.24 Z0.83 F2400.0 E44.879
G1 X8.4 Y4.2 Z0.83 F2400.0 E45.031
G1 X8.8 Y4.2 Z0.83 F2400.0 E45.038
G1 X8.8 Y-4.24 Z0.83 F2400.0 E45.191
G1 X9.2 Y-4.24 Z0.83 F2400.0 E45.198
G1 X9.2 Y4.2 Z0.83 F2400.0 E45.351
G1 X9.6 Y4.2 Z0.83 F2400.0 E45.358
G1 X9.6 Y-4.24 Z0.83 F2400.0 E45.511
G1 X10.0 Y-4.24 Z0.83 F2400.0 E45.518
G1 X10.0 Y4.2 Z0.83 F2400.0 E45.67
G1 F1200.0
G1 E44.67
G1 F2400.0
M103
G1 X10.4 Y1.98 Z0.83 F3300.0
G1 F1200.0
G1 E45.67
G1 F3300.0
M101
G1 X10.4 Y-4.24 Z0.83 F2400.0 E45.783
G1 X10.8 Y-4.2 Z0.83 F2400.0 E45.79
G1 X10.8 Y-2.76 Z0.83 F2400.0 E45.816
G1 F1200.0
G1 E44.816
G1 F2400.0
M73 P42 (display progress)
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 0.93 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.38 Y2.235 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.38 Y3.913 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-10.791 Y3.897 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.185 Y3.71 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.416 Y3.304 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.45 Y3.151 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-3.139 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.369 Y-3.487 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.143 Y-3.755 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-10.804 Y-3.909 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.379 Y-3.925 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.38 Y-2.247 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.701 Y-2.247 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.713 Y-3.95 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.612 Y-4.306 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.39 Y-4.566 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.063 Y-4.716 Z0.93 </boundaryPoint>)
M73 P43 (display progress)
(<boundaryPoint> X10.814 Y-4.717 Z0.93 </boundaryPoint>)
(<boundaryPoint> X11.213 Y-4.521 Z0.93 </boundaryPoint>)
(<boundaryPoint> X11.417 Y-4.242 Z0.93 </boundaryPoint>)
(<boundaryPoint> X10.696 Y4.172 Z0.93 </boundaryPoint>)
(<boundaryPoint> X10.548 Y4.406 Z0.93 </boundaryPoint>)
(<boundaryPoint> X10.34 Y4.537 Z0.93 </boundaryPoint>)
(<boundaryPoint> X10.183 Y4.68 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-6.927 Y4.733 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.297 Y4.627 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.631 Y4.255 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.692 Y4.009 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-7.701 Y2.235 Z0.93 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z0.93 F3300.0
G1 X-9.58 Y-2.05 Z0.93 F3300.0
G1 X-11.17 Y-3.41 Z0.93 F3300.0
G1 F1200.0
G1 E45.816
G1 F3300.0
M101
G1 X-11.02 Y-3.59 Z0.93 F1200.0 E45.82
G1 X-10.76 Y-3.71 Z0.93 F1200.0 E45.826
G1 X-9.58 Y-3.72 Z0.93 F1200.0 E45.847
G1 X-9.58 Y-2.05 Z0.93 F1200.0 E45.877
G1 X-7.5 Y-2.05 Z0.93 F1200.0 E45.915
M73 P44 (display progress)
G1 X-7.51 Y-3.92 Z0.93 F1200.0 E45.949
G1 X-7.43 Y-4.21 Z0.93 F1200.0 E45.954
G1 X-7.27 Y-4.4 Z0.93 F1200.0 E45.959
G1 X-7.02 Y-4.52 Z0.93 F1200.0 E45.964
G1 X10.77 Y-4.52 Z0.93 F1200.0 E46.285
G1 X11.08 Y-4.36 Z0.93 F1200.0 E46.292
G1 X11.21 Y-4.18 Z0.93 F1200.0 E46.296
G1 X10.5 Y4.11 Z0.93 F1200.0 E46.446
G1 X10.4 Y4.26 Z0.93 F1200.0 E46.45
G1 X10.22 Y4.38 Z0.93 F1200.0 E46.454
G1 X10.11 Y4.48 Z0.93 F1200.0 E46.456
G1 X-6.9 Y4.53 Z0.93 F1200.0 E46.764
G1 X-7.19 Y4.45 Z0.93 F1200.0 E46.769
G1 X-7.45 Y4.16 Z0.93 F1200.0 E46.776
G1 X-7.49 Y3.98 Z0.93 F1200.0 E46.78
G1 X-7.5 Y2.04 Z0.93 F1200.0 E46.815
G1 X-9.58 Y2.04 Z0.93 F1200.0 E46.852
G1 X-9.58 Y3.71 Z0.93 F1200.0 E46.883
G1 X-10.74 Y3.7 Z0.93 F1200.0 E46.904
G1 X-11.04 Y3.56 Z0.93 F1200.0 E46.91
G1 X-11.23 Y3.23 Z0.93 F1200.0 E46.917
G1 X-11.25 Y3.13 Z0.93 F1200.0 E46.918
G1 X-11.26 Y-3.11 Z0.93 F1200.0 E47.031
G1 X-11.19 Y-3.39 Z0.93 F1200.0 E47.037
G1 X-11.17 Y-3.41 Z0.93 F1200.0 E47.037
G1 F1200.0
M73 P45 (display progress)
G1 E46.037
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.58 Y2.035 Z0.35 </infillPoint>)
(<infillPoint> X-9.58 Y3.711 Z0.35 </infillPoint>)
(<infillPoint> X-10.745 Y3.698 Z0.35 </infillPoint>)
(<infillPoint> X-11.042 Y3.556 Z0.35 </infillPoint>)
(<infillPoint> X-11.227 Y3.231 Z0.35 </infillPoint>)
(<infillPoint> X-11.25 Y3.129 Z0.35 </infillPoint>)
(<infillPoint> X-11.264 Y-3.112 Z0.35 </infillPoint>)
(<infillPoint> X-11.188 Y-3.392 Z0.35 </infillPoint>)
(<infillPoint> X-11.019 Y-3.592 Z0.35 </infillPoint>)
(<infillPoint> X-10.76 Y-3.709 Z0.35 </infillPoint>)
(<infillPoint> X-9.579 Y-3.723 Z0.35 </infillPoint>)
(<infillPoint> X-9.58 Y-2.047 Z0.35 </infillPoint>)
(<infillPoint> X-7.5 Y-2.047 Z0.35 </infillPoint>)
(<infillPoint> X-7.513 Y-3.923 Z0.35 </infillPoint>)
(<infillPoint> X-7.432 Y-4.209 Z0.35 </infillPoint>)
(<infillPoint> X-7.267 Y-4.403 Z0.35 </infillPoint>)
(<infillPoint> X-7.019 Y-4.516 Z0.35 </infillPoint>)
(<infillPoint> X10.768 Y-4.517 Z0.35 </infillPoint>)
M73 P46 (display progress)
(<infillPoint> X11.081 Y-4.363 Z0.35 </infillPoint>)
(<infillPoint> X11.211 Y-4.184 Z0.35 </infillPoint>)
(<infillPoint> X10.501 Y4.106 Z0.35 </infillPoint>)
(<infillPoint> X10.403 Y4.261 Z0.35 </infillPoint>)
(<infillPoint> X10.218 Y4.377 Z0.35 </infillPoint>)
(<infillPoint> X10.105 Y4.48 Z0.35 </infillPoint>)
(<infillPoint> X-6.899 Y4.533 Z0.35 </infillPoint>)
(<infillPoint> X-7.187 Y4.451 Z0.35 </infillPoint>)
(<infillPoint> X-7.449 Y4.158 Z0.35 </infillPoint>)
(<infillPoint> X-7.492 Y3.984 Z0.35 </infillPoint>)
(<infillPoint> X-7.502 Y2.035 Z0.35 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.58 Y-2.05 Z0.93 F3300.0
G1 X10.57 Y-0.0 Z0.93 F3300.0
G1 F1200.0
G1 E47.037
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z0.93 F2400.0 E47.427
G1 X-10.98 Y-0.4 Z0.93 F2400.0 E47.434
G1 X10.61 Y-0.4 Z0.93 F2400.0 E47.824
G1 X10.64 Y-0.8 Z0.93 F2400.0 E47.832
G1 X-10.98 Y-0.8 Z0.93 F2400.0 E48.223
G1 X-10.98 Y-1.2 Z0.93 F2400.0 E48.23
G1 X10.68 Y-1.2 Z0.93 F2400.0 E48.622
M73 P47 (display progress)
G1 X10.71 Y-1.6 Z0.93 F2400.0 E48.629
G1 X-10.98 Y-1.6 Z0.93 F2400.0 E49.021
G1 X-10.98 Y-2.0 Z0.93 F2400.0 E49.029
G1 X-9.86 Y-2.0 Z0.93 F2400.0 E49.049
G1 X-9.86 Y-2.4 Z0.93 F2400.0 E49.056
G1 X-10.98 Y-2.4 Z0.93 F2400.0 E49.076
G1 X-10.98 Y-2.8 Z0.93 F2400.0 E49.084
G1 X-9.86 Y-2.8 Z0.93 F2400.0 E49.104
G1 X-9.86 Y-3.2 Z0.93 F2400.0 E49.111
G1 X-10.95 Y-3.2 Z0.93 F2400.0 E49.131
G1 F1200.0
G1 E48.131
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z0.93 F3300.0
G1 F1200.0
G1 E49.131
G1 F3300.0
M101
G1 X10.54 Y0.4 Z0.93 F2400.0 E49.52
G1 X10.5 Y0.8 Z0.93 F2400.0 E49.527
G1 X-10.97 Y0.8 Z0.93 F2400.0 E49.916
G1 X-10.97 Y1.2 Z0.93 F2400.0 E49.923
G1 X10.47 Y1.2 Z0.93 F2400.0 E50.311
G1 X10.44 Y1.6 Z0.93 F2400.0 E50.318
G1 X-10.97 Y1.6 Z0.93 F2400.0 E50.705
M73 P48 (display progress)
G1 X-10.97 Y2.0 Z0.93 F2400.0 E50.713
G1 X-9.86 Y2.0 Z0.93 F2400.0 E50.733
G1 X-9.86 Y2.4 Z0.93 F2400.0 E50.74
G1 X-10.97 Y2.4 Z0.93 F2400.0 E50.76
G1 X-10.97 Y2.8 Z0.93 F2400.0 E50.767
G1 X-9.86 Y2.8 Z0.93 F2400.0 E50.788
G1 X-9.86 Y3.2 Z0.93 F2400.0 E50.795
G1 X-10.92 Y3.2 Z0.93 F2400.0 E50.814
G1 F1200.0
G1 E49.814
G1 F2400.0
M103
G1 X-9.58 Y2.04 Z0.93 F3300.0
G1 X-7.5 Y2.03 Z0.93 F3300.0
G1 X-7.21 Y3.2 Z0.93 F3300.0
G1 F1200.0
G1 E50.814
G1 F3300.0
M101
G1 X10.3 Y3.2 Z0.93 F2400.0 E51.13
G1 X10.26 Y3.6 Z0.93 F2400.0 E51.138
G1 X-7.2 Y3.6 Z0.93 F2400.0 E51.454
G1 X-7.19 Y4.0 Z0.93 F2400.0 E51.461
G1 X10.23 Y4.0 Z0.93 F2400.0 E51.776
G1 F1200.0
G1 E51.572
M73 P49 (display progress)
G1 F2400.0
M103
G1 X10.33 Y2.8 Z0.93 F3300.0
G1 F1200.0
G1 E51.776
G1 F3300.0
M101
G1 X-7.21 Y2.8 Z0.93 F2400.0 E52.093
G1 X-7.21 Y2.4 Z0.93 F2400.0 E52.101
G1 X10.37 Y2.4 Z0.93 F2400.0 E52.419
G1 X10.4 Y2.0 Z0.93 F2400.0 E52.426
G1 X-7.22 Y2.0 Z0.93 F2400.0 E52.745
G1 F1200.0
G1 E51.745
G1 F2400.0
M103
G1 X-7.22 Y-2.0 Z0.93 F3300.0
G1 F1200.0
G1 E52.745
G1 F3300.0
M101
G1 X10.74 Y-2.0 Z0.93 F2400.0 E53.069
G1 X10.78 Y-2.4 Z0.93 F2400.0 E53.077
G1 X-7.22 Y-2.4 Z0.93 F2400.0 E53.402
G1 X-7.22 Y-2.8 Z0.93 F2400.0 E53.41
G1 X10.81 Y-2.8 Z0.93 F2400.0 E53.736
M73 P50 (display progress)
G1 X10.85 Y-3.2 Z0.93 F2400.0 E53.743
G1 X-7.23 Y-3.2 Z0.93 F2400.0 E54.07
G1 X-7.23 Y-3.6 Z0.93 F2400.0 E54.077
G1 X10.88 Y-3.6 Z0.93 F2400.0 E54.405
G1 X10.91 Y-4.0 Z0.93 F2400.0 E54.412
G1 X-7.2 Y-4.0 Z0.93 F2400.0 E54.74
G1 F1200.0
G1 E53.74
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
(<layer> 1.03 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.38 Y2.235 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.381 Y3.913 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-10.778 Y3.9 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.184 Y3.711 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.408 Y3.339 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.451 Y3.141 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.465 Y-3.135 Z1.03 </boundaryPoint>)
M73 P51 (display progress)
(<boundaryPoint> X-11.371 Y-3.483 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.146 Y-3.753 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-10.805 Y-3.908 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.38 Y-3.924 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.38 Y-2.246 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.702 Y-2.246 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.713 Y-3.946 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.613 Y-4.306 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.393 Y-4.563 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.067 Y-4.715 Z1.03 </boundaryPoint>)
(<boundaryPoint> X10.79 Y-4.72 Z1.03 </boundaryPoint>)
(<boundaryPoint> X11.221 Y-4.51 Z1.03 </boundaryPoint>)
(<boundaryPoint> X11.361 Y-4.329 Z1.03 </boundaryPoint>)
(<boundaryPoint> X11.423 Y-4.186 Z1.03 </boundaryPoint>)
(<boundaryPoint> X10.696 Y4.172 Z1.03 </boundaryPoint>)
(<boundaryPoint> X10.572 Y4.367 Z1.03 </boundaryPoint>)
(<boundaryPoint> X10.399 Y4.476 Z1.03 </boundaryPoint>)
(<boundaryPoint> X10.171 Y4.684 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-6.928 Y4.734 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.297 Y4.628 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.632 Y4.255 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.694 Y3.989 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-7.702 Y2.235 Z1.03 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z1.03 F3300.0
M73 P52 (display progress)
G1 X-9.58 Y-2.05 Z1.03 F3300.0
G1 X-10.79 Y-3.69 Z1.03 F3300.0
G1 F1200.0
G1 E54.74
G1 F3300.0
M101
G1 X-10.76 Y-3.71 Z1.03 F1200.0 E54.74
G1 X-9.58 Y-3.72 Z1.03 F1200.0 E54.762
G1 X-9.58 Y-2.05 Z1.03 F1200.0 E54.792
G1 X-7.5 Y-2.05 Z1.03 F1200.0 E54.83
G1 X-7.51 Y-3.92 Z1.03 F1200.0 E54.864
G1 X-7.43 Y-4.21 Z1.03 F1200.0 E54.869
G1 X-7.27 Y-4.4 Z1.03 F1200.0 E54.874
G1 X-7.02 Y-4.51 Z1.03 F1200.0 E54.878
G1 X10.74 Y-4.52 Z1.03 F1200.0 E55.2
G1 X11.09 Y-4.35 Z1.03 F1200.0 E55.207
G1 X11.19 Y-4.23 Z1.03 F1200.0 E55.21
G1 X11.22 Y-4.15 Z1.03 F1200.0 E55.211
G1 X10.5 Y4.11 Z1.03 F1200.0 E55.361
G1 X10.43 Y4.22 Z1.03 F1200.0 E55.364
G1 X10.28 Y4.32 Z1.03 F1200.0 E55.367
G1 X10.09 Y4.48 Z1.03 F1200.0 E55.371
G1 X-6.9 Y4.53 Z1.03 F1200.0 E55.679
G1 X-7.19 Y4.45 Z1.03 F1200.0 E55.684
G1 X-7.45 Y4.16 Z1.03 F1200.0 E55.691
G1 X-7.49 Y3.97 Z1.03 F1200.0 E55.695
M73 P53 (display progress)
G1 X-7.5 Y2.04 Z1.03 F1200.0 E55.73
G1 X-9.58 Y2.04 Z1.03 F1200.0 E55.767
G1 X-9.58 Y3.71 Z1.03 F1200.0 E55.798
G1 X-10.73 Y3.7 Z1.03 F1200.0 E55.818
G1 X-11.04 Y3.56 Z1.03 F1200.0 E55.825
G1 X-11.22 Y3.26 Z1.03 F1200.0 E55.831
G1 X-11.25 Y3.12 Z1.03 F1200.0 E55.833
G1 X-11.27 Y-3.11 Z1.03 F1200.0 E55.946
G1 X-11.19 Y-3.39 Z1.03 F1200.0 E55.951
G1 X-11.02 Y-3.59 Z1.03 F1200.0 E55.956
G1 X-10.79 Y-3.69 Z1.03 F1200.0 E55.961
G1 F1200.0
G1 E54.961
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.58 Y2.035 Z0.45 </infillPoint>)
(<infillPoint> X-9.581 Y3.711 Z0.45 </infillPoint>)
(<infillPoint> X-10.733 Y3.7 Z0.45 </infillPoint>)
(<infillPoint> X-11.044 Y3.555 Z0.45 </infillPoint>)
(<infillPoint> X-11.22 Y3.264 Z0.45 </infillPoint>)
(<infillPoint> X-11.251 Y3.119 Z0.45 </infillPoint>)
(<infillPoint> X-11.265 Y-3.109 Z0.45 </infillPoint>)
M73 P54 (display progress)
(<infillPoint> X-11.189 Y-3.389 Z0.45 </infillPoint>)
(<infillPoint> X-11.022 Y-3.59 Z0.45 </infillPoint>)
(<infillPoint> X-10.761 Y-3.708 Z0.45 </infillPoint>)
(<infillPoint> X-9.58 Y-3.722 Z0.45 </infillPoint>)
(<infillPoint> X-9.58 Y-2.046 Z0.45 </infillPoint>)
(<infillPoint> X-7.501 Y-2.046 Z0.45 </infillPoint>)
(<infillPoint> X-7.513 Y-3.919 Z0.45 </infillPoint>)
(<infillPoint> X-7.432 Y-4.21 Z0.45 </infillPoint>)
(<infillPoint> X-7.269 Y-4.4 Z0.45 </infillPoint>)
(<infillPoint> X-7.023 Y-4.515 Z0.45 </infillPoint>)
(<infillPoint> X10.744 Y-4.52 Z0.45 </infillPoint>)
(<infillPoint> X11.091 Y-4.351 Z0.45 </infillPoint>)
(<infillPoint> X11.187 Y-4.226 Z0.45 </infillPoint>)
(<infillPoint> X11.219 Y-4.153 Z0.45 </infillPoint>)
(<infillPoint> X10.501 Y4.106 Z0.45 </infillPoint>)
(<infillPoint> X10.427 Y4.222 Z0.45 </infillPoint>)
(<infillPoint> X10.277 Y4.316 Z0.45 </infillPoint>)
(<infillPoint> X10.093 Y4.484 Z0.45 </infillPoint>)
(<infillPoint> X-6.9 Y4.534 Z0.45 </infillPoint>)
(<infillPoint> X-7.187 Y4.452 Z0.45 </infillPoint>)
(<infillPoint> X-7.449 Y4.16 Z0.45 </infillPoint>)
(<infillPoint> X-7.494 Y3.966 Z0.45 </infillPoint>)
(<infillPoint> X-7.503 Y2.035 Z0.45 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
M73 P55 (display progress)
G1 X-10.0 Y3.34 Z1.03 F3300.0
G1 F1200.0
G1 E55.961
G1 F3300.0
M101
G1 X-10.0 Y-3.35 Z1.03 F2400.0 E56.082
G1 X-10.4 Y-3.43 Z1.03 F2400.0 E56.089
G1 X-10.4 Y3.42 Z1.03 F2400.0 E56.213
G1 X-10.8 Y3.36 Z1.03 F2400.0 E56.22
G1 X-10.8 Y-3.38 Z1.03 F2400.0 E56.342
G1 F1200.0
G1 E55.342
G1 F2400.0
M103
G1 X-7.6 Y1.75 Z1.03 F3300.0
G1 F1200.0
G1 E56.342
G1 F3300.0
M101
G1 X-7.6 Y-1.77 Z1.03 F2400.0 E56.406
G1 X-8.0 Y-1.77 Z1.03 F2400.0 E56.413
G1 X-8.0 Y1.75 Z1.03 F2400.0 E56.477
G1 X-8.4 Y1.75 Z1.03 F2400.0 E56.484
G1 X-8.4 Y-1.77 Z1.03 F2400.0 E56.548
G1 X-8.8 Y-1.77 Z1.03 F2400.0 E56.555
G1 X-8.8 Y1.75 Z1.03 F2400.0 E56.619
M73 P56 (display progress)
G1 X-9.2 Y1.75 Z1.03 F2400.0 E56.626
G1 X-9.2 Y-1.77 Z1.03 F2400.0 E56.69
G1 X-9.6 Y-1.77 Z1.03 F2400.0 E56.697
G1 X-9.6 Y1.75 Z1.03 F2400.0 E56.761
G1 F1200.0
G1 E55.761
G1 F2400.0
M103
G1 X-7.5 Y2.03 Z1.03 F3300.0
G1 X-7.2 Y3.49 Z1.03 F3300.0
G1 F1200.0
G1 E56.761
G1 F3300.0
M101
G1 X-7.2 Y-4.0 Z1.03 F2400.0 E56.896
G1 X-6.8 Y-4.24 Z1.03 F2400.0 E56.905
G1 X-6.8 Y4.25 Z1.03 F2400.0 E57.058
G1 X-6.4 Y4.25 Z1.03 F2400.0 E57.065
G1 X-6.4 Y-4.24 Z1.03 F2400.0 E57.219
G1 X-6.0 Y-4.24 Z1.03 F2400.0 E57.226
G1 X-6.0 Y4.25 Z1.03 F2400.0 E57.38
G1 X-5.6 Y4.25 Z1.03 F2400.0 E57.387
G1 X-5.6 Y-4.24 Z1.03 F2400.0 E57.54
G1 X-5.2 Y-4.24 Z1.03 F2400.0 E57.548
G1 X-5.2 Y4.25 Z1.03 F2400.0 E57.701
G1 X-4.8 Y4.25 Z1.03 F2400.0 E57.708
M73 P57 (display progress)
G1 X-4.8 Y-4.24 Z1.03 F2400.0 E57.862
G1 X-4.4 Y-4.24 Z1.03 F2400.0 E57.869
G1 X-4.4 Y4.25 Z1.03 F2400.0 E58.022
G1 X-4.0 Y4.25 Z1.03 F2400.0 E58.03
G1 X-4.0 Y-4.24 Z1.03 F2400.0 E58.183
G1 X-3.6 Y-4.24 Z1.03 F2400.0 E58.19
G1 X-3.6 Y4.24 Z1.03 F2400.0 E58.344
G1 X-3.2 Y4.24 Z1.03 F2400.0 E58.351
G1 X-3.2 Y-4.24 Z1.03 F2400.0 E58.504
G1 X-2.8 Y-4.24 Z1.03 F2400.0 E58.512
G1 X-2.8 Y4.24 Z1.03 F2400.0 E58.665
G1 X-2.4 Y4.24 Z1.03 F2400.0 E58.672
G1 X-2.4 Y-4.24 Z1.03 F2400.0 E58.825
G1 X-2.0 Y-4.24 Z1.03 F2400.0 E58.833
G1 X-2.0 Y4.24 Z1.03 F2400.0 E58.986
G1 X-1.6 Y4.24 Z1.03 F2400.0 E58.993
G1 X-1.6 Y-4.24 Z1.03 F2400.0 E59.147
G1 X-1.2 Y-4.24 Z1.03 F2400.0 E59.154
G1 X-1.2 Y4.24 Z1.03 F2400.0 E59.307
G1 X-0.8 Y4.24 Z1.03 F2400.0 E59.314
G1 X-0.8 Y-4.24 Z1.03 F2400.0 E59.468
G1 X-0.4 Y-4.24 Z1.03 F2400.0 E59.475
G1 X-0.4 Y4.24 Z1.03 F2400.0 E59.628
G1 X0.0 Y4.23 Z1.03 F2400.0 E59.635
G1 X-0.0 Y-4.24 Z1.03 F2400.0 E59.789
G1 X0.4 Y-4.24 Z1.03 F2400.0 E59.796
M73 P58 (display progress)
G1 X0.4 Y4.23 Z1.03 F2400.0 E59.949
G1 X0.8 Y4.23 Z1.03 F2400.0 E59.956
G1 X0.8 Y-4.24 Z1.03 F2400.0 E60.109
G1 X1.2 Y-4.24 Z1.03 F2400.0 E60.117
G1 X1.2 Y4.23 Z1.03 F2400.0 E60.27
G1 X1.6 Y4.23 Z1.03 F2400.0 E60.277
G1 X1.6 Y-4.24 Z1.03 F2400.0 E60.43
G1 X2.0 Y-4.24 Z1.03 F2400.0 E60.437
G1 X2.0 Y4.23 Z1.03 F2400.0 E60.591
G1 X2.4 Y4.23 Z1.03 F2400.0 E60.598
G1 X2.4 Y-4.24 Z1.03 F2400.0 E60.751
G1 X2.8 Y-4.24 Z1.03 F2400.0 E60.758
G1 X2.8 Y4.23 Z1.03 F2400.0 E60.911
G1 X3.2 Y4.22 Z1.03 F2400.0 E60.918
G1 X3.2 Y-4.24 Z1.03 F2400.0 E61.072
G1 X3.6 Y-4.24 Z1.03 F2400.0 E61.079
G1 X3.6 Y4.22 Z1.03 F2400.0 E61.232
G1 X4.0 Y4.22 Z1.03 F2400.0 E61.239
G1 X4.0 Y-4.24 Z1.03 F2400.0 E61.392
G1 X4.4 Y-4.24 Z1.03 F2400.0 E61.399
G1 X4.4 Y4.22 Z1.03 F2400.0 E61.552
G1 X4.8 Y4.22 Z1.03 F2400.0 E61.56
G1 X4.8 Y-4.24 Z1.03 F2400.0 E61.713
G1 X5.2 Y-4.24 Z1.03 F2400.0 E61.72
G1 X5.2 Y4.22 Z1.03 F2400.0 E61.873
G1 X5.6 Y4.22 Z1.03 F2400.0 E61.88
M73 P59 (display progress)
G1 X5.6 Y-4.24 Z1.03 F2400.0 E62.033
G1 X6.0 Y-4.24 Z1.03 F2400.0 E62.04
G1 X6.0 Y4.22 Z1.03 F2400.0 E62.193
G1 X6.4 Y4.21 Z1.03 F2400.0 E62.2
G1 X6.4 Y-4.24 Z1.03 F2400.0 E62.353
G1 X6.8 Y-4.24 Z1.03 F2400.0 E62.361
G1 X6.8 Y4.21 Z1.03 F2400.0 E62.513
G1 X7.2 Y4.21 Z1.03 F2400.0 E62.521
G1 X7.2 Y-4.24 Z1.03 F2400.0 E62.674
G1 X7.6 Y-4.24 Z1.03 F2400.0 E62.681
G1 X7.6 Y4.21 Z1.03 F2400.0 E62.834
G1 X8.0 Y4.21 Z1.03 F2400.0 E62.841
G1 X8.0 Y-4.24 Z1.03 F2400.0 E62.994
G1 X8.4 Y-4.24 Z1.03 F2400.0 E63.001
G1 X8.4 Y4.21 Z1.03 F2400.0 E63.154
G1 X8.8 Y4.21 Z1.03 F2400.0 E63.161
G1 X8.8 Y-4.24 Z1.03 F2400.0 E63.314
G1 X9.2 Y-4.24 Z1.03 F2400.0 E63.321
G1 X9.2 Y4.21 Z1.03 F2400.0 E63.474
G1 X9.6 Y4.21 Z1.03 F2400.0 E63.481
G1 X9.6 Y-4.24 Z1.03 F2400.0 E63.634
G1 X10.0 Y-4.24 Z1.03 F2400.0 E63.641
G1 X10.0 Y4.19 Z1.03 F2400.0 E63.794
G1 F1200.0
G1 E62.794
G1 F2400.0
M73 P60 (display progress)
M103
G1 X10.4 Y2.04 Z1.03 F3300.0
G1 F1200.0
G1 E63.794
G1 F3300.0
M101
G1 X10.4 Y-4.24 Z1.03 F2400.0 E63.907
G1 X10.8 Y-4.18 Z1.03 F2400.0 E63.914
G1 X10.8 Y-2.56 Z1.03 F2400.0 E63.944
G1 F1200.0
G1 E62.944
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.13 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.381 Y2.236 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.381 Y3.914 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-10.764 Y3.903 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.174 Y3.717 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.312 Y3.535 Z1.13 </boundaryPoint>)
M73 P61 (display progress)
(<boundaryPoint> X-11.4 Y3.365 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.452 Y3.131 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.465 Y-3.131 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.374 Y-3.48 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.149 Y-3.75 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-10.806 Y-3.908 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.381 Y-3.924 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.381 Y-2.246 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.702 Y-2.246 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.714 Y-3.942 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.614 Y-4.305 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.397 Y-4.56 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.071 Y-4.714 Z1.13 </boundaryPoint>)
(<boundaryPoint> X10.766 Y-4.722 Z1.13 </boundaryPoint>)
(<boundaryPoint> X11.232 Y-4.498 Z1.13 </boundaryPoint>)
(<boundaryPoint> X11.346 Y-4.351 Z1.13 </boundaryPoint>)
(<boundaryPoint> X11.431 Y-4.155 Z1.13 </boundaryPoint>)
(<boundaryPoint> X10.695 Y4.172 Z1.13 </boundaryPoint>)
(<boundaryPoint> X10.597 Y4.328 Z1.13 </boundaryPoint>)
(<boundaryPoint> X10.459 Y4.415 Z1.13 </boundaryPoint>)
(<boundaryPoint> X10.159 Y4.688 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-6.929 Y4.734 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.274 Y4.635 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.625 Y4.271 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.697 Y3.972 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-7.702 Y2.236 Z1.13 </boundaryPoint>)
M73 P62 (display progress)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z1.13 F3300.0
G1 X-9.58 Y-2.05 Z1.13 F3300.0
G1 X-11.06 Y-3.55 Z1.13 F3300.0
G1 F1200.0
G1 E63.944
G1 F3300.0
M101
G1 X-11.02 Y-3.59 Z1.13 F1200.0 E63.945
G1 X-10.76 Y-3.71 Z1.13 F1200.0 E63.95
G1 X-9.58 Y-3.72 Z1.13 F1200.0 E63.971
G1 X-9.58 Y-2.05 Z1.13 F1200.0 E64.002
G1 X-7.5 Y-2.05 Z1.13 F1200.0 E64.039
G1 X-7.51 Y-3.92 Z1.13 F1200.0 E64.073
G1 X-7.43 Y-4.21 Z1.13 F1200.0 E64.078
G1 X-7.27 Y-4.4 Z1.13 F1200.0 E64.083
G1 X-7.03 Y-4.51 Z1.13 F1200.0 E64.088
G1 X10.72 Y-4.52 Z1.13 F1200.0 E64.409
G1 X11.1 Y-4.34 Z1.13 F1200.0 E64.417
G1 X11.17 Y-4.25 Z1.13 F1200.0 E64.419
G1 X11.23 Y-4.12 Z1.13 F1200.0 E64.421
G1 X10.5 Y4.11 Z1.13 F1200.0 E64.571
G1 X10.45 Y4.18 Z1.13 F1200.0 E64.572
G1 X10.34 Y4.25 Z1.13 F1200.0 E64.575
G1 X10.08 Y4.49 Z1.13 F1200.0 E64.581
M73 P63 (display progress)
G1 X-6.9 Y4.53 Z1.13 F1200.0 E64.888
G1 X-7.17 Y4.46 Z1.13 F1200.0 E64.893
G1 X-7.44 Y4.17 Z1.13 F1200.0 E64.9
G1 X-7.5 Y3.95 Z1.13 F1200.0 E64.904
G1 X-7.5 Y2.04 Z1.13 F1200.0 E64.939
G1 X-9.58 Y2.04 Z1.13 F1200.0 E64.977
G1 X-9.58 Y3.71 Z1.13 F1200.0 E65.007
G1 X-10.72 Y3.7 Z1.13 F1200.0 E65.028
G1 X-11.04 Y3.56 Z1.13 F1200.0 E65.034
G1 X-11.14 Y3.43 Z1.13 F1200.0 E65.037
G1 X-11.21 Y3.3 Z1.13 F1200.0 E65.04
G1 X-11.25 Y3.11 Z1.13 F1200.0 E65.043
G1 X-11.27 Y-3.11 Z1.13 F1200.0 E65.155
G1 X-11.19 Y-3.39 Z1.13 F1200.0 E65.161
G1 X-11.06 Y-3.55 Z1.13 F1200.0 E65.165
G1 F1200.0
G1 E64.165
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.581 Y2.036 Z0.55 </infillPoint>)
(<infillPoint> X-9.581 Y3.712 Z0.55 </infillPoint>)
M73 P64 (display progress)
(<infillPoint> X-10.72 Y3.703 Z0.55 </infillPoint>)
(<infillPoint> X-11.045 Y3.556 Z0.55 </infillPoint>)
(<infillPoint> X-11.142 Y3.428 Z0.55 </infillPoint>)
(<infillPoint> X-11.21 Y3.296 Z0.55 </infillPoint>)
(<infillPoint> X-11.252 Y3.109 Z0.55 </infillPoint>)
(<infillPoint> X-11.265 Y-3.106 Z0.55 </infillPoint>)
(<infillPoint> X-11.192 Y-3.386 Z0.55 </infillPoint>)
(<infillPoint> X-11.024 Y-3.587 Z0.55 </infillPoint>)
(<infillPoint> X-10.761 Y-3.708 Z0.55 </infillPoint>)
(<infillPoint> X-9.581 Y-3.722 Z0.55 </infillPoint>)
(<infillPoint> X-9.581 Y-2.046 Z0.55 </infillPoint>)
(<infillPoint> X-7.501 Y-2.046 Z0.55 </infillPoint>)
(<infillPoint> X-7.514 Y-3.916 Z0.55 </infillPoint>)
(<infillPoint> X-7.433 Y-4.209 Z0.55 </infillPoint>)
(<infillPoint> X-7.273 Y-4.398 Z0.55 </infillPoint>)
(<infillPoint> X-7.026 Y-4.514 Z0.55 </infillPoint>)
(<infillPoint> X10.72 Y-4.522 Z0.55 </infillPoint>)
(<infillPoint> X11.103 Y-4.338 Z0.55 </infillPoint>)
(<infillPoint> X11.173 Y-4.248 Z0.55 </infillPoint>)
(<infillPoint> X11.227 Y-4.122 Z0.55 </infillPoint>)
(<infillPoint> X10.5 Y4.106 Z0.55 </infillPoint>)
(<infillPoint> X10.452 Y4.183 Z0.55 </infillPoint>)
(<infillPoint> X10.337 Y4.255 Z0.55 </infillPoint>)
(<infillPoint> X10.081 Y4.488 Z0.55 </infillPoint>)
(<infillPoint> X-6.901 Y4.534 Z0.55 </infillPoint>)
(<infillPoint> X-7.167 Y4.458 Z0.55 </infillPoint>)
M73 P65 (display progress)
(<infillPoint> X-7.443 Y4.171 Z0.55 </infillPoint>)
(<infillPoint> X-7.497 Y3.948 Z0.55 </infillPoint>)
(<infillPoint> X-7.503 Y2.036 Z0.55 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.58 Y-2.05 Z1.13 F3300.0
G1 X10.58 Y-0.0 Z1.13 F3300.0
G1 F1200.0
G1 E65.165
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z1.13 F2400.0 E65.555
G1 X-10.98 Y-0.4 Z1.13 F2400.0 E65.562
G1 X10.62 Y-0.4 Z1.13 F2400.0 E65.952
G1 X10.65 Y-0.8 Z1.13 F2400.0 E65.96
G1 X-10.98 Y-0.8 Z1.13 F2400.0 E66.351
G1 X-10.98 Y-1.2 Z1.13 F2400.0 E66.358
G1 X10.69 Y-1.2 Z1.13 F2400.0 E66.75
G1 X10.72 Y-1.6 Z1.13 F2400.0 E66.757
G1 X-10.98 Y-1.6 Z1.13 F2400.0 E67.15
G1 X-10.98 Y-2.0 Z1.13 F2400.0 E67.157
G1 X-9.86 Y-2.0 Z1.13 F2400.0 E67.178
G1 X-9.86 Y-2.4 Z1.13 F2400.0 E67.185
G1 X-10.98 Y-2.4 Z1.13 F2400.0 E67.205
G1 X-10.98 Y-2.8 Z1.13 F2400.0 E67.212
G1 X-9.86 Y-2.8 Z1.13 F2400.0 E67.233
M73 P66 (display progress)
G1 X-9.86 Y-3.2 Z1.13 F2400.0 E67.24
G1 X-10.95 Y-3.2 Z1.13 F2400.0 E67.26
G1 F1200.0
G1 E66.26
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z1.13 F3300.0
G1 F1200.0
G1 E67.26
G1 F3300.0
M101
G1 X10.55 Y0.4 Z1.13 F2400.0 E67.649
G1 X10.51 Y0.8 Z1.13 F2400.0 E67.656
G1 X-10.98 Y0.8 Z1.13 F2400.0 E68.045
G1 X-10.98 Y1.2 Z1.13 F2400.0 E68.052
G1 X10.48 Y1.2 Z1.13 F2400.0 E68.44
G1 X10.44 Y1.6 Z1.13 F2400.0 E68.448
G1 X-10.97 Y1.6 Z1.13 F2400.0 E68.835
G1 X-10.97 Y2.0 Z1.13 F2400.0 E68.842
G1 X-9.86 Y2.0 Z1.13 F2400.0 E68.862
G1 X-9.86 Y2.4 Z1.13 F2400.0 E68.869
G1 X-10.97 Y2.4 Z1.13 F2400.0 E68.89
G1 X-10.97 Y2.8 Z1.13 F2400.0 E68.897
G1 X-9.86 Y2.8 Z1.13 F2400.0 E68.917
G1 X-9.86 Y3.2 Z1.13 F2400.0 E68.924
G1 X-10.95 Y3.2 Z1.13 F2400.0 E68.944
M73 P67 (display progress)
G1 F1200.0
G1 E67.944
G1 F2400.0
M103
G1 X-9.58 Y2.04 Z1.13 F3300.0
G1 X-7.5 Y2.04 Z1.13 F3300.0
G1 X-7.22 Y3.2 Z1.13 F3300.0
G1 F1200.0
G1 E68.944
G1 F3300.0
M101
G1 X10.3 Y3.2 Z1.13 F2400.0 E69.261
G1 X10.26 Y3.6 Z1.13 F2400.0 E69.268
G1 X-7.22 Y3.6 Z1.13 F2400.0 E69.584
G1 X-7.2 Y4.0 Z1.13 F2400.0 E69.591
G1 X10.2 Y4.0 Z1.13 F2400.0 E69.906
G1 F1200.0
G1 E69.699
G1 F2400.0
M103
G1 X10.33 Y2.8 Z1.13 F3300.0
G1 F1200.0
G1 E69.906
G1 F3300.0
M101
G1 X-7.22 Y2.8 Z1.13 F2400.0 E70.224
M73 P68 (display progress)
G1 X-7.22 Y2.4 Z1.13 F2400.0 E70.231
G1 X10.37 Y2.4 Z1.13 F2400.0 E70.549
G1 X10.4 Y2.0 Z1.13 F2400.0 E70.556
G1 X-7.22 Y2.0 Z1.13 F2400.0 E70.875
G1 F1200.0
G1 E69.875
G1 F2400.0
M103
G1 X-7.22 Y-2.0 Z1.13 F3300.0
G1 F1200.0
G1 E70.875
G1 F3300.0
M101
G1 X10.76 Y-2.0 Z1.13 F2400.0 E71.2
G1 X10.79 Y-2.4 Z1.13 F2400.0 E71.208
G1 X-7.22 Y-2.4 Z1.13 F2400.0 E71.534
G1 X-7.23 Y-2.8 Z1.13 F2400.0 E71.541
G1 X10.83 Y-2.8 Z1.13 F2400.0 E71.867
G1 X10.87 Y-3.2 Z1.13 F2400.0 E71.875
G1 X-7.23 Y-3.2 Z1.13 F2400.0 E72.202
G1 X-7.23 Y-3.6 Z1.13 F2400.0 E72.209
G1 X10.9 Y-3.6 Z1.13 F2400.0 E72.537
G1 X10.94 Y-4.0 Z1.13 F2400.0 E72.545
G1 X-7.2 Y-4.0 Z1.13 F2400.0 E72.873
G1 F1200.0
G1 E71.873
M73 P69 (display progress)
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.23 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.382 Y2.236 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.382 Y3.914 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-10.751 Y3.906 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.174 Y3.717 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.392 Y3.398 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.453 Y3.121 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.466 Y-3.127 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.376 Y-3.476 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.153 Y-3.747 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-10.807 Y-3.907 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.382 Y-3.923 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.382 Y-2.245 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.703 Y-2.245 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.715 Y-3.938 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.614 Y-4.305 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.4 Y-4.558 Z1.23 </boundaryPoint>)
M73 P70 (display progress)
(<boundaryPoint> X-7.075 Y-4.712 Z1.23 </boundaryPoint>)
(<boundaryPoint> X10.743 Y-4.724 Z1.23 </boundaryPoint>)
(<boundaryPoint> X11.243 Y-4.487 Z1.23 </boundaryPoint>)
(<boundaryPoint> X11.331 Y-4.372 Z1.23 </boundaryPoint>)
(<boundaryPoint> X11.44 Y-4.124 Z1.23 </boundaryPoint>)
(<boundaryPoint> X10.694 Y4.173 Z1.23 </boundaryPoint>)
(<boundaryPoint> X10.621 Y4.289 Z1.23 </boundaryPoint>)
(<boundaryPoint> X10.147 Y4.692 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-6.929 Y4.735 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.275 Y4.636 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.638 Y4.235 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.7 Y3.95 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-7.703 Y2.236 Z1.23 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z1.23 F3300.0
G1 X-9.58 Y-2.05 Z1.23 F3300.0
G1 X-11.22 Y-3.29 Z1.23 F3300.0
G1 F1200.0
G1 E72.873
G1 F3300.0
M101
G1 X-11.19 Y-3.38 Z1.23 F1200.0 E72.874
G1 X-11.03 Y-3.58 Z1.23 F1200.0 E72.879
G1 X-10.76 Y-3.71 Z1.23 F1200.0 E72.884
G1 X-9.58 Y-3.72 Z1.23 F1200.0 E72.906
M73 P71 (display progress)
G1 X-9.58 Y-2.04 Z1.23 F1200.0 E72.936
G1 X-7.5 Y-2.04 Z1.23 F1200.0 E72.974
G1 X-7.51 Y-3.91 Z1.23 F1200.0 E73.007
G1 X-7.43 Y-4.21 Z1.23 F1200.0 E73.013
G1 X-7.28 Y-4.4 Z1.23 F1200.0 E73.017
G1 X-7.03 Y-4.51 Z1.23 F1200.0 E73.022
G1 X10.7 Y-4.52 Z1.23 F1200.0 E73.343
G1 X11.11 Y-4.33 Z1.23 F1200.0 E73.351
G1 X11.16 Y-4.27 Z1.23 F1200.0 E73.353
G1 X11.24 Y-4.09 Z1.23 F1200.0 E73.356
G1 X10.5 Y4.11 Z1.23 F1200.0 E73.505
G1 X10.47 Y4.16 Z1.23 F1200.0 E73.506
G1 X10.07 Y4.49 Z1.23 F1200.0 E73.515
G1 X-6.9 Y4.54 Z1.23 F1200.0 E73.822
G1 X-7.17 Y4.46 Z1.23 F1200.0 E73.827
G1 X-7.45 Y4.14 Z1.23 F1200.0 E73.835
G1 X-7.5 Y3.93 Z1.23 F1200.0 E73.839
G1 X-7.5 Y2.04 Z1.23 F1200.0 E73.873
G1 X-9.58 Y2.04 Z1.23 F1200.0 E73.911
G1 X-9.58 Y3.71 Z1.23 F1200.0 E73.941
G1 X-10.71 Y3.71 Z1.23 F1200.0 E73.962
G1 X-11.04 Y3.56 Z1.23 F1200.0 E73.968
G1 X-11.21 Y3.32 Z1.23 F1200.0 E73.974
G1 X-11.25 Y3.1 Z1.23 F1200.0 E73.978
G1 X-11.27 Y-3.1 Z1.23 F1200.0 E74.09
G1 X-11.22 Y-3.29 Z1.23 F1200.0 E74.093
M73 P72 (display progress)
G1 F1200.0
G1 E73.093
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.582 Y2.036 Z0.65 </infillPoint>)
(<infillPoint> X-9.582 Y3.713 Z0.65 </infillPoint>)
(<infillPoint> X-10.708 Y3.706 Z0.65 </infillPoint>)
(<infillPoint> X-11.041 Y3.557 Z0.65 </infillPoint>)
(<infillPoint> X-11.205 Y3.317 Z0.65 </infillPoint>)
(<infillPoint> X-11.253 Y3.099 Z0.65 </infillPoint>)
(<infillPoint> X-11.266 Y-3.102 Z0.65 </infillPoint>)
(<infillPoint> X-11.193 Y-3.383 Z0.65 </infillPoint>)
(<infillPoint> X-11.028 Y-3.585 Z0.65 </infillPoint>)
(<infillPoint> X-10.762 Y-3.707 Z0.65 </infillPoint>)
(<infillPoint> X-9.582 Y-3.721 Z0.65 </infillPoint>)
(<infillPoint> X-9.582 Y-2.045 Z0.65 </infillPoint>)
(<infillPoint> X-7.502 Y-2.045 Z0.65 </infillPoint>)
(<infillPoint> X-7.515 Y-3.912 Z0.65 </infillPoint>)
(<infillPoint> X-7.433 Y-4.209 Z0.65 </infillPoint>)
(<infillPoint> X-7.275 Y-4.396 Z0.65 </infillPoint>)
(<infillPoint> X-7.03 Y-4.512 Z0.65 </infillPoint>)
M73 P73 (display progress)
(<infillPoint> X10.698 Y-4.524 Z0.65 </infillPoint>)
(<infillPoint> X11.114 Y-4.327 Z0.65 </infillPoint>)
(<infillPoint> X11.158 Y-4.27 Z0.65 </infillPoint>)
(<infillPoint> X11.236 Y-4.091 Z0.65 </infillPoint>)
(<infillPoint> X10.499 Y4.107 Z0.65 </infillPoint>)
(<infillPoint> X10.468 Y4.157 Z0.65 </infillPoint>)
(<infillPoint> X10.073 Y4.492 Z0.65 </infillPoint>)
(<infillPoint> X-6.901 Y4.535 Z0.65 </infillPoint>)
(<infillPoint> X-7.165 Y4.459 Z0.65 </infillPoint>)
(<infillPoint> X-7.454 Y4.14 Z0.65 </infillPoint>)
(<infillPoint> X-7.5 Y3.928 Z0.65 </infillPoint>)
(<infillPoint> X-7.503 Y2.036 Z0.65 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-10.0 Y3.34 Z1.23 F3300.0
G1 F1200.0
G1 E74.093
G1 F3300.0
M101
G1 X-10.0 Y-3.35 Z1.23 F2400.0 E74.214
G1 X-10.4 Y-3.43 Z1.23 F2400.0 E74.222
G1 X-10.4 Y3.43 Z1.23 F2400.0 E74.346
G1 X-10.8 Y3.36 Z1.23 F2400.0 E74.353
G1 X-10.8 Y-3.38 Z1.23 F2400.0 E74.475
G1 F1200.0
G1 E73.475
M73 P74 (display progress)
G1 F2400.0
M103
G1 X-7.6 Y1.76 Z1.23 F3300.0
G1 F1200.0
G1 E74.475
G1 F3300.0
M101
G1 X-7.6 Y-1.76 Z1.23 F2400.0 E74.539
G1 X-8.0 Y-1.76 Z1.23 F2400.0 E74.546
G1 X-8.0 Y1.76 Z1.23 F2400.0 E74.61
G1 X-8.4 Y1.76 Z1.23 F2400.0 E74.617
G1 X-8.4 Y-1.76 Z1.23 F2400.0 E74.681
G1 X-8.8 Y-1.76 Z1.23 F2400.0 E74.688
G1 X-8.8 Y1.76 Z1.23 F2400.0 E74.751
G1 X-9.2 Y1.76 Z1.23 F2400.0 E74.759
G1 X-9.2 Y-1.76 Z1.23 F2400.0 E74.822
G1 X-9.6 Y-1.76 Z1.23 F2400.0 E74.83
G1 X-9.6 Y1.76 Z1.23 F2400.0 E74.893
G1 F1200.0
G1 E73.893
G1 F2400.0
M103
G1 X-7.5 Y2.04 Z1.23 F3300.0
G1 X-7.2 Y3.99 Z1.23 F3300.0
G1 F1200.0
G1 E74.893
M73 P75 (display progress)
G1 F3300.0
M101
G1 X-7.2 Y-4.0 Z1.23 F2400.0 E75.038
G1 X-6.8 Y-4.23 Z1.23 F2400.0 E75.046
G1 X-6.8 Y4.25 Z1.23 F2400.0 E75.2
G1 X-6.4 Y4.25 Z1.23 F2400.0 E75.207
G1 X-6.4 Y-4.23 Z1.23 F2400.0 E75.36
G1 X-6.0 Y-4.23 Z1.23 F2400.0 E75.368
G1 X-6.0 Y4.25 Z1.23 F2400.0 E75.521
G1 X-5.6 Y4.25 Z1.23 F2400.0 E75.528
G1 X-5.6 Y-4.23 Z1.23 F2400.0 E75.682
G1 X-5.2 Y-4.23 Z1.23 F2400.0 E75.689
G1 X-5.2 Y4.25 Z1.23 F2400.0 E75.843
G1 X-4.8 Y4.25 Z1.23 F2400.0 E75.85
G1 X-4.8 Y-4.23 Z1.23 F2400.0 E76.003
G1 X-4.4 Y-4.23 Z1.23 F2400.0 E76.011
G1 X-4.4 Y4.25 Z1.23 F2400.0 E76.164
G1 X-4.0 Y4.25 Z1.23 F2400.0 E76.171
G1 X-4.0 Y-4.23 Z1.23 F2400.0 E76.325
G1 X-3.6 Y-4.23 Z1.23 F2400.0 E76.332
G1 X-3.6 Y4.25 Z1.23 F2400.0 E76.485
G1 X-3.2 Y4.25 Z1.23 F2400.0 E76.493
G1 X-3.2 Y-4.24 Z1.23 F2400.0 E76.646
G1 X-2.8 Y-4.24 Z1.23 F2400.0 E76.653
G1 X-2.8 Y4.25 Z1.23 F2400.0 E76.807
G1 X-2.4 Y4.24 Z1.23 F2400.0 E76.814
M73 P76 (display progress)
G1 X-2.4 Y-4.24 Z1.23 F2400.0 E76.967
G1 X-2.0 Y-4.24 Z1.23 F2400.0 E76.974
G1 X-2.0 Y4.24 Z1.23 F2400.0 E77.128
G1 X-1.6 Y4.24 Z1.23 F2400.0 E77.135
G1 X-1.6 Y-4.24 Z1.23 F2400.0 E77.288
G1 X-1.2 Y-4.24 Z1.23 F2400.0 E77.296
G1 X-1.2 Y4.24 Z1.23 F2400.0 E77.449
G1 X-0.8 Y4.24 Z1.23 F2400.0 E77.456
G1 X-0.8 Y-4.24 Z1.23 F2400.0 E77.61
G1 X-0.4 Y-4.24 Z1.23 F2400.0 E77.617
G1 X-0.4 Y4.24 Z1.23 F2400.0 E77.77
G1 X0.0 Y4.24 Z1.23 F2400.0 E77.777
G1 X-0.0 Y-4.24 Z1.23 F2400.0 E77.931
G1 X0.4 Y-4.24 Z1.23 F2400.0 E77.938
G1 X0.4 Y4.24 Z1.23 F2400.0 E78.091
G1 X0.8 Y4.24 Z1.23 F2400.0 E78.098
G1 X0.8 Y-4.24 Z1.23 F2400.0 E78.252
G1 X1.2 Y-4.24 Z1.23 F2400.0 E78.259
G1 X1.2 Y4.24 Z1.23 F2400.0 E78.412
G1 X1.6 Y4.23 Z1.23 F2400.0 E78.419
G1 X1.6 Y-4.24 Z1.23 F2400.0 E78.573
G1 X2.0 Y-4.24 Z1.23 F2400.0 E78.58
G1 X2.0 Y4.23 Z1.23 F2400.0 E78.733
G1 X2.4 Y4.23 Z1.23 F2400.0 E78.74
G1 X2.4 Y-4.24 Z1.23 F2400.0 E78.893
G1 X2.8 Y-4.24 Z1.23 F2400.0 E78.901
M73 P77 (display progress)
G1 X2.8 Y4.23 Z1.23 F2400.0 E79.054
G1 X3.2 Y4.23 Z1.23 F2400.0 E79.061
G1 X3.2 Y-4.24 Z1.23 F2400.0 E79.214
G1 X3.6 Y-4.24 Z1.23 F2400.0 E79.222
G1 X3.6 Y4.23 Z1.23 F2400.0 E79.375
G1 X4.0 Y4.23 Z1.23 F2400.0 E79.382
G1 X4.0 Y-4.24 Z1.23 F2400.0 E79.535
G1 X4.4 Y-4.24 Z1.23 F2400.0 E79.542
G1 X4.4 Y4.23 Z1.23 F2400.0 E79.695
G1 X4.8 Y4.22 Z1.23 F2400.0 E79.703
G1 X4.8 Y-4.24 Z1.23 F2400.0 E79.856
G1 X5.2 Y-4.24 Z1.23 F2400.0 E79.863
G1 X5.2 Y4.22 Z1.23 F2400.0 E80.016
G1 X5.6 Y4.22 Z1.23 F2400.0 E80.023
G1 X5.6 Y-4.24 Z1.23 F2400.0 E80.177
G1 X6.0 Y-4.24 Z1.23 F2400.0 E80.184
G1 X6.0 Y4.22 Z1.23 F2400.0 E80.337
G1 X6.4 Y4.22 Z1.23 F2400.0 E80.344
G1 X6.4 Y-4.24 Z1.23 F2400.0 E80.497
G1 X6.8 Y-4.24 Z1.23 F2400.0 E80.504
G1 X6.8 Y4.22 Z1.23 F2400.0 E80.657
G1 X7.2 Y4.22 Z1.23 F2400.0 E80.665
G1 X7.2 Y-4.24 Z1.23 F2400.0 E80.818
G1 X7.6 Y-4.24 Z1.23 F2400.0 E80.825
G1 X7.6 Y4.22 Z1.23 F2400.0 E80.978
G1 X8.0 Y4.22 Z1.23 F2400.0 E80.985
M73 P78 (display progress)
G1 X8.0 Y-4.24 Z1.23 F2400.0 E81.138
G1 X8.4 Y-4.24 Z1.23 F2400.0 E81.145
G1 X8.4 Y4.22 Z1.23 F2400.0 E81.298
G1 X8.8 Y4.21 Z1.23 F2400.0 E81.306
G1 X8.8 Y-4.24 Z1.23 F2400.0 E81.459
G1 X9.2 Y-4.24 Z1.23 F2400.0 E81.466
G1 X9.2 Y4.21 Z1.23 F2400.0 E81.619
G1 X9.6 Y4.21 Z1.23 F2400.0 E81.626
G1 X9.6 Y-4.24 Z1.23 F2400.0 E81.779
G1 X10.0 Y-4.24 Z1.23 F2400.0 E81.786
G1 X10.0 Y4.19 Z1.23 F2400.0 E81.939
G1 F1200.0
G1 E80.939
G1 F2400.0
M103
G1 X10.4 Y2.08 Z1.23 F3300.0
G1 F1200.0
G1 E81.939
G1 F3300.0
M101
G1 X10.4 Y-4.24 Z1.23 F2400.0 E82.053
G1 X10.8 Y-4.17 Z1.23 F2400.0 E82.061
G1 X10.8 Y-2.37 Z1.23 F2400.0 E82.093
G1 F1200.0
G1 E81.093
G1 F2400.0
M73 P79 (display progress)
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.33 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.383 Y2.237 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.383 Y3.915 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-10.737 Y3.909 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.175 Y3.718 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.384 Y3.431 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.454 Y3.111 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.467 Y-3.123 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.378 Y-3.472 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.156 Y-3.744 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-10.807 Y-3.907 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.383 Y-3.923 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.383 Y-2.245 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.703 Y-2.245 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.716 Y-3.934 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.615 Y-4.304 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.404 Y-4.555 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.079 Y-4.711 Z1.33 </boundaryPoint>)
M73 P80 (display progress)
(<boundaryPoint> X10.719 Y-4.726 Z1.33 </boundaryPoint>)
(<boundaryPoint> X11.275 Y-4.465 Z1.33 </boundaryPoint>)
(<boundaryPoint> X11.448 Y-4.095 Z1.33 </boundaryPoint>)
(<boundaryPoint> X10.691 Y4.204 Z1.33 </boundaryPoint>)
(<boundaryPoint> X10.136 Y4.696 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-6.93 Y4.735 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.275 Y4.636 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.639 Y4.236 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.702 Y3.931 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-7.704 Y2.237 Z1.33 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z1.33 F3300.0
G1 X-9.58 Y-2.04 Z1.33 F3300.0
G1 X-10.9 Y-3.64 Z1.33 F3300.0
G1 F1200.0
G1 E82.093
G1 F3300.0
M101
G1 X-10.76 Y-3.71 Z1.33 F1200.0 E82.096
G1 X-9.58 Y-3.72 Z1.33 F1200.0 E82.117
G1 X-9.58 Y-2.04 Z1.33 F1200.0 E82.148
G1 X-7.5 Y-2.04 Z1.33 F1200.0 E82.185
G1 X-7.52 Y-3.91 Z1.33 F1200.0 E82.219
G1 X-7.43 Y-4.21 Z1.33 F1200.0 E82.225
G1 X-7.28 Y-4.39 Z1.33 F1200.0 E82.229
M73 P81 (display progress)
G1 X-7.03 Y-4.51 Z1.33 F1200.0 E82.234
G1 X10.67 Y-4.53 Z1.33 F1200.0 E82.554
G1 X11.13 Y-4.32 Z1.33 F1200.0 E82.563
G1 X11.24 Y-4.06 Z1.33 F1200.0 E82.568
G1 X10.5 Y4.11 Z1.33 F1200.0 E82.717
G1 X10.06 Y4.5 Z1.33 F1200.0 E82.727
G1 X-6.9 Y4.54 Z1.33 F1200.0 E83.034
G1 X-7.17 Y4.46 Z1.33 F1200.0 E83.039
G1 X-7.45 Y4.14 Z1.33 F1200.0 E83.047
G1 X-7.5 Y3.91 Z1.33 F1200.0 E83.051
G1 X-7.5 Y2.04 Z1.33 F1200.0 E83.085
G1 X-9.58 Y2.04 Z1.33 F1200.0 E83.123
G1 X-9.58 Y3.71 Z1.33 F1200.0 E83.153
G1 X-10.7 Y3.71 Z1.33 F1200.0 E83.173
G1 X-11.04 Y3.56 Z1.33 F1200.0 E83.18
G1 X-11.2 Y3.35 Z1.33 F1200.0 E83.185
G1 X-11.25 Y3.09 Z1.33 F1200.0 E83.189
G1 X-11.27 Y-3.1 Z1.33 F1200.0 E83.301
G1 X-11.2 Y-3.38 Z1.33 F1200.0 E83.307
G1 X-11.03 Y-3.58 Z1.33 F1200.0 E83.311
G1 X-10.9 Y-3.64 Z1.33 F1200.0 E83.314
G1 F1200.0
G1 E82.314
G1 F1200.0
M103
M73 P82 (display progress)
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.583 Y2.037 Z0.75 </infillPoint>)
(<infillPoint> X-9.583 Y3.714 Z0.75 </infillPoint>)
(<infillPoint> X-10.695 Y3.709 Z0.75 </infillPoint>)
(<infillPoint> X-11.045 Y3.556 Z0.75 </infillPoint>)
(<infillPoint> X-11.198 Y3.347 Z0.75 </infillPoint>)
(<infillPoint> X-11.254 Y3.089 Z0.75 </infillPoint>)
(<infillPoint> X-11.267 Y-3.098 Z0.75 </infillPoint>)
(<infillPoint> X-11.195 Y-3.38 Z0.75 </infillPoint>)
(<infillPoint> X-11.03 Y-3.582 Z0.75 </infillPoint>)
(<infillPoint> X-10.762 Y-3.707 Z0.75 </infillPoint>)
(<infillPoint> X-9.583 Y-3.721 Z0.75 </infillPoint>)
(<infillPoint> X-9.583 Y-2.045 Z0.75 </infillPoint>)
(<infillPoint> X-7.501 Y-2.045 Z0.75 </infillPoint>)
(<infillPoint> X-7.516 Y-3.908 Z0.75 </infillPoint>)
(<infillPoint> X-7.434 Y-4.209 Z0.75 </infillPoint>)
(<infillPoint> X-7.279 Y-4.393 Z0.75 </infillPoint>)
(<infillPoint> X-7.033 Y-4.511 Z0.75 </infillPoint>)
(<infillPoint> X10.674 Y-4.526 Z0.75 </infillPoint>)
(<infillPoint> X11.124 Y-4.315 Z0.75 </infillPoint>)
(<infillPoint> X11.244 Y-4.059 Z0.75 </infillPoint>)
(<infillPoint> X10.499 Y4.107 Z0.75 </infillPoint>)
(<infillPoint> X10.06 Y4.496 Z0.75 </infillPoint>)
M73 P83 (display progress)
(<infillPoint> X-6.902 Y4.535 Z0.75 </infillPoint>)
(<infillPoint> X-7.165 Y4.459 Z0.75 </infillPoint>)
(<infillPoint> X-7.454 Y4.142 Z0.75 </infillPoint>)
(<infillPoint> X-7.502 Y3.91 Z0.75 </infillPoint>)
(<infillPoint> X-7.504 Y2.037 Z0.75 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.58 Y-2.04 Z1.33 F3300.0
G1 X10.59 Y-0.0 Z1.33 F3300.0
G1 F1200.0
G1 E83.314
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z1.33 F2400.0 E83.704
G1 X-10.98 Y-0.4 Z1.33 F2400.0 E83.711
G1 X10.63 Y-0.4 Z1.33 F2400.0 E84.102
G1 X10.66 Y-0.8 Z1.33 F2400.0 E84.109
G1 X-10.98 Y-0.8 Z1.33 F2400.0 E84.501
G1 X-10.98 Y-1.2 Z1.33 F2400.0 E84.508
G1 X10.7 Y-1.2 Z1.33 F2400.0 E84.901
G1 X10.74 Y-1.6 Z1.33 F2400.0 E84.908
G1 X-10.98 Y-1.6 Z1.33 F2400.0 E85.301
G1 X-10.98 Y-2.0 Z1.33 F2400.0 E85.308
G1 X-9.86 Y-2.0 Z1.33 F2400.0 E85.328
G1 X-9.86 Y-2.4 Z1.33 F2400.0 E85.335
G1 X-10.98 Y-2.4 Z1.33 F2400.0 E85.356
M73 P84 (display progress)
G1 X-10.99 Y-2.8 Z1.33 F2400.0 E85.363
G1 X-9.86 Y-2.8 Z1.33 F2400.0 E85.383
G1 X-9.86 Y-3.2 Z1.33 F2400.0 E85.391
G1 X-10.95 Y-3.2 Z1.33 F2400.0 E85.41
G1 F1200.0
G1 E84.41
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z1.33 F3300.0
G1 F1200.0
G1 E85.41
G1 F3300.0
M101
G1 X10.56 Y0.4 Z1.33 F2400.0 E85.8
G1 X10.52 Y0.8 Z1.33 F2400.0 E85.807
G1 X-10.98 Y0.8 Z1.33 F2400.0 E86.196
G1 X-10.98 Y1.2 Z1.33 F2400.0 E86.203
G1 X10.48 Y1.2 Z1.33 F2400.0 E86.591
G1 X10.45 Y1.6 Z1.33 F2400.0 E86.599
G1 X-10.98 Y1.6 Z1.33 F2400.0 E86.986
G1 X-10.98 Y2.0 Z1.33 F2400.0 E86.993
G1 X-9.86 Y2.0 Z1.33 F2400.0 E87.014
G1 X-9.86 Y2.4 Z1.33 F2400.0 E87.021
G1 X-10.97 Y2.4 Z1.33 F2400.0 E87.041
G1 X-10.97 Y2.8 Z1.33 F2400.0 E87.048
G1 X-9.86 Y2.8 Z1.33 F2400.0 E87.068
M73 P85 (display progress)
G1 X-9.86 Y3.2 Z1.33 F2400.0 E87.075
G1 X-10.94 Y3.2 Z1.33 F2400.0 E87.095
G1 F1200.0
G1 E86.095
G1 F2400.0
M103
G1 X-9.58 Y2.04 Z1.33 F3300.0
G1 X-7.5 Y2.04 Z1.33 F3300.0
G1 X-7.22 Y3.2 Z1.33 F3300.0
G1 F1200.0
G1 E87.095
G1 F3300.0
M101
G1 X10.3 Y3.2 Z1.33 F2400.0 E87.412
G1 X10.26 Y3.6 Z1.33 F2400.0 E87.419
G1 X-7.22 Y3.6 Z1.33 F2400.0 E87.736
G1 X-7.2 Y4.0 Z1.33 F2400.0 E87.743
G1 X10.2 Y4.0 Z1.33 F2400.0 E88.058
G1 F1200.0
G1 E87.849
G1 F2400.0
M103
G1 X10.34 Y2.8 Z1.33 F3300.0
G1 F1200.0
G1 E88.058
G1 F3300.0
M73 P86 (display progress)
M101
G1 X-7.22 Y2.8 Z1.33 F2400.0 E88.375
G1 X-7.22 Y2.4 Z1.33 F2400.0 E88.382
G1 X10.37 Y2.4 Z1.33 F2400.0 E88.701
G1 X10.41 Y2.0 Z1.33 F2400.0 E88.708
G1 X-7.22 Y2.0 Z1.33 F2400.0 E89.027
G1 F1200.0
G1 E88.027
G1 F2400.0
M103
G1 X-7.22 Y-2.0 Z1.33 F3300.0
G1 F1200.0
G1 E89.027
G1 F3300.0
M101
G1 X10.78 Y-2.0 Z1.33 F2400.0 E89.352
G1 X10.81 Y-2.4 Z1.33 F2400.0 E89.36
G1 X-7.22 Y-2.4 Z1.33 F2400.0 E89.686
G1 X-7.23 Y-2.8 Z1.33 F2400.0 E89.693
G1 X10.85 Y-2.8 Z1.33 F2400.0 E90.02
G1 X10.88 Y-3.2 Z1.33 F2400.0 E90.027
G1 X-7.23 Y-3.2 Z1.33 F2400.0 E90.355
G1 X-7.23 Y-3.6 Z1.33 F2400.0 E90.362
G1 X10.92 Y-3.6 Z1.33 F2400.0 E90.691
G1 X10.96 Y-4.0 Z1.33 F2400.0 E90.698
G1 X-7.2 Y-4.0 Z1.33 F2400.0 E91.026
M73 P87 (display progress)
G1 F1200.0
G1 E90.026
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.43 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-9.383 Y-3.922 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-9.383 Y-2.604 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-9.673 Y-2.511 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-10.555 Y-3.625 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-10.419 Y-3.911 Z1.43 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-7.5 Y-2.05 Z1.43 F3300.0
G1 X-9.58 Y-2.04 Z1.43 F3300.0
G1 X-10.26 Y-3.57 Z1.43 F3300.0
G1 F1200.0
G1 E91.026
G1 F3300.0
M101
M73 P88 (display progress)
G1 X-10.32 Y-3.65 Z1.43 F1200.0 E91.028
G1 X-10.29 Y-3.71 Z1.43 F1200.0 E91.029
G1 X-9.58 Y-3.72 Z1.43 F1200.0 E91.042
G1 X-9.58 Y-2.75 Z1.43 F1200.0 E91.06
G1 X-9.6 Y-2.74 Z1.43 F1200.0 E91.06
G1 X-10.26 Y-3.57 Z1.43 F1200.0 E91.079
G1 F1200.0
G1 E90.079
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-9.583 Y-3.72 Z0.85 </infillPoint>)
(<infillPoint> X-9.583 Y-2.75 Z0.85 </infillPoint>)
(<infillPoint> X-9.602 Y-2.744 Z0.85 </infillPoint>)
(<infillPoint> X-10.321 Y-3.652 Z0.85 </infillPoint>)
(<infillPoint> X-10.292 Y-3.712 Z0.85 </infillPoint>)
(</infillBoundary>)
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-7.704 Y-2.244 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-7.717 Y-3.93 Z1.43 </boundaryPoint>)
M73 P89 (display progress)
(<boundaryPoint> X-7.615 Y-4.304 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-7.408 Y-4.552 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-7.083 Y-4.71 Z1.43 </boundaryPoint>)
(<boundaryPoint> X10.695 Y-4.729 Z1.43 </boundaryPoint>)
(<boundaryPoint> X11.264 Y-4.463 Z1.43 </boundaryPoint>)
(<boundaryPoint> X11.456 Y-4.061 Z1.43 </boundaryPoint>)
(<boundaryPoint> X10.693 Y4.173 Z1.43 </boundaryPoint>)
(<boundaryPoint> X10.123 Y4.7 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-3.932 Y4.73 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-9.231 Y-1.955 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-9.023 Y-2.244 Z1.43 </boundaryPoint>)
(<edge> outer )
G1 X-9.97 Y-3.87 Z1.43 F3300.0
G1 X-7.53 Y-0.18 Z1.43 F3300.0
G1 X-8.94 Y-1.91 Z1.43 F3300.0
G1 F1200.0
G1 E91.079
G1 F3300.0
M101
G1 X-8.98 Y-1.96 Z1.43 F1200.0 E91.08
G1 X-8.92 Y-2.04 Z1.43 F1200.0 E91.082
G1 X-7.5 Y-2.04 Z1.43 F1200.0 E91.108
G1 X-7.52 Y-3.9 Z1.43 F1200.0 E91.142
G1 X-7.43 Y-4.21 Z1.43 F1200.0 E91.147
G1 X-7.28 Y-4.39 Z1.43 F1200.0 E91.152
G1 X-7.04 Y-4.51 Z1.43 F1200.0 E91.157
M73 P90 (display progress)
G1 X10.65 Y-4.53 Z1.43 F1200.0 E91.477
G1 X11.11 Y-4.31 Z1.43 F1200.0 E91.486
G1 X11.25 Y-4.03 Z1.43 F1200.0 E91.492
G1 X10.5 Y4.08 Z1.43 F1200.0 E91.639
G1 X10.04 Y4.5 Z1.43 F1200.0 E91.65
G1 X-3.83 Y4.53 Z1.43 F1200.0 E91.901
G1 X-8.94 Y-1.91 Z1.43 F1200.0 E92.05
G1 F1200.0
G1 E92.05
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-7.502 Y-2.044 Z0.85 </infillPoint>)
(<infillPoint> X-7.517 Y-3.904 Z0.85 </infillPoint>)
(<infillPoint> X-7.434 Y-4.209 Z0.85 </infillPoint>)
(<infillPoint> X-7.282 Y-4.391 Z0.85 </infillPoint>)
(<infillPoint> X-7.037 Y-4.51 Z0.85 </infillPoint>)
(<infillPoint> X10.651 Y-4.529 Z0.85 </infillPoint>)
(<infillPoint> X11.114 Y-4.312 Z0.85 </infillPoint>)
(<infillPoint> X11.252 Y-4.025 Z0.85 </infillPoint>)
(<infillPoint> X10.501 Y4.078 Z0.85 </infillPoint>)
(<infillPoint> X10.045 Y4.5 Z0.85 </infillPoint>)
M73 P91 (display progress)
(<infillPoint> X-3.835 Y4.53 Z0.85 </infillPoint>)
(<infillPoint> X-8.98 Y-1.961 Z0.85 </infillPoint>)
(<infillPoint> X-8.921 Y-2.044 Z0.85 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-8.4 Y-1.69 Z1.43 F3300.0
G1 F1200.0
G1 E92.05
G1 F3300.0
M101
G1 X-8.0 Y-1.18 Z1.43 F2400.0 E92.062
G1 X-8.0 Y-1.76 Z1.43 F2400.0 E92.072
G1 X-7.6 Y-1.76 Z1.43 F2400.0 E92.079
G1 X-7.6 Y-0.67 Z1.43 F2400.0 E92.099
G1 X-7.2 Y-0.17 Z1.43 F2400.0 E92.111
G1 X-7.2 Y-4.0 Z1.43 F2400.0 E92.18
G1 X-6.8 Y-4.23 Z1.43 F2400.0 E92.189
G1 X-6.8 Y0.34 Z1.43 F2400.0 E92.271
G1 X-6.4 Y0.84 Z1.43 F2400.0 E92.283
G1 X-6.4 Y-4.23 Z1.43 F2400.0 E92.375
G1 X-6.0 Y-4.23 Z1.43 F2400.0 E92.382
G1 X-6.0 Y1.35 Z1.43 F2400.0 E92.483
G1 X-5.6 Y1.85 Z1.43 F2400.0 E92.494
G1 X-5.6 Y-4.23 Z1.43 F2400.0 E92.605
G1 X-5.2 Y-4.23 Z1.43 F2400.0 E92.612
G1 X-5.2 Y2.36 Z1.43 F2400.0 E92.731
M73 P92 (display progress)
G1 X-4.8 Y2.86 Z1.43 F2400.0 E92.743
G1 X-4.8 Y-4.23 Z1.43 F2400.0 E92.871
G1 X-4.4 Y-4.23 Z1.43 F2400.0 E92.878
G1 X-4.4 Y3.37 Z1.43 F2400.0 E93.016
G1 X-4.0 Y3.87 Z1.43 F2400.0 E93.027
G1 X-4.0 Y-4.23 Z1.43 F2400.0 E93.174
G1 X-3.6 Y-4.23 Z1.43 F2400.0 E93.181
G1 X-3.6 Y4.25 Z1.43 F2400.0 E93.335
G1 X-3.2 Y4.25 Z1.43 F2400.0 E93.342
G1 X-3.2 Y-4.23 Z1.43 F2400.0 E93.495
G1 X-2.8 Y-4.24 Z1.43 F2400.0 E93.502
G1 X-2.8 Y4.25 Z1.43 F2400.0 E93.656
G1 X-2.4 Y4.25 Z1.43 F2400.0 E93.663
G1 X-2.4 Y-4.24 Z1.43 F2400.0 E93.817
G1 X-2.0 Y-4.24 Z1.43 F2400.0 E93.824
G1 X-2.0 Y4.25 Z1.43 F2400.0 E93.977
G1 X-1.6 Y4.25 Z1.43 F2400.0 E93.984
G1 X-1.6 Y-4.24 Z1.43 F2400.0 E94.138
G1 X-1.2 Y-4.24 Z1.43 F2400.0 E94.145
G1 X-1.2 Y4.24 Z1.43 F2400.0 E94.298
G1 X-0.8 Y4.24 Z1.43 F2400.0 E94.306
G1 X-0.8 Y-4.24 Z1.43 F2400.0 E94.459
G1 X-0.4 Y-4.24 Z1.43 F2400.0 E94.466
G1 X-0.4 Y4.24 Z1.43 F2400.0 E94.62
G1 X0.0 Y4.24 Z1.43 F2400.0 E94.627
G1 X-0.0 Y-4.24 Z1.43 F2400.0 E94.78
M73 P93 (display progress)
G1 X0.4 Y-4.24 Z1.43 F2400.0 E94.788
G1 X0.4 Y4.24 Z1.43 F2400.0 E94.941
G1 X0.8 Y4.24 Z1.43 F2400.0 E94.948
G1 X0.8 Y-4.24 Z1.43 F2400.0 E95.102
G1 X1.2 Y-4.24 Z1.43 F2400.0 E95.109
G1 X1.2 Y4.24 Z1.43 F2400.0 E95.262
G1 X1.6 Y4.24 Z1.43 F2400.0 E95.269
G1 X1.6 Y-4.24 Z1.43 F2400.0 E95.423
G1 X2.0 Y-4.24 Z1.43 F2400.0 E95.43
G1 X2.0 Y4.24 Z1.43 F2400.0 E95.583
G1 X2.4 Y4.24 Z1.43 F2400.0 E95.591
G1 X2.4 Y-4.24 Z1.43 F2400.0 E95.744
G1 X2.8 Y-4.24 Z1.43 F2400.0 E95.751
G1 X2.8 Y4.24 Z1.43 F2400.0 E95.904
G1 X3.2 Y4.24 Z1.43 F2400.0 E95.912
G1 X3.2 Y-4.24 Z1.43 F2400.0 E96.065
G1 X3.6 Y-4.24 Z1.43 F2400.0 E96.072
G1 X3.6 Y4.23 Z1.43 F2400.0 E96.226
G1 X4.0 Y4.23 Z1.43 F2400.0 E96.233
G1 X4.0 Y-4.24 Z1.43 F2400.0 E96.386
G1 X4.4 Y-4.24 Z1.43 F2400.0 E96.393
G1 X4.4 Y4.23 Z1.43 F2400.0 E96.547
G1 X4.8 Y4.23 Z1.43 F2400.0 E96.554
G1 X4.8 Y-4.24 Z1.43 F2400.0 E96.707
G1 X5.2 Y-4.24 Z1.43 F2400.0 E96.714
G1 X5.2 Y4.23 Z1.43 F2400.0 E96.868
M73 P94 (display progress)
G1 X5.6 Y4.23 Z1.43 F2400.0 E96.875
G1 X5.6 Y-4.24 Z1.43 F2400.0 E97.028
G1 X6.0 Y-4.24 Z1.43 F2400.0 E97.035
G1 X6.0 Y4.23 Z1.43 F2400.0 E97.189
G1 X6.4 Y4.23 Z1.43 F2400.0 E97.196
G1 X6.4 Y-4.24 Z1.43 F2400.0 E97.349
G1 X6.8 Y-4.25 Z1.43 F2400.0 E97.356
G1 X6.8 Y4.23 Z1.43 F2400.0 E97.51
G1 X7.2 Y4.23 Z1.43 F2400.0 E97.517
G1 X7.2 Y-4.25 Z1.43 F2400.0 E97.67
G1 X7.6 Y-4.25 Z1.43 F2400.0 E97.677
G1 X7.6 Y4.22 Z1.43 F2400.0 E97.831
G1 X8.0 Y4.22 Z1.43 F2400.0 E97.838
G1 X8.0 Y-4.25 Z1.43 F2400.0 E97.991
G1 X8.4 Y-4.25 Z1.43 F2400.0 E97.998
G1 X8.4 Y4.22 Z1.43 F2400.0 E98.151
G1 X8.8 Y4.22 Z1.43 F2400.0 E98.159
G1 X8.8 Y-4.25 Z1.43 F2400.0 E98.312
G1 X9.2 Y-4.25 Z1.43 F2400.0 E98.319
G1 X9.2 Y4.22 Z1.43 F2400.0 E98.472
G1 X9.6 Y4.22 Z1.43 F2400.0 E98.48
G1 X9.6 Y-4.25 Z1.43 F2400.0 E98.633
G1 X10.0 Y-4.25 Z1.43 F2400.0 E98.64
G1 X10.0 Y4.16 Z1.43 F2400.0 E98.792
G1 F1200.0
G1 E97.792
M73 P95 (display progress)
G1 F2400.0
M103
G1 X10.4 Y2.13 Z1.43 F3300.0
G1 F1200.0
G1 E98.792
G1 F3300.0
M101
G1 X10.4 Y-4.25 Z1.43 F2400.0 E98.908
G1 X10.8 Y-4.15 Z1.43 F2400.0 E98.915
G1 X10.8 Y-2.18 Z1.43 F2400.0 E98.951
G1 F1200.0
G1 E97.951
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.53 )
;M108 R9.852
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X10.672 Y-4.731 Z1.53 </boundaryPoint>)
(<boundaryPoint> X11.275 Y-4.451 Z1.53 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.029 Z1.53 </boundaryPoint>)
M73 P96 (display progress)
(<boundaryPoint> X10.866 Y2.331 Z1.53 </boundaryPoint>)
(<boundaryPoint> X10.686 Y2.849 Z1.53 </boundaryPoint>)
(<boundaryPoint> X10.253 Y2.513 Z1.53 </boundaryPoint>)
(<boundaryPoint> X4.74 Y-4.442 Z1.53 </boundaryPoint>)
(<boundaryPoint> X4.876 Y-4.724 Z1.53 </boundaryPoint>)
(<edge> outer )
G1 X5.23 Y-4.15 Z1.53 F3300.0
G1 F1200.0
G1 E98.951
G1 F3300.0
M101
G1 X4.97 Y-4.47 Z1.53 F591.146 E98.958
G1 X5.0 Y-4.53 Z1.53 F591.146 E98.959
G1 X10.63 Y-4.53 Z1.53 F591.146 E99.061
G1 X11.12 Y-4.3 Z1.53 F591.146 E99.071
G1 X11.26 Y-4.0 Z1.53 F591.146 E99.077
G1 X10.63 Y2.67 Z1.53 F591.146 E99.198
G1 X5.23 Y-4.15 Z1.53 F591.146 E99.355
G1 F1200.0
G1 E98.355
G1 F591.146
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
M73 P97 (display progress)
(<infillPoint> X10.628 Y-4.531 Z0.95 </infillPoint>)
(<infillPoint> X11.123 Y-4.301 Z0.95 </infillPoint>)
(<infillPoint> X11.26 Y-3.995 Z0.95 </infillPoint>)
(<infillPoint> X10.669 Y2.288 Z0.95 </infillPoint>)
(<infillPoint> X10.621 Y2.427 Z0.95 </infillPoint>)
(<infillPoint> X10.511 Y2.46 Z0.95 </infillPoint>)
(<infillPoint> X10.395 Y2.37 Z0.95 </infillPoint>)
(<infillPoint> X4.975 Y-4.468 Z0.95 </infillPoint>)
(<infillPoint> X5.002 Y-4.524 Z0.95 </infillPoint>)
(</infillBoundary>)
;M108 R19.7
G1 X10.64 Y-0.4 Z1.53 F3300.0
G1 F1200.0
G1 E99.355
G1 F3300.0
M101
G1 X8.56 Y-0.4 Z1.53 F1182.291 E99.393
G1 X8.24 Y-0.8 Z1.53 F1182.291 E99.402
G1 X10.68 Y-0.8 Z1.53 F1182.291 E99.446
G1 X10.72 Y-1.2 Z1.53 F1182.291 E99.454
G1 X7.92 Y-1.2 Z1.53 F1182.291 E99.504
G1 X7.61 Y-1.6 Z1.53 F1182.291 E99.513
G1 X10.75 Y-1.6 Z1.53 F1182.291 E99.57
G1 X10.79 Y-2.0 Z1.53 F1182.291 E99.578
G1 X7.29 Y-2.0 Z1.53 F1182.291 E99.641
G1 X6.97 Y-2.4 Z1.53 F1182.291 E99.65
M73 P98 (display progress)
G1 X10.83 Y-2.4 Z1.53 F1182.291 E99.72
G1 X10.87 Y-2.8 Z1.53 F1182.291 E99.727
G1 X6.65 Y-2.8 Z1.53 F1182.291 E99.803
G1 X6.34 Y-3.2 Z1.53 F1182.291 E99.813
G1 X10.9 Y-3.2 Z1.53 F1182.291 E99.895
G1 X10.94 Y-3.6 Z1.53 F1182.291 E99.902
G1 X6.02 Y-3.6 Z1.53 F1182.291 E99.991
G1 X5.7 Y-4.0 Z1.53 F1182.291 E100.001
G1 X10.95 Y-4.0 Z1.53 F1182.291 E100.096
G1 F1200.0
G1 E99.096
G1 F1182.291
M103
G1 X10.6 Y-0.0 Z1.53 F3300.0
G1 F1200.0
G1 E100.096
G1 F3300.0
M101
G1 X8.87 Y-0.0 Z1.53 F1182.291 E100.127
G1 X9.19 Y0.4 Z1.53 F1182.291 E100.136
G1 X10.56 Y0.4 Z1.53 F1182.291 E100.161
G1 X10.53 Y0.8 Z1.53 F1182.291 E100.168
G1 X9.51 Y0.8 Z1.53 F1182.291 E100.187
G1 X9.82 Y1.2 Z1.53 F1182.291 E100.196
G1 X10.49 Y1.2 Z1.53 F1182.291 E100.208
G1 X10.45 Y1.6 Z1.53 F1182.291 E100.215
M73 P99 (display progress)
G1 X10.14 Y1.6 Z1.53 F1182.291 E100.221
G1 F1200.0
G1 E99.221
G1 F1182.291
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R40.0
(</layer>)
(</crafting>)
M104 S0
;M113 S0.0
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
