(** This GCode was generated by ReplicatorG 0040 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2013/05/24 14:07:51 (-0700) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
M109 S110 T0 (set HBP temperature)
M104 S220 T0 (set extruder temperature) (temp updated by printOMatic)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
M73 P1 (display progress)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.6      (Position Height)
M108 R5.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P2000     (Create Anchor)
(**** end of start.gcode ****)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
(<created> 13.05.24|14:7 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
M73 P2 (display progress)
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.1 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.1 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
(<operatingFeedRatePerSecond> 40.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 40.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 55.0 </travelFeedRatePerSecond>)
(<edgeWidth> 0.4 </edgeWidth>)
M73 P3 (display progress)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
M73 P4 (display progress)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning False </setting>)
(<setting> cool Turn_Fan_Off_at_Ending False </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.82 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
M73 P5 (display progress)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
M73 P6 (display progress)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 0 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
M73 P7 (display progress)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular True </setting>)
(<setting> fill Line False </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 1.0 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
M73 P8 (display progress)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: True </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 1 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
M73 P9 (display progress)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 2 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None False </setting>)
M73 P10 (display progress)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere True </setting>)
(<setting> raft Exterior_Only False </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 40.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 40.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
M73 P11 (display progress)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 55.0 </setting>)
(</settings>)
(<timeStampPreface> 20130524_140749 </timeStampPreface>)
(<procedureName> carve </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
M73 P12 (display progress)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
(<crafting>)
;M113 S1.0
;M108 R24.0
(<raftPerimeter>)
(<raftPoint> X-1.675 Y-7.908 </raftPoint>)
(<raftPoint> X14.532 Y-7.908 </raftPoint>)
(<raftPoint> X15.267 Y-7.517 </raftPoint>)
(<raftPoint> X15.267 Y7.517 </raftPoint>)
(<raftPoint> X14.532 Y7.908 </raftPoint>)
(<raftPoint> X-1.675 Y7.908 </raftPoint>)
(<raftPoint> X-5.275 Y9.708 </raftPoint>)
M73 P13 (display progress)
(<raftPoint> X-14.532 Y9.708 </raftPoint>)
(<raftPoint> X-15.267 Y9.317 </raftPoint>)
(<raftPoint> X-15.267 Y-9.317 </raftPoint>)
(<raftPoint> X-14.532 Y-9.708 </raftPoint>)
(<raftPoint> X-5.275 Y-9.708 </raftPoint>)
(</raftPerimeter>)
(<layer> 0.176 )
G1 X-14.67 Y-9.09 Z0.18 F3300.0
G1 F1200.0
G1 E1.0
G1 F3300.0
M101
G1 X-14.67 Y9.09 Z0.18 F371.901 E2.273
G1 X-11.73 Y9.09 Z0.18 F371.901 E2.479
G1 X-11.73 Y-9.09 Z0.18 F371.901 E3.752
G1 X-8.8 Y-9.09 Z0.18 F371.901 E3.957
M73 P14 (display progress)
G1 X-8.8 Y9.09 Z0.18 F371.901 E5.23
G1 X-5.87 Y9.09 Z0.18 F371.901 E5.435
G1 X-5.87 Y-9.09 Z0.18 F371.901 E6.709
G1 X-2.93 Y-7.29 Z0.18 F371.901 E6.95
G1 X-2.93 Y7.29 Z0.18 F371.901 E7.97
G1 X0.0 Y7.29 Z0.18 F371.901 E8.176
G1 X0.0 Y-7.29 Z0.18 F371.901 E9.197
G1 X2.93 Y-7.29 Z0.18 F371.901 E9.402
G1 X2.93 Y7.29 Z0.18 F371.901 E10.423
G1 X5.87 Y7.29 Z0.18 F371.901 E10.629
G1 X5.87 Y-7.29 Z0.18 F371.901 E11.65
G1 X8.8 Y-7.29 Z0.18 F371.901 E11.855
G1 X8.8 Y7.29 Z0.18 F371.901 E12.876
G1 X11.73 Y7.29 Z0.18 F371.901 E13.081
G1 X11.73 Y-7.29 Z0.18 F371.901 E14.102
G1 X14.67 Y-7.29 Z0.18 F371.901 E14.308
M73 P15 (display progress)
G1 X14.67 Y7.29 Z0.18 F371.901 E15.329
G1 F1200.0
G1 E14.329
G1 F371.901
M103
;M108 R28.0
(</layer>)
(<layer> 0.364 )
G1 X-14.74 Y0.0 Z0.36 F3300.0
G1 F1200.0
G1 E15.329
G1 F3300.0
M101
G1 X14.74 Y0.0 Z0.36 F1111.111 E16.135
G1 X14.74 Y-1.8 Z0.36 F1111.111 E16.184
G1 X-14.74 Y-1.8 Z0.36 F1111.111 E16.99
M73 P16 (display progress)
G1 X-14.74 Y-3.6 Z0.36 F1111.111 E17.039
G1 X14.74 Y-3.6 Z0.36 F1111.111 E17.846
G1 X14.74 Y-5.4 Z0.36 F1111.111 E17.895
G1 X-14.74 Y-5.4 Z0.36 F1111.111 E18.701
G1 X-14.74 Y-7.2 Z0.36 F1111.111 E18.75
G1 X14.74 Y-7.2 Z0.36 F1111.111 E19.557
G1 F1200.0
G1 E18.557
G1 F1111.111
M103
G1 X14.74 Y1.8 Z0.36 F3300.0
G1 F1200.0
G1 E19.557
G1 F3300.0
M101
G1 X-14.74 Y1.8 Z0.36 F1111.111 E20.363
M73 P17 (display progress)
G1 X-14.74 Y3.6 Z0.36 F1111.111 E20.412
G1 X14.74 Y3.6 Z0.36 F1111.111 E21.218
G1 X14.74 Y5.4 Z0.36 F1111.111 E21.268
G1 X-14.74 Y5.4 Z0.36 F1111.111 E22.074
G1 X-14.74 Y7.2 Z0.36 F1111.111 E22.123
G1 X14.74 Y7.2 Z0.36 F1111.111 E22.929
G1 F1200.0
G1 E21.929
G1 F1111.111
M103
G1 X-5.79 Y9.0 Z0.36 F3300.0
G1 F1200.0
G1 E22.929
G1 F3300.0
M101
M73 P18 (display progress)
G1 X-14.74 Y9.0 Z0.36 F1111.111 E23.174
G1 F1200.0
G1 E22.174
G1 F1111.111
M103
G1 X-14.74 Y-9.0 Z0.36 F3300.0
G1 F1200.0
G1 E23.174
G1 F3300.0
M101
G1 X-5.79 Y-9.0 Z0.36 F1111.111 E23.418
G1 F1200.0
G1 E22.418
G1 F1111.111
M103
;M108 R28.0
M73 P19 (display progress)
(</layer>)
(<layer> 0.544 )
G1 X-14.74 Y0.0 Z0.54 F3300.0
G1 F1200.0
G1 E23.418
G1 F3300.0
M101
G1 X14.74 Y0.0 Z0.54 F1111.111 E24.225
G1 X14.74 Y-1.8 Z0.54 F1111.111 E24.274
G1 X-14.74 Y-1.8 Z0.54 F1111.111 E25.08
G1 X-14.74 Y-3.6 Z0.54 F1111.111 E25.129
G1 X14.74 Y-3.6 Z0.54 F1111.111 E25.936
G1 X14.74 Y-5.4 Z0.54 F1111.111 E25.985
G1 X-14.74 Y-5.4 Z0.54 F1111.111 E26.791
G1 X-14.74 Y-7.2 Z0.54 F1111.111 E26.84
G1 X14.74 Y-7.2 Z0.54 F1111.111 E27.647
M73 P20 (display progress)
G1 F1200.0
G1 E26.647
G1 F1111.111
M103
G1 X14.74 Y1.8 Z0.54 F3300.0
G1 F1200.0
G1 E27.647
G1 F3300.0
M101
G1 X-14.74 Y1.8 Z0.54 F1111.111 E28.453
G1 X-14.74 Y3.6 Z0.54 F1111.111 E28.502
G1 X14.74 Y3.6 Z0.54 F1111.111 E29.308
G1 X14.74 Y5.4 Z0.54 F1111.111 E29.357
G1 X-14.74 Y5.4 Z0.54 F1111.111 E30.164
G1 X-14.74 Y7.2 Z0.54 F1111.111 E30.213
G1 X14.74 Y7.2 Z0.54 F1111.111 E31.019
M73 P21 (display progress)
G1 F1200.0
G1 E30.019
G1 F1111.111
M103
G1 X-5.79 Y9.0 Z0.54 F3300.0
G1 F1200.0
G1 E31.019
G1 F3300.0
M101
G1 X-14.74 Y9.0 Z0.54 F1111.111 E31.264
G1 F1200.0
G1 E30.264
G1 F1111.111
M103
G1 X-14.74 Y-9.0 Z0.54 F3300.0
G1 F1200.0
M73 P22 (display progress)
G1 E31.264
G1 F3300.0
M101
G1 X-5.79 Y-9.0 Z0.54 F1111.111 E31.508
G1 F1200.0
G1 E30.508
G1 F1111.111
M103
;M108 R18.0
(</layer>)
(<raftLayerEnd> </raftLayerEnd>)
(<layer> 0.63 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z0.63 </boundaryPoint>)
M73 P23 (display progress)
(<boundaryPoint> X-11.464 Y-6.218 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z0.63 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z0.63 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z0.63 </boundaryPoint>)
(<edge> outer )
G1 X-11.26 Y-5.9 Z0.63 F3300.0
G1 F1200.0
G1 E31.508
G1 F3300.0
M101
G1 X-11.26 Y-6.02 Z0.63 F1080.0 E31.511
G1 X-9.59 Y-6.02 Z0.63 F1080.0 E31.541
M73 P24 (display progress)
G1 X-9.59 Y-4.53 Z0.63 F1080.0 E31.568
G1 X11.26 Y-4.53 Z0.63 F1080.0 E31.945
G1 X11.26 Y4.53 Z0.63 F1080.0 E32.109
G1 X-9.59 Y4.53 Z0.63 F1080.0 E32.486
G1 X-9.59 Y6.02 Z0.63 F1080.0 E32.513
G1 X-11.26 Y6.02 Z0.63 F1080.0 E32.543
G1 X-11.26 Y-5.9 Z0.63 F1080.0 E32.759
G1 F1200.0
G1 E31.759
G1 F1080.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.05 </infillPoint>)
M73 P25 (display progress)
(<infillPoint> X-11.264 Y-6.018 Z0.05 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.05 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.05 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.05 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.05 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.05 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.05 </infillPoint>)
(</infillBoundary>)
;M108 R32.0
G1 X-10.0 Y5.64 Z0.63 F3300.0
G1 F1200.0
G1 E32.759
G1 F3300.0
M101
G1 X-10.0 Y-5.64 Z0.63 F2160.0 E32.94
G1 X-10.4 Y-5.74 Z0.63 F2160.0 E32.947
M73 P26 (display progress)
G1 X-10.4 Y5.74 Z0.63 F2160.0 E33.131
G1 X-10.8 Y5.69 Z0.63 F2160.0 E33.138
G1 X-10.8 Y-5.69 Z0.63 F2160.0 E33.321
G1 F1200.0
G1 E32.321
G1 F2160.0
M103
G1 X-9.6 Y4.25 Z0.63 F3300.0
G1 F1200.0
G1 E33.321
G1 F3300.0
M101
G1 X-9.6 Y-4.25 Z0.63 F2160.0 E33.457
G1 X-9.2 Y-4.25 Z0.63 F2160.0 E33.464
G1 X-9.2 Y4.25 Z0.63 F2160.0 E33.601
G1 X-8.8 Y4.25 Z0.63 F2160.0 E33.607
M73 P27 (display progress)
G1 X-8.8 Y-4.25 Z0.63 F2160.0 E33.744
G1 X-8.4 Y-4.25 Z0.63 F2160.0 E33.75
G1 X-8.4 Y4.25 Z0.63 F2160.0 E33.887
G1 X-8.0 Y4.25 Z0.63 F2160.0 E33.893
G1 X-8.0 Y-4.25 Z0.63 F2160.0 E34.03
G1 X-7.6 Y-4.25 Z0.63 F2160.0 E34.036
G1 X-7.6 Y4.25 Z0.63 F2160.0 E34.173
G1 X-7.2 Y4.25 Z0.63 F2160.0 E34.179
G1 X-7.2 Y-4.25 Z0.63 F2160.0 E34.316
G1 X-6.8 Y-4.25 Z0.63 F2160.0 E34.322
G1 X-6.8 Y4.25 Z0.63 F2160.0 E34.459
G1 X-6.4 Y4.25 Z0.63 F2160.0 E34.465
G1 X-6.4 Y-4.25 Z0.63 F2160.0 E34.602
G1 X-6.0 Y-4.25 Z0.63 F2160.0 E34.608
G1 X-6.0 Y4.25 Z0.63 F2160.0 E34.745
G1 X-5.6 Y4.25 Z0.63 F2160.0 E34.751
M73 P28 (display progress)
G1 X-5.6 Y-4.25 Z0.63 F2160.0 E34.888
G1 X-5.2 Y-4.25 Z0.63 F2160.0 E34.894
G1 X-5.2 Y4.25 Z0.63 F2160.0 E35.031
G1 X-4.8 Y4.25 Z0.63 F2160.0 E35.037
G1 X-4.8 Y-4.25 Z0.63 F2160.0 E35.174
G1 X-4.4 Y-4.25 Z0.63 F2160.0 E35.18
G1 X-4.4 Y4.25 Z0.63 F2160.0 E35.317
G1 X-4.0 Y4.25 Z0.63 F2160.0 E35.323
G1 X-4.0 Y-4.25 Z0.63 F2160.0 E35.46
G1 X-3.6 Y-4.25 Z0.63 F2160.0 E35.466
G1 X-3.6 Y4.25 Z0.63 F2160.0 E35.603
G1 X-3.2 Y4.25 Z0.63 F2160.0 E35.609
G1 X-3.2 Y-4.25 Z0.63 F2160.0 E35.746
G1 X-2.8 Y-4.25 Z0.63 F2160.0 E35.753
G1 X-2.8 Y4.25 Z0.63 F2160.0 E35.889
G1 X-2.4 Y4.25 Z0.63 F2160.0 E35.896
M73 P29 (display progress)
G1 X-2.4 Y-4.25 Z0.63 F2160.0 E36.032
G1 X-2.0 Y-4.25 Z0.63 F2160.0 E36.039
G1 X-2.0 Y4.25 Z0.63 F2160.0 E36.175
G1 X-1.6 Y4.25 Z0.63 F2160.0 E36.182
G1 X-1.6 Y-4.25 Z0.63 F2160.0 E36.318
G1 X-1.2 Y-4.25 Z0.63 F2160.0 E36.325
G1 X-1.2 Y4.25 Z0.63 F2160.0 E36.461
G1 X-0.8 Y4.25 Z0.63 F2160.0 E36.468
G1 X-0.8 Y-4.25 Z0.63 F2160.0 E36.604
G1 X-0.4 Y-4.25 Z0.63 F2160.0 E36.611
G1 X-0.4 Y4.25 Z0.63 F2160.0 E36.747
G1 X0.0 Y4.25 Z0.63 F2160.0 E36.754
G1 X-0.0 Y-4.25 Z0.63 F2160.0 E36.89
G1 X0.4 Y-4.25 Z0.63 F2160.0 E36.897
G1 X0.4 Y4.25 Z0.63 F2160.0 E37.033
M73 P30 (display progress)
G1 X0.8 Y4.25 Z0.63 F2160.0 E37.04
G1 X0.8 Y-4.25 Z0.63 F2160.0 E37.176
G1 X1.2 Y-4.25 Z0.63 F2160.0 E37.183
G1 X1.2 Y4.25 Z0.63 F2160.0 E37.32
G1 X1.6 Y4.25 Z0.63 F2160.0 E37.326
G1 X1.6 Y-4.25 Z0.63 F2160.0 E37.463
G1 X2.0 Y-4.25 Z0.63 F2160.0 E37.469
G1 X2.0 Y4.25 Z0.63 F2160.0 E37.606
G1 X2.4 Y4.25 Z0.63 F2160.0 E37.612
G1 X2.4 Y-4.25 Z0.63 F2160.0 E37.749
G1 X2.8 Y-4.25 Z0.63 F2160.0 E37.755
G1 X2.8 Y4.25 Z0.63 F2160.0 E37.892
G1 X3.2 Y4.25 Z0.63 F2160.0 E37.898
G1 X3.2 Y-4.25 Z0.63 F2160.0 E38.035
G1 X3.6 Y-4.25 Z0.63 F2160.0 E38.041
G1 X3.6 Y4.25 Z0.63 F2160.0 E38.178
M73 P31 (display progress)
G1 X4.0 Y4.25 Z0.63 F2160.0 E38.184
G1 X4.0 Y-4.25 Z0.63 F2160.0 E38.321
G1 X4.4 Y-4.25 Z0.63 F2160.0 E38.327
G1 X4.4 Y4.25 Z0.63 F2160.0 E38.464
G1 X4.8 Y4.25 Z0.63 F2160.0 E38.47
G1 X4.8 Y-4.25 Z0.63 F2160.0 E38.607
G1 X5.2 Y-4.25 Z0.63 F2160.0 E38.613
G1 X5.2 Y4.25 Z0.63 F2160.0 E38.75
G1 X5.6 Y4.25 Z0.63 F2160.0 E38.756
G1 X5.6 Y-4.25 Z0.63 F2160.0 E38.893
G1 X6.0 Y-4.25 Z0.63 F2160.0 E38.899
G1 X6.0 Y4.25 Z0.63 F2160.0 E39.036
G1 X6.4 Y4.25 Z0.63 F2160.0 E39.042
G1 X6.4 Y-4.25 Z0.63 F2160.0 E39.179
G1 X6.8 Y-4.25 Z0.63 F2160.0 E39.185
G1 X6.8 Y4.25 Z0.63 F2160.0 E39.322
M73 P32 (display progress)
G1 X7.2 Y4.25 Z0.63 F2160.0 E39.328
G1 X7.2 Y-4.25 Z0.63 F2160.0 E39.465
G1 X7.6 Y-4.25 Z0.63 F2160.0 E39.472
G1 X7.6 Y4.25 Z0.63 F2160.0 E39.608
G1 X8.0 Y4.25 Z0.63 F2160.0 E39.615
G1 X8.0 Y-4.25 Z0.63 F2160.0 E39.751
G1 X8.4 Y-4.25 Z0.63 F2160.0 E39.758
G1 X8.4 Y4.25 Z0.63 F2160.0 E39.894
G1 X8.8 Y4.25 Z0.63 F2160.0 E39.901
G1 X8.8 Y-4.25 Z0.63 F2160.0 E40.037
G1 X9.2 Y-4.25 Z0.63 F2160.0 E40.044
G1 X9.2 Y4.25 Z0.63 F2160.0 E40.18
G1 X9.6 Y4.25 Z0.63 F2160.0 E40.187
G1 X9.6 Y-4.25 Z0.63 F2160.0 E40.323
G1 X10.0 Y-4.25 Z0.63 F2160.0 E40.33
G1 X10.0 Y4.25 Z0.63 F2160.0 E40.466
M73 P33 (display progress)
G1 X10.4 Y4.25 Z0.63 F2160.0 E40.473
G1 X10.4 Y-4.25 Z0.63 F2160.0 E40.609
G1 X10.8 Y-4.2 Z0.63 F2160.0 E40.616
G1 X10.8 Y4.2 Z0.63 F2160.0 E40.751
G1 F1200.0
G1 E39.751
G1 F2160.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
;M108 R20.0
(<layer> 0.73 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
M73 P34 (display progress)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z0.73 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z0.73 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z0.73 </boundaryPoint>)
(<edge> outer )
G1 X-9.32 Y-4.33 Z0.73 F3300.0
G1 X-11.26 Y-5.59 Z0.73 F3300.0
G1 F1200.0
G1 E40.751
G1 F3300.0
M101
M73 P35 (display progress)
G1 X-11.26 Y-6.02 Z0.73 F1200.0 E40.759
G1 X-9.59 Y-6.02 Z0.73 F1200.0 E40.789
G1 X-9.59 Y-4.53 Z0.73 F1200.0 E40.816
G1 X11.26 Y-4.53 Z0.73 F1200.0 E41.193
G1 X11.26 Y4.53 Z0.73 F1200.0 E41.357
G1 X-9.59 Y4.53 Z0.73 F1200.0 E41.734
G1 X-9.59 Y6.02 Z0.73 F1200.0 E41.761
G1 X-11.26 Y6.02 Z0.73 F1200.0 E41.792
G1 X-11.26 Y-5.59 Z0.73 F1200.0 E42.001
G1 F1200.0
G1 E41.001
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
M73 P36 (display progress)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.15 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.15 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.15 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.15 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.15 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.15 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.15 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.15 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.59 Y-4.53 Z0.73 F3300.0
G1 X10.98 Y-0.0 Z0.73 F3300.0
G1 F1200.0
G1 E42.001
M73 P37 (display progress)
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z0.73 F2400.0 E42.399
G1 X-10.98 Y-0.4 Z0.73 F2400.0 E42.406
G1 X10.98 Y-0.4 Z0.73 F2400.0 E42.803
G1 X10.98 Y-0.8 Z0.73 F2400.0 E42.811
G1 X-10.98 Y-0.8 Z0.73 F2400.0 E43.208
G1 X-10.98 Y-1.2 Z0.73 F2400.0 E43.215
G1 X10.98 Y-1.2 Z0.73 F2400.0 E43.613
G1 X10.98 Y-1.6 Z0.73 F2400.0 E43.62
G1 X-10.98 Y-1.6 Z0.73 F2400.0 E44.017
G1 X-10.98 Y-2.0 Z0.73 F2400.0 E44.025
G1 X10.98 Y-2.0 Z0.73 F2400.0 E44.422
G1 X10.98 Y-2.4 Z0.73 F2400.0 E44.429
G1 X-10.98 Y-2.4 Z0.73 F2400.0 E44.827
G1 X-10.98 Y-2.8 Z0.73 F2400.0 E44.834
M73 P38 (display progress)
G1 X10.98 Y-2.8 Z0.73 F2400.0 E45.231
G1 X10.98 Y-3.2 Z0.73 F2400.0 E45.238
G1 X-10.98 Y-3.2 Z0.73 F2400.0 E45.636
G1 X-10.98 Y-3.6 Z0.73 F2400.0 E45.643
G1 X10.98 Y-3.6 Z0.73 F2400.0 E46.04
G1 X10.98 Y-4.0 Z0.73 F2400.0 E46.048
G1 X-10.98 Y-4.0 Z0.73 F2400.0 E46.445
G1 X-10.98 Y-4.4 Z0.73 F2400.0 E46.452
G1 X-9.87 Y-4.4 Z0.73 F2400.0 E46.472
G1 X-9.87 Y-4.8 Z0.73 F2400.0 E46.48
G1 X-10.98 Y-4.8 Z0.73 F2400.0 E46.5
G1 X-10.98 Y-5.2 Z0.73 F2400.0 E46.507
G1 X-9.87 Y-5.2 Z0.73 F2400.0 E46.527
G1 X-9.96 Y-5.6 Z0.73 F2400.0 E46.534
G1 X-10.89 Y-5.6 Z0.73 F2400.0 E46.551
G1 F1200.0
M73 P39 (display progress)
G1 E45.551
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z0.73 F3300.0
G1 F1200.0
G1 E46.551
G1 F3300.0
M101
G1 X10.98 Y0.4 Z0.73 F2400.0 E46.949
G1 X10.98 Y0.8 Z0.73 F2400.0 E46.956
G1 X-10.98 Y0.8 Z0.73 F2400.0 E47.353
G1 X-10.98 Y1.2 Z0.73 F2400.0 E47.361
G1 X10.98 Y1.2 Z0.73 F2400.0 E47.758
G1 X10.98 Y1.6 Z0.73 F2400.0 E47.765
G1 X-10.98 Y1.6 Z0.73 F2400.0 E48.163
G1 X-10.98 Y2.0 Z0.73 F2400.0 E48.17
M73 P40 (display progress)
G1 X10.98 Y2.0 Z0.73 F2400.0 E48.567
G1 X10.98 Y2.4 Z0.73 F2400.0 E48.574
G1 X-10.98 Y2.4 Z0.73 F2400.0 E48.972
G1 X-10.98 Y2.8 Z0.73 F2400.0 E48.979
G1 X10.98 Y2.8 Z0.73 F2400.0 E49.376
G1 X10.98 Y3.2 Z0.73 F2400.0 E49.384
G1 X-10.98 Y3.2 Z0.73 F2400.0 E49.781
G1 X-10.98 Y3.6 Z0.73 F2400.0 E49.788
G1 X10.98 Y3.6 Z0.73 F2400.0 E50.186
G1 X10.98 Y4.0 Z0.73 F2400.0 E50.193
G1 X-10.98 Y4.0 Z0.73 F2400.0 E50.59
G1 X-10.98 Y4.4 Z0.73 F2400.0 E50.597
G1 X-9.87 Y4.4 Z0.73 F2400.0 E50.618
G1 X-9.87 Y4.8 Z0.73 F2400.0 E50.625
G1 X-10.98 Y4.8 Z0.73 F2400.0 E50.645
G1 X-10.98 Y5.2 Z0.73 F2400.0 E50.652
M73 P41 (display progress)
G1 X-9.87 Y5.2 Z0.73 F2400.0 E50.672
G1 X-9.96 Y5.6 Z0.73 F2400.0 E50.68
G1 X-10.89 Y5.6 Z0.73 F2400.0 E50.697
G1 F1200.0
G1 E49.697
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
(<layer> 0.83 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
M73 P42 (display progress)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z0.83 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z0.83 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z0.83 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-11.2 Y-6.02 Z0.83 F3300.0
G1 F1200.0
G1 E50.697
G1 F3300.0
M101
M73 P43 (display progress)
G1 X-9.59 Y-6.02 Z0.83 F1200.0 E50.726
G1 X-9.59 Y-4.53 Z0.83 F1200.0 E50.753
G1 X11.26 Y-4.53 Z0.83 F1200.0 E51.13
G1 X11.26 Y4.53 Z0.83 F1200.0 E51.294
G1 X-9.59 Y4.53 Z0.83 F1200.0 E51.671
G1 X-9.59 Y6.02 Z0.83 F1200.0 E51.698
G1 X-11.26 Y6.02 Z0.83 F1200.0 E51.728
G1 X-11.26 Y-6.02 Z0.83 F1200.0 E51.946
G1 X-11.2 Y-6.02 Z0.83 F1200.0 E51.947
G1 F1200.0
G1 E50.947
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
M73 P44 (display progress)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.25 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.25 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.25 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.25 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.25 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.25 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.25 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.25 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-10.0 Y5.64 Z0.83 F3300.0
G1 F1200.0
G1 E51.947
G1 F3300.0
M101
M73 P45 (display progress)
G1 X-10.0 Y-5.64 Z0.83 F2400.0 E52.151
G1 X-10.4 Y-5.74 Z0.83 F2400.0 E52.158
G1 X-10.4 Y5.74 Z0.83 F2400.0 E52.366
G1 X-10.8 Y5.69 Z0.83 F2400.0 E52.373
G1 X-10.8 Y-5.69 Z0.83 F2400.0 E52.579
G1 F1200.0
G1 E51.579
G1 F2400.0
M103
G1 X-9.6 Y4.25 Z0.83 F3300.0
G1 F1200.0
G1 E52.579
G1 F3300.0
M101
G1 X-9.6 Y-4.25 Z0.83 F2400.0 E52.733
G1 X-9.2 Y-4.25 Z0.83 F2400.0 E52.74
M73 P46 (display progress)
G1 X-9.2 Y4.25 Z0.83 F2400.0 E52.894
G1 X-8.8 Y4.25 Z0.83 F2400.0 E52.901
G1 X-8.8 Y-4.25 Z0.83 F2400.0 E53.055
G1 X-8.4 Y-4.25 Z0.83 F2400.0 E53.062
G1 X-8.4 Y4.25 Z0.83 F2400.0 E53.216
G1 X-8.0 Y4.25 Z0.83 F2400.0 E53.223
G1 X-8.0 Y-4.25 Z0.83 F2400.0 E53.377
G1 X-7.6 Y-4.25 Z0.83 F2400.0 E53.384
G1 X-7.6 Y4.25 Z0.83 F2400.0 E53.538
G1 X-7.2 Y4.25 Z0.83 F2400.0 E53.545
G1 X-7.2 Y-4.25 Z0.83 F2400.0 E53.699
G1 X-6.8 Y-4.25 Z0.83 F2400.0 E53.706
G1 X-6.8 Y4.25 Z0.83 F2400.0 E53.859
G1 X-6.4 Y4.25 Z0.83 F2400.0 E53.867
G1 X-6.4 Y-4.25 Z0.83 F2400.0 E54.02
G1 X-6.0 Y-4.25 Z0.83 F2400.0 E54.028
M73 P47 (display progress)
G1 X-6.0 Y4.25 Z0.83 F2400.0 E54.181
G1 X-5.6 Y4.25 Z0.83 F2400.0 E54.189
G1 X-5.6 Y-4.25 Z0.83 F2400.0 E54.342
G1 X-5.2 Y-4.25 Z0.83 F2400.0 E54.349
G1 X-5.2 Y4.25 Z0.83 F2400.0 E54.503
G1 X-4.8 Y4.25 Z0.83 F2400.0 E54.51
G1 X-4.8 Y-4.25 Z0.83 F2400.0 E54.664
G1 X-4.4 Y-4.25 Z0.83 F2400.0 E54.671
G1 X-4.4 Y4.25 Z0.83 F2400.0 E54.825
G1 X-4.0 Y4.25 Z0.83 F2400.0 E54.832
G1 X-4.0 Y-4.25 Z0.83 F2400.0 E54.986
G1 X-3.6 Y-4.25 Z0.83 F2400.0 E54.993
G1 X-3.6 Y4.25 Z0.83 F2400.0 E55.147
G1 X-3.2 Y4.25 Z0.83 F2400.0 E55.154
G1 X-3.2 Y-4.25 Z0.83 F2400.0 E55.308
M73 P48 (display progress)
G1 X-2.8 Y-4.25 Z0.83 F2400.0 E55.315
G1 X-2.8 Y4.25 Z0.83 F2400.0 E55.469
G1 X-2.4 Y4.25 Z0.83 F2400.0 E55.476
G1 X-2.4 Y-4.25 Z0.83 F2400.0 E55.63
G1 X-2.0 Y-4.25 Z0.83 F2400.0 E55.637
G1 X-2.0 Y4.25 Z0.83 F2400.0 E55.79
G1 X-1.6 Y4.25 Z0.83 F2400.0 E55.798
G1 X-1.6 Y-4.25 Z0.83 F2400.0 E55.951
G1 X-1.2 Y-4.25 Z0.83 F2400.0 E55.959
G1 X-1.2 Y4.25 Z0.83 F2400.0 E56.112
G1 X-0.8 Y4.25 Z0.83 F2400.0 E56.12
G1 X-0.8 Y-4.25 Z0.83 F2400.0 E56.273
G1 X-0.4 Y-4.25 Z0.83 F2400.0 E56.28
G1 X-0.4 Y4.25 Z0.83 F2400.0 E56.434
G1 X0.0 Y4.25 Z0.83 F2400.0 E56.441
G1 X-0.0 Y-4.25 Z0.83 F2400.0 E56.595
M73 P49 (display progress)
G1 X0.4 Y-4.25 Z0.83 F2400.0 E56.602
G1 X0.4 Y4.25 Z0.83 F2400.0 E56.756
G1 X0.8 Y4.25 Z0.83 F2400.0 E56.763
G1 X0.8 Y-4.25 Z0.83 F2400.0 E56.917
G1 X1.2 Y-4.25 Z0.83 F2400.0 E56.924
G1 X1.2 Y4.25 Z0.83 F2400.0 E57.078
G1 X1.6 Y4.25 Z0.83 F2400.0 E57.085
G1 X1.6 Y-4.25 Z0.83 F2400.0 E57.239
G1 X2.0 Y-4.25 Z0.83 F2400.0 E57.246
G1 X2.0 Y4.25 Z0.83 F2400.0 E57.4
G1 X2.4 Y4.25 Z0.83 F2400.0 E57.407
G1 X2.4 Y-4.25 Z0.83 F2400.0 E57.561
G1 X2.8 Y-4.25 Z0.83 F2400.0 E57.568
G1 X2.8 Y4.25 Z0.83 F2400.0 E57.721
G1 X3.2 Y4.25 Z0.83 F2400.0 E57.729
G1 X3.2 Y-4.25 Z0.83 F2400.0 E57.882
M73 P50 (display progress)
G1 X3.6 Y-4.25 Z0.83 F2400.0 E57.89
G1 X3.6 Y4.25 Z0.83 F2400.0 E58.043
G1 X4.0 Y4.25 Z0.83 F2400.0 E58.051
G1 X4.0 Y-4.25 Z0.83 F2400.0 E58.204
G1 X4.4 Y-4.25 Z0.83 F2400.0 E58.211
G1 X4.4 Y4.25 Z0.83 F2400.0 E58.365
G1 X4.8 Y4.25 Z0.83 F2400.0 E58.372
G1 X4.8 Y-4.25 Z0.83 F2400.0 E58.526
G1 X5.2 Y-4.25 Z0.83 F2400.0 E58.533
G1 X5.2 Y4.25 Z0.83 F2400.0 E58.687
G1 X5.6 Y4.25 Z0.83 F2400.0 E58.694
G1 X5.6 Y-4.25 Z0.83 F2400.0 E58.848
G1 X6.0 Y-4.25 Z0.83 F2400.0 E58.855
G1 X6.0 Y4.25 Z0.83 F2400.0 E59.009
G1 X6.4 Y4.25 Z0.83 F2400.0 E59.016
G1 X6.4 Y-4.25 Z0.83 F2400.0 E59.17
M73 P51 (display progress)
G1 X6.8 Y-4.25 Z0.83 F2400.0 E59.177
G1 X6.8 Y4.25 Z0.83 F2400.0 E59.331
G1 X7.2 Y4.25 Z0.83 F2400.0 E59.338
G1 X7.2 Y-4.25 Z0.83 F2400.0 E59.492
G1 X7.6 Y-4.25 Z0.83 F2400.0 E59.499
G1 X7.6 Y4.25 Z0.83 F2400.0 E59.652
G1 X8.0 Y4.25 Z0.83 F2400.0 E59.66
G1 X8.0 Y-4.25 Z0.83 F2400.0 E59.813
G1 X8.4 Y-4.25 Z0.83 F2400.0 E59.821
G1 X8.4 Y4.25 Z0.83 F2400.0 E59.974
G1 X8.8 Y4.25 Z0.83 F2400.0 E59.982
G1 X8.8 Y-4.25 Z0.83 F2400.0 E60.135
G1 X9.2 Y-4.25 Z0.83 F2400.0 E60.142
G1 X9.2 Y4.25 Z0.83 F2400.0 E60.296
G1 X9.6 Y4.25 Z0.83 F2400.0 E60.303
G1 X9.6 Y-4.25 Z0.83 F2400.0 E60.457
M73 P52 (display progress)
G1 X10.0 Y-4.25 Z0.83 F2400.0 E60.464
G1 X10.0 Y4.25 Z0.83 F2400.0 E60.618
G1 X10.4 Y4.25 Z0.83 F2400.0 E60.625
G1 X10.4 Y-4.25 Z0.83 F2400.0 E60.779
G1 X10.8 Y-4.2 Z0.83 F2400.0 E60.786
G1 X10.8 Y4.2 Z0.83 F2400.0 E60.938
G1 F1200.0
G1 E59.938
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 0.93 )
M73 P53 (display progress)
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z0.93 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z0.93 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z0.93 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-8.94 Y-4.33 Z0.93 F3300.0
G1 X-11.26 Y-5.78 Z0.93 F3300.0
G1 F1200.0
M73 P54 (display progress)
G1 E60.938
G1 F3300.0
M101
G1 X-11.26 Y-6.02 Z0.93 F1200.0 E60.943
G1 X-9.59 Y-6.02 Z0.93 F1200.0 E60.973
G1 X-9.59 Y-4.53 Z0.93 F1200.0 E61.0
G1 X11.26 Y-4.53 Z0.93 F1200.0 E61.377
G1 X11.26 Y4.53 Z0.93 F1200.0 E61.541
G1 X-9.59 Y4.53 Z0.93 F1200.0 E61.918
G1 X-9.59 Y6.02 Z0.93 F1200.0 E61.945
G1 X-11.26 Y6.02 Z0.93 F1200.0 E61.975
G1 X-11.26 Y-5.78 Z0.93 F1200.0 E62.189
G1 F1200.0
G1 E61.189
G1 F1200.0
M103
M73 P55 (display progress)
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.35 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.35 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.35 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.35 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.35 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.35 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.35 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.35 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.59 Y-4.53 Z0.93 F3300.0
G1 X10.98 Y-0.0 Z0.93 F3300.0
M73 P56 (display progress)
G1 F1200.0
G1 E62.189
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z0.93 F2400.0 E62.586
G1 X-10.98 Y-0.4 Z0.93 F2400.0 E62.593
G1 X10.98 Y-0.4 Z0.93 F2400.0 E62.991
G1 X10.98 Y-0.8 Z0.93 F2400.0 E62.998
G1 X-10.98 Y-0.8 Z0.93 F2400.0 E63.395
G1 X-10.98 Y-1.2 Z0.93 F2400.0 E63.403
G1 X10.98 Y-1.2 Z0.93 F2400.0 E63.8
G1 X10.98 Y-1.6 Z0.93 F2400.0 E63.807
G1 X-10.98 Y-1.6 Z0.93 F2400.0 E64.205
G1 X-10.98 Y-2.0 Z0.93 F2400.0 E64.212
G1 X10.98 Y-2.0 Z0.93 F2400.0 E64.609
G1 X10.98 Y-2.4 Z0.93 F2400.0 E64.616
M73 P57 (display progress)
G1 X-10.98 Y-2.4 Z0.93 F2400.0 E65.014
G1 X-10.98 Y-2.8 Z0.93 F2400.0 E65.021
G1 X10.98 Y-2.8 Z0.93 F2400.0 E65.418
G1 X10.98 Y-3.2 Z0.93 F2400.0 E65.426
G1 X-10.98 Y-3.2 Z0.93 F2400.0 E65.823
G1 X-10.98 Y-3.6 Z0.93 F2400.0 E65.83
G1 X10.98 Y-3.6 Z0.93 F2400.0 E66.228
G1 X10.98 Y-4.0 Z0.93 F2400.0 E66.235
G1 X-10.98 Y-4.0 Z0.93 F2400.0 E66.632
G1 X-10.98 Y-4.4 Z0.93 F2400.0 E66.639
G1 X-9.87 Y-4.4 Z0.93 F2400.0 E66.66
G1 X-9.87 Y-4.8 Z0.93 F2400.0 E66.667
G1 X-10.98 Y-4.8 Z0.93 F2400.0 E66.687
G1 X-10.98 Y-5.2 Z0.93 F2400.0 E66.694
G1 X-9.87 Y-5.2 Z0.93 F2400.0 E66.714
G1 X-9.96 Y-5.6 Z0.93 F2400.0 E66.722
M73 P58 (display progress)
G1 X-10.89 Y-5.6 Z0.93 F2400.0 E66.739
G1 F1200.0
G1 E65.739
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z0.93 F3300.0
G1 F1200.0
G1 E66.739
G1 F3300.0
M101
G1 X10.98 Y0.4 Z0.93 F2400.0 E67.136
G1 X10.98 Y0.8 Z0.93 F2400.0 E67.143
G1 X-10.98 Y0.8 Z0.93 F2400.0 E67.541
G1 X-10.98 Y1.2 Z0.93 F2400.0 E67.548
G1 X10.98 Y1.2 Z0.93 F2400.0 E67.945
M73 P59 (display progress)
G1 X10.98 Y1.6 Z0.93 F2400.0 E67.952
G1 X-10.98 Y1.6 Z0.93 F2400.0 E68.35
G1 X-10.98 Y2.0 Z0.93 F2400.0 E68.357
G1 X10.98 Y2.0 Z0.93 F2400.0 E68.754
G1 X10.98 Y2.4 Z0.93 F2400.0 E68.762
G1 X-10.98 Y2.4 Z0.93 F2400.0 E69.159
G1 X-10.98 Y2.8 Z0.93 F2400.0 E69.166
G1 X10.98 Y2.8 Z0.93 F2400.0 E69.564
G1 X10.98 Y3.2 Z0.93 F2400.0 E69.571
G1 X-10.98 Y3.2 Z0.93 F2400.0 E69.968
G1 X-10.98 Y3.6 Z0.93 F2400.0 E69.975
G1 X10.98 Y3.6 Z0.93 F2400.0 E70.373
G1 X10.98 Y4.0 Z0.93 F2400.0 E70.38
G1 X-10.98 Y4.0 Z0.93 F2400.0 E70.777
G1 X-10.98 Y4.4 Z0.93 F2400.0 E70.785
G1 X-9.87 Y4.4 Z0.93 F2400.0 E70.805
M73 P60 (display progress)
G1 X-9.87 Y4.8 Z0.93 F2400.0 E70.812
G1 X-10.98 Y4.8 Z0.93 F2400.0 E70.832
G1 X-10.98 Y5.2 Z0.93 F2400.0 E70.839
G1 X-9.87 Y5.2 Z0.93 F2400.0 E70.86
G1 X-9.96 Y5.6 Z0.93 F2400.0 E70.867
G1 X-10.89 Y5.6 Z0.93 F2400.0 E70.884
G1 F1200.0
G1 E69.884
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.03 )
(<rotation> (6.12323399574e-17+1j) )
M73 P61 (display progress)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z1.03 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z1.03 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z1.03 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-11.01 Y-6.02 Z1.03 F3300.0
G1 F1200.0
G1 E70.884
G1 F3300.0
M73 P62 (display progress)
M101
G1 X-9.59 Y-6.02 Z1.03 F1200.0 E70.909
G1 X-9.59 Y-4.53 Z1.03 F1200.0 E70.936
G1 X11.26 Y-4.53 Z1.03 F1200.0 E71.314
G1 X11.26 Y4.53 Z1.03 F1200.0 E71.477
G1 X-9.59 Y4.53 Z1.03 F1200.0 E71.855
G1 X-9.59 Y6.02 Z1.03 F1200.0 E71.882
G1 X-11.26 Y6.02 Z1.03 F1200.0 E71.912
G1 X-11.26 Y-6.02 Z1.03 F1200.0 E72.13
G1 X-11.01 Y-6.02 Z1.03 F1200.0 E72.134
G1 F1200.0
G1 E71.134
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
M73 P63 (display progress)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.45 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.45 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.45 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.45 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.45 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.45 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.45 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.45 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-10.0 Y5.64 Z1.03 F3300.0
G1 F1200.0
G1 E72.134
G1 F3300.0
M73 P64 (display progress)
M101
G1 X-10.0 Y-5.64 Z1.03 F2400.0 E72.338
G1 X-10.4 Y-5.74 Z1.03 F2400.0 E72.346
G1 X-10.4 Y5.74 Z1.03 F2400.0 E72.553
G1 X-10.8 Y5.69 Z1.03 F2400.0 E72.561
G1 X-10.8 Y-5.69 Z1.03 F2400.0 E72.767
G1 F1200.0
G1 E71.767
G1 F2400.0
M103
G1 X-9.6 Y4.25 Z1.03 F3300.0
G1 F1200.0
G1 E72.767
G1 F3300.0
M101
M73 P65 (display progress)
G1 X-9.6 Y-4.25 Z1.03 F2400.0 E72.92
G1 X-9.2 Y-4.25 Z1.03 F2400.0 E72.928
G1 X-9.2 Y4.25 Z1.03 F2400.0 E73.081
G1 X-8.8 Y4.25 Z1.03 F2400.0 E73.088
G1 X-8.8 Y-4.25 Z1.03 F2400.0 E73.242
G1 X-8.4 Y-4.25 Z1.03 F2400.0 E73.249
G1 X-8.4 Y4.25 Z1.03 F2400.0 E73.403
G1 X-8.0 Y4.25 Z1.03 F2400.0 E73.41
G1 X-8.0 Y-4.25 Z1.03 F2400.0 E73.564
G1 X-7.6 Y-4.25 Z1.03 F2400.0 E73.571
G1 X-7.6 Y4.25 Z1.03 F2400.0 E73.725
G1 X-7.2 Y4.25 Z1.03 F2400.0 E73.732
G1 X-7.2 Y-4.25 Z1.03 F2400.0 E73.886
G1 X-6.8 Y-4.25 Z1.03 F2400.0 E73.893
G1 X-6.8 Y4.25 Z1.03 F2400.0 E74.047
G1 X-6.4 Y4.25 Z1.03 F2400.0 E74.054
M73 P66 (display progress)
G1 X-6.4 Y-4.25 Z1.03 F2400.0 E74.208
G1 X-6.0 Y-4.25 Z1.03 F2400.0 E74.215
G1 X-6.0 Y4.25 Z1.03 F2400.0 E74.369
G1 X-5.6 Y4.25 Z1.03 F2400.0 E74.376
G1 X-5.6 Y-4.25 Z1.03 F2400.0 E74.529
G1 X-5.2 Y-4.25 Z1.03 F2400.0 E74.537
G1 X-5.2 Y4.25 Z1.03 F2400.0 E74.69
G1 X-4.8 Y4.25 Z1.03 F2400.0 E74.698
G1 X-4.8 Y-4.25 Z1.03 F2400.0 E74.851
G1 X-4.4 Y-4.25 Z1.03 F2400.0 E74.859
G1 X-4.4 Y4.25 Z1.03 F2400.0 E75.012
G1 X-4.0 Y4.25 Z1.03 F2400.0 E75.019
G1 X-4.0 Y-4.25 Z1.03 F2400.0 E75.173
G1 X-3.6 Y-4.25 Z1.03 F2400.0 E75.18
G1 X-3.6 Y4.25 Z1.03 F2400.0 E75.334
G1 X-3.2 Y4.25 Z1.03 F2400.0 E75.341
M73 P67 (display progress)
G1 X-3.2 Y-4.25 Z1.03 F2400.0 E75.495
G1 X-2.8 Y-4.25 Z1.03 F2400.0 E75.502
G1 X-2.8 Y4.25 Z1.03 F2400.0 E75.656
G1 X-2.4 Y4.25 Z1.03 F2400.0 E75.663
G1 X-2.4 Y-4.25 Z1.03 F2400.0 E75.817
G1 X-2.0 Y-4.25 Z1.03 F2400.0 E75.824
G1 X-2.0 Y4.25 Z1.03 F2400.0 E75.978
G1 X-1.6 Y4.25 Z1.03 F2400.0 E75.985
G1 X-1.6 Y-4.25 Z1.03 F2400.0 E76.139
G1 X-1.2 Y-4.25 Z1.03 F2400.0 E76.146
G1 X-1.2 Y4.25 Z1.03 F2400.0 E76.3
G1 X-0.8 Y4.25 Z1.03 F2400.0 E76.307
G1 X-0.8 Y-4.25 Z1.03 F2400.0 E76.46
G1 X-0.4 Y-4.25 Z1.03 F2400.0 E76.468
G1 X-0.4 Y4.25 Z1.03 F2400.0 E76.621
G1 X0.0 Y4.25 Z1.03 F2400.0 E76.629
M73 P68 (display progress)
G1 X-0.0 Y-4.25 Z1.03 F2400.0 E76.782
G1 X0.4 Y-4.25 Z1.03 F2400.0 E76.79
G1 X0.4 Y4.25 Z1.03 F2400.0 E76.943
G1 X0.8 Y4.25 Z1.03 F2400.0 E76.95
G1 X0.8 Y-4.25 Z1.03 F2400.0 E77.104
G1 X1.2 Y-4.25 Z1.03 F2400.0 E77.111
G1 X1.2 Y4.25 Z1.03 F2400.0 E77.265
G1 X1.6 Y4.25 Z1.03 F2400.0 E77.272
G1 X1.6 Y-4.25 Z1.03 F2400.0 E77.426
G1 X2.0 Y-4.25 Z1.03 F2400.0 E77.433
G1 X2.0 Y4.25 Z1.03 F2400.0 E77.587
G1 X2.4 Y4.25 Z1.03 F2400.0 E77.594
G1 X2.4 Y-4.25 Z1.03 F2400.0 E77.748
G1 X2.8 Y-4.25 Z1.03 F2400.0 E77.755
G1 X2.8 Y4.25 Z1.03 F2400.0 E77.909
G1 X3.2 Y4.25 Z1.03 F2400.0 E77.916
M73 P69 (display progress)
G1 X3.2 Y-4.25 Z1.03 F2400.0 E78.07
G1 X3.6 Y-4.25 Z1.03 F2400.0 E78.077
G1 X3.6 Y4.25 Z1.03 F2400.0 E78.231
G1 X4.0 Y4.25 Z1.03 F2400.0 E78.238
G1 X4.0 Y-4.25 Z1.03 F2400.0 E78.391
G1 X4.4 Y-4.25 Z1.03 F2400.0 E78.399
G1 X4.4 Y4.25 Z1.03 F2400.0 E78.552
G1 X4.8 Y4.25 Z1.03 F2400.0 E78.56
G1 X4.8 Y-4.25 Z1.03 F2400.0 E78.713
G1 X5.2 Y-4.25 Z1.03 F2400.0 E78.721
G1 X5.2 Y4.25 Z1.03 F2400.0 E78.874
G1 X5.6 Y4.25 Z1.03 F2400.0 E78.881
G1 X5.6 Y-4.25 Z1.03 F2400.0 E79.035
G1 X6.0 Y-4.25 Z1.03 F2400.0 E79.042
G1 X6.0 Y4.25 Z1.03 F2400.0 E79.196
G1 X6.4 Y4.25 Z1.03 F2400.0 E79.203
M73 P70 (display progress)
G1 X6.4 Y-4.25 Z1.03 F2400.0 E79.357
G1 X6.8 Y-4.25 Z1.03 F2400.0 E79.364
G1 X6.8 Y4.25 Z1.03 F2400.0 E79.518
G1 X7.2 Y4.25 Z1.03 F2400.0 E79.525
G1 X7.2 Y-4.25 Z1.03 F2400.0 E79.679
G1 X7.6 Y-4.25 Z1.03 F2400.0 E79.686
G1 X7.6 Y4.25 Z1.03 F2400.0 E79.84
G1 X8.0 Y4.25 Z1.03 F2400.0 E79.847
G1 X8.0 Y-4.25 Z1.03 F2400.0 E80.001
G1 X8.4 Y-4.25 Z1.03 F2400.0 E80.008
G1 X8.4 Y4.25 Z1.03 F2400.0 E80.162
G1 X8.8 Y4.25 Z1.03 F2400.0 E80.169
G1 X8.8 Y-4.25 Z1.03 F2400.0 E80.322
G1 X9.2 Y-4.25 Z1.03 F2400.0 E80.33
G1 X9.2 Y4.25 Z1.03 F2400.0 E80.483
M73 P71 (display progress)
G1 X9.6 Y4.25 Z1.03 F2400.0 E80.491
G1 X9.6 Y-4.25 Z1.03 F2400.0 E80.644
G1 X10.0 Y-4.25 Z1.03 F2400.0 E80.652
G1 X10.0 Y4.25 Z1.03 F2400.0 E80.805
G1 X10.4 Y4.25 Z1.03 F2400.0 E80.812
G1 X10.4 Y-4.25 Z1.03 F2400.0 E80.966
G1 X10.8 Y-4.2 Z1.03 F2400.0 E80.973
G1 X10.8 Y4.2 Z1.03 F2400.0 E81.126
G1 F1200.0
G1 E80.126
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
M73 P72 (display progress)
(<layer> 1.13 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z1.13 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z1.13 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z1.13 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-9.59 Y-4.53 Z1.13 F3300.0
G1 X-11.26 Y-5.97 Z1.13 F3300.0
M73 P73 (display progress)
G1 F1200.0
G1 E81.126
G1 F3300.0
M101
G1 X-11.26 Y-6.02 Z1.13 F1200.0 E81.126
G1 X-9.59 Y-6.02 Z1.13 F1200.0 E81.157
G1 X-9.59 Y-4.53 Z1.13 F1200.0 E81.184
G1 X11.26 Y-4.53 Z1.13 F1200.0 E81.561
G1 X11.26 Y4.53 Z1.13 F1200.0 E81.725
G1 X-9.59 Y4.53 Z1.13 F1200.0 E82.102
G1 X-9.59 Y6.02 Z1.13 F1200.0 E82.129
G1 X-11.26 Y6.02 Z1.13 F1200.0 E82.159
G1 X-11.26 Y-5.97 Z1.13 F1200.0 E82.376
G1 F1200.0
G1 E81.376
G1 F1200.0
M73 P74 (display progress)
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.55 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.55 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.55 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.55 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.55 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.55 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.55 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.55 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-9.59 Y-4.53 Z1.13 F3300.0
M73 P75 (display progress)
G1 X10.98 Y-0.0 Z1.13 F3300.0
G1 F1200.0
G1 E82.376
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z1.13 F2400.0 E82.773
G1 X-10.98 Y-0.4 Z1.13 F2400.0 E82.781
G1 X10.98 Y-0.4 Z1.13 F2400.0 E83.178
G1 X10.98 Y-0.8 Z1.13 F2400.0 E83.185
G1 X-10.98 Y-0.8 Z1.13 F2400.0 E83.583
G1 X-10.98 Y-1.2 Z1.13 F2400.0 E83.59
G1 X10.98 Y-1.2 Z1.13 F2400.0 E83.987
G1 X10.98 Y-1.6 Z1.13 F2400.0 E83.994
G1 X-10.98 Y-1.6 Z1.13 F2400.0 E84.392
G1 X-10.98 Y-2.0 Z1.13 F2400.0 E84.399
G1 X10.98 Y-2.0 Z1.13 F2400.0 E84.796
M73 P76 (display progress)
G1 X10.98 Y-2.4 Z1.13 F2400.0 E84.804
G1 X-10.98 Y-2.4 Z1.13 F2400.0 E85.201
G1 X-10.98 Y-2.8 Z1.13 F2400.0 E85.208
G1 X10.98 Y-2.8 Z1.13 F2400.0 E85.606
G1 X10.98 Y-3.2 Z1.13 F2400.0 E85.613
G1 X-10.98 Y-3.2 Z1.13 F2400.0 E86.01
G1 X-10.98 Y-3.6 Z1.13 F2400.0 E86.017
G1 X10.98 Y-3.6 Z1.13 F2400.0 E86.415
G1 X10.98 Y-4.0 Z1.13 F2400.0 E86.422
G1 X-10.98 Y-4.0 Z1.13 F2400.0 E86.819
G1 X-10.98 Y-4.4 Z1.13 F2400.0 E86.827
G1 X-9.87 Y-4.4 Z1.13 F2400.0 E86.847
G1 X-9.87 Y-4.8 Z1.13 F2400.0 E86.854
G1 X-10.98 Y-4.8 Z1.13 F2400.0 E86.874
G1 X-10.98 Y-5.2 Z1.13 F2400.0 E86.881
M73 P77 (display progress)
G1 X-9.87 Y-5.2 Z1.13 F2400.0 E86.902
G1 X-9.96 Y-5.6 Z1.13 F2400.0 E86.909
G1 X-10.89 Y-5.6 Z1.13 F2400.0 E86.926
G1 F1200.0
G1 E85.926
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z1.13 F3300.0
G1 F1200.0
G1 E86.926
G1 F3300.0
M101
G1 X10.98 Y0.4 Z1.13 F2400.0 E87.323
G1 X10.98 Y0.8 Z1.13 F2400.0 E87.33
G1 X-10.98 Y0.8 Z1.13 F2400.0 E87.728
G1 X-10.98 Y1.2 Z1.13 F2400.0 E87.735
M73 P78 (display progress)
G1 X10.98 Y1.2 Z1.13 F2400.0 E88.132
G1 X10.98 Y1.6 Z1.13 F2400.0 E88.14
G1 X-10.98 Y1.6 Z1.13 F2400.0 E88.537
G1 X-10.98 Y2.0 Z1.13 F2400.0 E88.544
G1 X10.98 Y2.0 Z1.13 F2400.0 E88.942
G1 X10.98 Y2.4 Z1.13 F2400.0 E88.949
G1 X-10.98 Y2.4 Z1.13 F2400.0 E89.346
G1 X-10.98 Y2.8 Z1.13 F2400.0 E89.353
G1 X10.98 Y2.8 Z1.13 F2400.0 E89.751
G1 X10.98 Y3.2 Z1.13 F2400.0 E89.758
G1 X-10.98 Y3.2 Z1.13 F2400.0 E90.155
G1 X-10.98 Y3.6 Z1.13 F2400.0 E90.163
G1 X10.98 Y3.6 Z1.13 F2400.0 E90.56
G1 X10.98 Y4.0 Z1.13 F2400.0 E90.567
G1 X-10.98 Y4.0 Z1.13 F2400.0 E90.965
G1 X-10.98 Y4.4 Z1.13 F2400.0 E90.972
M73 P79 (display progress)
G1 X-9.87 Y4.4 Z1.13 F2400.0 E90.992
G1 X-9.87 Y4.8 Z1.13 F2400.0 E90.999
G1 X-10.98 Y4.8 Z1.13 F2400.0 E91.019
G1 X-10.98 Y5.2 Z1.13 F2400.0 E91.027
G1 X-9.87 Y5.2 Z1.13 F2400.0 E91.047
G1 X-9.96 Y5.6 Z1.13 F2400.0 E91.054
G1 X-10.89 Y5.6 Z1.13 F2400.0 E91.071
G1 F1200.0
G1 E90.071
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
(<layer> 1.23 )
M73 P80 (display progress)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z1.23 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z1.23 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z1.23 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-11.26 Y-5.66 Z1.23 F3300.0
G1 F1200.0
G1 E91.071
M73 P81 (display progress)
G1 F3300.0
M101
G1 X-11.26 Y-6.02 Z1.23 F1200.0 E91.078
G1 X-9.59 Y-6.02 Z1.23 F1200.0 E91.108
G1 X-9.59 Y-4.53 Z1.23 F1200.0 E91.135
G1 X11.26 Y-4.53 Z1.23 F1200.0 E91.512
G1 X11.26 Y4.53 Z1.23 F1200.0 E91.676
G1 X-9.59 Y4.53 Z1.23 F1200.0 E92.053
G1 X-9.59 Y6.02 Z1.23 F1200.0 E92.08
G1 X-11.26 Y6.02 Z1.23 F1200.0 E92.11
G1 X-11.26 Y-5.66 Z1.23 F1200.0 E92.322
G1 F1200.0
G1 E91.322
G1 F1200.0
M103
(</edge>)
M73 P82 (display progress)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.65 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.65 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.65 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.65 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.65 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.65 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.65 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.65 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
G1 X-10.0 Y5.64 Z1.23 F3300.0
G1 F1200.0
M73 P83 (display progress)
G1 E92.322
G1 F3300.0
M101
G1 X-10.0 Y-5.64 Z1.23 F2400.0 E92.526
G1 X-10.4 Y-5.74 Z1.23 F2400.0 E92.533
G1 X-10.4 Y5.74 Z1.23 F2400.0 E92.741
G1 X-10.8 Y5.69 Z1.23 F2400.0 E92.748
G1 X-10.8 Y-5.69 Z1.23 F2400.0 E92.954
G1 F1200.0
G1 E91.954
G1 F2400.0
M103
G1 X-9.6 Y4.25 Z1.23 F3300.0
G1 F1200.0
G1 E92.954
G1 F3300.0
M73 P84 (display progress)
M101
G1 X-9.6 Y-4.25 Z1.23 F2400.0 E93.108
G1 X-9.2 Y-4.25 Z1.23 F2400.0 E93.115
G1 X-9.2 Y4.25 Z1.23 F2400.0 E93.268
G1 X-8.8 Y4.25 Z1.23 F2400.0 E93.276
G1 X-8.8 Y-4.25 Z1.23 F2400.0 E93.429
G1 X-8.4 Y-4.25 Z1.23 F2400.0 E93.437
G1 X-8.4 Y4.25 Z1.23 F2400.0 E93.59
G1 X-8.0 Y4.25 Z1.23 F2400.0 E93.597
G1 X-8.0 Y-4.25 Z1.23 F2400.0 E93.751
G1 X-7.6 Y-4.25 Z1.23 F2400.0 E93.758
G1 X-7.6 Y4.25 Z1.23 F2400.0 E93.912
G1 X-7.2 Y4.25 Z1.23 F2400.0 E93.919
G1 X-7.2 Y-4.25 Z1.23 F2400.0 E94.073
G1 X-6.8 Y-4.25 Z1.23 F2400.0 E94.08
G1 X-6.8 Y4.25 Z1.23 F2400.0 E94.234
M73 P85 (display progress)
G1 X-6.4 Y4.25 Z1.23 F2400.0 E94.241
G1 X-6.4 Y-4.25 Z1.23 F2400.0 E94.395
G1 X-6.0 Y-4.25 Z1.23 F2400.0 E94.402
G1 X-6.0 Y4.25 Z1.23 F2400.0 E94.556
G1 X-5.6 Y4.25 Z1.23 F2400.0 E94.563
G1 X-5.6 Y-4.25 Z1.23 F2400.0 E94.717
G1 X-5.2 Y-4.25 Z1.23 F2400.0 E94.724
G1 X-5.2 Y4.25 Z1.23 F2400.0 E94.878
G1 X-4.8 Y4.25 Z1.23 F2400.0 E94.885
G1 X-4.8 Y-4.25 Z1.23 F2400.0 E95.039
G1 X-4.4 Y-4.25 Z1.23 F2400.0 E95.046
G1 X-4.4 Y4.25 Z1.23 F2400.0 E95.199
G1 X-4.0 Y4.25 Z1.23 F2400.0 E95.207
G1 X-4.0 Y-4.25 Z1.23 F2400.0 E95.36
G1 X-3.6 Y-4.25 Z1.23 F2400.0 E95.368
G1 X-3.6 Y4.25 Z1.23 F2400.0 E95.521
M73 P86 (display progress)
G1 X-3.2 Y4.25 Z1.23 F2400.0 E95.529
G1 X-3.2 Y-4.25 Z1.23 F2400.0 E95.682
G1 X-2.8 Y-4.25 Z1.23 F2400.0 E95.689
G1 X-2.8 Y4.25 Z1.23 F2400.0 E95.843
G1 X-2.4 Y4.25 Z1.23 F2400.0 E95.85
G1 X-2.4 Y-4.25 Z1.23 F2400.0 E96.004
G1 X-2.0 Y-4.25 Z1.23 F2400.0 E96.011
G1 X-2.0 Y4.25 Z1.23 F2400.0 E96.165
G1 X-1.6 Y4.25 Z1.23 F2400.0 E96.172
G1 X-1.6 Y-4.25 Z1.23 F2400.0 E96.326
G1 X-1.2 Y-4.25 Z1.23 F2400.0 E96.333
G1 X-1.2 Y4.25 Z1.23 F2400.0 E96.487
G1 X-0.8 Y4.25 Z1.23 F2400.0 E96.494
G1 X-0.8 Y-4.25 Z1.23 F2400.0 E96.648
G1 X-0.4 Y-4.25 Z1.23 F2400.0 E96.655
G1 X-0.4 Y4.25 Z1.23 F2400.0 E96.809
M73 P87 (display progress)
G1 X0.0 Y4.25 Z1.23 F2400.0 E96.816
G1 X-0.0 Y-4.25 Z1.23 F2400.0 E96.97
G1 X0.4 Y-4.25 Z1.23 F2400.0 E96.977
G1 X0.4 Y4.25 Z1.23 F2400.0 E97.13
G1 X0.8 Y4.25 Z1.23 F2400.0 E97.138
G1 X0.8 Y-4.25 Z1.23 F2400.0 E97.291
G1 X1.2 Y-4.25 Z1.23 F2400.0 E97.299
G1 X1.2 Y4.25 Z1.23 F2400.0 E97.452
G1 X1.6 Y4.25 Z1.23 F2400.0 E97.46
G1 X1.6 Y-4.25 Z1.23 F2400.0 E97.613
G1 X2.0 Y-4.25 Z1.23 F2400.0 E97.62
G1 X2.0 Y4.25 Z1.23 F2400.0 E97.774
G1 X2.4 Y4.25 Z1.23 F2400.0 E97.781
G1 X2.4 Y-4.25 Z1.23 F2400.0 E97.935
G1 X2.8 Y-4.25 Z1.23 F2400.0 E97.942
G1 X2.8 Y4.25 Z1.23 F2400.0 E98.096
M73 P88 (display progress)
G1 X3.2 Y4.25 Z1.23 F2400.0 E98.103
G1 X3.2 Y-4.25 Z1.23 F2400.0 E98.257
G1 X3.6 Y-4.25 Z1.23 F2400.0 E98.264
G1 X3.6 Y4.25 Z1.23 F2400.0 E98.418
G1 X4.0 Y4.25 Z1.23 F2400.0 E98.425
G1 X4.0 Y-4.25 Z1.23 F2400.0 E98.579
G1 X4.4 Y-4.25 Z1.23 F2400.0 E98.586
G1 X4.4 Y4.25 Z1.23 F2400.0 E98.74
G1 X4.8 Y4.25 Z1.23 F2400.0 E98.747
G1 X4.8 Y-4.25 Z1.23 F2400.0 E98.901
G1 X5.2 Y-4.25 Z1.23 F2400.0 E98.908
G1 X5.2 Y4.25 Z1.23 F2400.0 E99.061
G1 X5.6 Y4.25 Z1.23 F2400.0 E99.069
G1 X5.6 Y-4.25 Z1.23 F2400.0 E99.222
G1 X6.0 Y-4.25 Z1.23 F2400.0 E99.23
M73 P89 (display progress)
G1 X6.0 Y4.25 Z1.23 F2400.0 E99.383
G1 X6.4 Y4.25 Z1.23 F2400.0 E99.391
G1 X6.4 Y-4.25 Z1.23 F2400.0 E99.544
G1 X6.8 Y-4.25 Z1.23 F2400.0 E99.551
G1 X6.8 Y4.25 Z1.23 F2400.0 E99.705
G1 X7.2 Y4.25 Z1.23 F2400.0 E99.712
G1 X7.2 Y-4.25 Z1.23 F2400.0 E99.866
G1 X7.6 Y-4.25 Z1.23 F2400.0 E99.873
G1 X7.6 Y4.25 Z1.23 F2400.0 E100.027
G1 X8.0 Y4.25 Z1.23 F2400.0 E100.034
G1 X8.0 Y-4.25 Z1.23 F2400.0 E100.188
G1 X8.4 Y-4.25 Z1.23 F2400.0 E100.195
G1 X8.4 Y4.25 Z1.23 F2400.0 E100.349
G1 X8.8 Y4.25 Z1.23 F2400.0 E100.356
G1 X8.8 Y-4.25 Z1.23 F2400.0 E100.51
G1 X9.2 Y-4.25 Z1.23 F2400.0 E100.517
M73 P90 (display progress)
G1 X9.2 Y4.25 Z1.23 F2400.0 E100.671
G1 X9.6 Y4.25 Z1.23 F2400.0 E100.678
G1 X9.6 Y-4.25 Z1.23 F2400.0 E100.832
G1 X10.0 Y-4.25 Z1.23 F2400.0 E100.839
G1 X10.0 Y4.25 Z1.23 F2400.0 E100.992
G1 X10.4 Y4.25 Z1.23 F2400.0 E101.0
G1 X10.4 Y-4.25 Z1.23 F2400.0 E101.153
G1 X10.8 Y-4.2 Z1.23 F2400.0 E101.161
G1 X10.8 Y4.2 Z1.23 F2400.0 E101.313
G1 F1200.0
G1 E100.313
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
M73 P91 (display progress)
(</layer>)
(<layer> 1.33 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-11.464 Y6.218 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-11.464 Y-6.218 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-6.218 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y-4.728 Z1.33 </boundaryPoint>)
(<boundaryPoint> X11.464 Y-4.728 Z1.33 </boundaryPoint>)
(<boundaryPoint> X11.464 Y4.728 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y4.728 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-9.391 Y6.218 Z1.33 </boundaryPoint>)
(<edge> outer )
;M108 R20.0
G1 X-9.59 Y-4.53 Z1.33 F3300.0
M73 P92 (display progress)
G1 X-11.13 Y-6.02 Z1.33 F3300.0
G1 F1200.0
G1 E101.313
G1 F3300.0
M101
G1 X-9.59 Y-6.02 Z1.33 F1200.0 E101.34
G1 X-9.59 Y-4.53 Z1.33 F1200.0 E101.367
G1 X11.26 Y-4.53 Z1.33 F1200.0 E101.745
G1 X11.26 Y4.53 Z1.33 F1200.0 E101.909
G1 X-9.59 Y4.53 Z1.33 F1200.0 E102.286
G1 X-9.59 Y6.02 Z1.33 F1200.0 E102.313
G1 X-11.26 Y6.02 Z1.33 F1200.0 E102.343
G1 X-11.26 Y-6.02 Z1.33 F1200.0 E102.561
G1 X-11.13 Y-6.02 Z1.33 F1200.0 E102.563
G1 F1200.0
G1 E101.563
M73 P93 (display progress)
G1 F1200.0
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-11.264 Y6.018 Z0.75 </infillPoint>)
(<infillPoint> X-11.264 Y-6.018 Z0.75 </infillPoint>)
(<infillPoint> X-9.591 Y-6.018 Z0.75 </infillPoint>)
(<infillPoint> X-9.591 Y-4.528 Z0.75 </infillPoint>)
(<infillPoint> X11.264 Y-4.528 Z0.75 </infillPoint>)
(<infillPoint> X11.264 Y4.528 Z0.75 </infillPoint>)
(<infillPoint> X-9.591 Y4.528 Z0.75 </infillPoint>)
(<infillPoint> X-9.591 Y6.018 Z0.75 </infillPoint>)
(</infillBoundary>)
;M108 R40.0
M73 P94 (display progress)
G1 X-9.59 Y-4.53 Z1.33 F3300.0
G1 X10.98 Y-0.0 Z1.33 F3300.0
G1 F1200.0
G1 E102.563
G1 F3300.0
M101
G1 X-10.98 Y0.0 Z1.33 F2400.0 E102.961
G1 X-10.98 Y-0.4 Z1.33 F2400.0 E102.968
G1 X10.98 Y-0.4 Z1.33 F2400.0 E103.365
G1 X10.98 Y-0.8 Z1.33 F2400.0 E103.372
G1 X-10.98 Y-0.8 Z1.33 F2400.0 E103.77
G1 X-10.98 Y-1.2 Z1.33 F2400.0 E103.777
G1 X10.98 Y-1.2 Z1.33 F2400.0 E104.174
G1 X10.98 Y-1.6 Z1.33 F2400.0 E104.182
G1 X-10.98 Y-1.6 Z1.33 F2400.0 E104.579
M73 P95 (display progress)
G1 X-10.98 Y-2.0 Z1.33 F2400.0 E104.586
G1 X10.98 Y-2.0 Z1.33 F2400.0 E104.984
G1 X10.98 Y-2.4 Z1.33 F2400.0 E104.991
G1 X-10.98 Y-2.4 Z1.33 F2400.0 E105.388
G1 X-10.98 Y-2.8 Z1.33 F2400.0 E105.395
G1 X10.98 Y-2.8 Z1.33 F2400.0 E105.793
G1 X10.98 Y-3.2 Z1.33 F2400.0 E105.8
G1 X-10.98 Y-3.2 Z1.33 F2400.0 E106.197
G1 X-10.98 Y-3.6 Z1.33 F2400.0 E106.205
G1 X10.98 Y-3.6 Z1.33 F2400.0 E106.602
G1 X10.98 Y-4.0 Z1.33 F2400.0 E106.609
G1 X-10.98 Y-4.0 Z1.33 F2400.0 E107.007
G1 X-10.98 Y-4.4 Z1.33 F2400.0 E107.014
G1 X-9.87 Y-4.4 Z1.33 F2400.0 E107.034
G1 X-9.87 Y-4.8 Z1.33 F2400.0 E107.041
G1 X-10.98 Y-4.8 Z1.33 F2400.0 E107.061
M73 P96 (display progress)
G1 X-10.98 Y-5.2 Z1.33 F2400.0 E107.069
G1 X-9.87 Y-5.2 Z1.33 F2400.0 E107.089
G1 X-9.96 Y-5.6 Z1.33 F2400.0 E107.096
G1 X-10.89 Y-5.6 Z1.33 F2400.0 E107.113
G1 F1200.0
G1 E106.113
G1 F2400.0
M103
G1 X-10.98 Y0.4 Z1.33 F3300.0
G1 F1200.0
G1 E107.113
G1 F3300.0
M101
G1 X10.98 Y0.4 Z1.33 F2400.0 E107.51
G1 X10.98 Y0.8 Z1.33 F2400.0 E107.518
G1 X-10.98 Y0.8 Z1.33 F2400.0 E107.915
M73 P97 (display progress)
G1 X-10.98 Y1.2 Z1.33 F2400.0 E107.922
G1 X10.98 Y1.2 Z1.33 F2400.0 E108.32
G1 X10.98 Y1.6 Z1.33 F2400.0 E108.327
G1 X-10.98 Y1.6 Z1.33 F2400.0 E108.724
G1 X-10.98 Y2.0 Z1.33 F2400.0 E108.731
G1 X10.98 Y2.0 Z1.33 F2400.0 E109.129
G1 X10.98 Y2.4 Z1.33 F2400.0 E109.136
G1 X-10.98 Y2.4 Z1.33 F2400.0 E109.533
G1 X-10.98 Y2.8 Z1.33 F2400.0 E109.541
G1 X10.98 Y2.8 Z1.33 F2400.0 E109.938
G1 X10.98 Y3.2 Z1.33 F2400.0 E109.945
G1 X-10.98 Y3.2 Z1.33 F2400.0 E110.343
G1 X-10.98 Y3.6 Z1.33 F2400.0 E110.35
G1 X10.98 Y3.6 Z1.33 F2400.0 E110.747
G1 X10.98 Y4.0 Z1.33 F2400.0 E110.755
G1 X-10.98 Y4.0 Z1.33 F2400.0 E111.152
M73 P98 (display progress)
G1 X-10.98 Y4.4 Z1.33 F2400.0 E111.159
G1 X-9.87 Y4.4 Z1.33 F2400.0 E111.179
G1 X-9.87 Y4.8 Z1.33 F2400.0 E111.187
G1 X-10.98 Y4.8 Z1.33 F2400.0 E111.207
G1 X-10.98 Y5.2 Z1.33 F2400.0 E111.214
G1 X-9.87 Y5.2 Z1.33 F2400.0 E111.234
G1 X-9.96 Y5.6 Z1.33 F2400.0 E111.241
G1 X-10.89 Y5.6 Z1.33 F2400.0 E111.258
G1 F1200.0
G1 E110.258
G1 F2400.0
M103
(</infill>)
(</nestedRing>)
(</rotation>)
(</layer>)
M73 P99 (display progress)
(</crafting>)
M104 S0
;M113 S0.0
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
