(** This GCode was generated by ReplicatorG 0040 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2013/05/24 12:29:19 (-0700) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
M109 S110 T0 (set HBP temperature)
M104 S220 T0 (set extruder temperature) (temp updated by printOMatic)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.6      (Position Height)
M108 R5.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P2000     (Create Anchor)
(**** end of start.gcode ****)
M73 P1 (display progress)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
(<created> 13.05.24|12:29 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.1 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.1 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 999.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.9 </objectFirstLayerFeedRateInfillMultiplier>)
(<operatingFeedRatePerSecond> 40.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.8 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 40.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 55.0 </travelFeedRatePerSecond>)
(<edgeWidth> 0.4 </edgeWidth>)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
M73 P2 (display progress)
(<setting> alteration Activate_Alteration True </setting>)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning False </setting>)
(<setting> cool Turn_Fan_Off_at_Ending False </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.82 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.85 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
M73 P3 (display progress)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 1.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
M73 P4 (display progress)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 0 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular True </setting>)
(<setting> fill Line False </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 1.0 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 60.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
M73 P5 (display progress)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: True </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 1 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 2 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
M73 P6 (display progress)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None False </setting>)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere True </setting>)
(<setting> raft Exterior_Only False </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 40.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 40.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.9 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 999.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 0.5 </setting>)
M73 P7 (display progress)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 0.5 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 55.0 </setting>)
(</settings>)
(<timeStampPreface> 20130524_122917 </timeStampPreface>)
(<procedureName> carve </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
(<crafting>)
;M113 S1.0
;M108 R24.0
(<raftPerimeter>)
(<raftPoint> X4.263 Y5.605 </raftPoint>)
(<raftPoint> X3.699 Y5.94 </raftPoint>)
(<raftPoint> X-3.7 Y5.94 </raftPoint>)
(<raftPoint> X-4.259 Y5.603 </raftPoint>)
M73 P8 (display progress)
(<raftPoint> X-4.259 Y-5.603 </raftPoint>)
(<raftPoint> X-3.7 Y-5.94 </raftPoint>)
(<raftPoint> X3.699 Y-5.94 </raftPoint>)
(<raftPoint> X4.263 Y-5.605 </raftPoint>)
(</raftPerimeter>)
(<raftPerimeter>)
(<raftPoint> X4.263 Y5.605 </raftPoint>)
(<raftPoint> X3.699 Y5.94 </raftPoint>)
(<raftPoint> X-3.7 Y5.94 </raftPoint>)
(<raftPoint> X-4.259 Y5.603 </raftPoint>)
(<raftPoint> X-4.259 Y-5.603 </raftPoint>)
(<raftPoint> X-3.7 Y-5.94 </raftPoint>)
(<raftPoint> X3.699 Y-5.94 </raftPoint>)
(<raftPoint> X4.263 Y-5.605 </raftPoint>)
(</raftPerimeter>)
(<raftPerimeter>)
(<raftPoint> X6.467 Y7.728 </raftPoint>)
(<raftPoint> X-6.467 Y7.728 </raftPoint>)
(<raftPoint> X-6.467 Y-7.728 </raftPoint>)
(<raftPoint> X6.467 Y-7.728 </raftPoint>)
(</raftPerimeter>)
(<layer> 0.176 )
G1 X-5.87 Y-7.29 Z0.18 F3300.0
G1 F1200.0
G1 E1.0
G1 F3300.0
M73 P9 (display progress)
M101
G1 X-5.87 Y7.29 Z0.18 F371.901 E2.021
G1 X-2.93 Y7.29 Z0.18 F371.901 E2.226
G1 X-2.93 Y-7.29 Z0.18 F371.901 E3.247
G1 X0.0 Y-7.29 Z0.18 F371.901 E3.453
G1 X0.0 Y7.29 Z0.18 F371.901 E4.474
G1 X2.93 Y7.29 Z0.18 F371.901 E4.679
G1 X2.93 Y-7.29 Z0.18 F371.901 E5.7
G1 X5.87 Y-7.29 Z0.18 F371.901 E5.905
G1 X5.87 Y7.29 Z0.18 F371.901 E6.926
G1 F1200.0
G1 E5.926
G1 F371.901
M103
;M108 R28.0
(</layer>)
(<layer> 0.364 )
G1 X-5.94 Y0.0 Z0.36 F3300.0
G1 F1200.0
G1 E6.926
G1 F3300.0
M101
G1 X5.94 Y0.0 Z0.36 F1111.111 E7.251
G1 X5.94 Y-1.8 Z0.36 F1111.111 E7.3
G1 X-5.94 Y-1.8 Z0.36 F1111.111 E7.625
M73 P10 (display progress)
G1 X-5.94 Y-3.6 Z0.36 F1111.111 E7.675
G1 X5.94 Y-3.6 Z0.36 F1111.111 E7.999
G1 X5.94 Y-5.4 Z0.36 F1111.111 E8.049
G1 X-5.94 Y-5.4 Z0.36 F1111.111 E8.373
G1 X-5.94 Y-7.2 Z0.36 F1111.111 E8.423
G1 X5.94 Y-7.2 Z0.36 F1111.111 E8.748
G1 F1200.0
G1 E7.748
G1 F1111.111
M103
G1 X5.94 Y1.8 Z0.36 F3300.0
G1 F1200.0
G1 E8.748
G1 F3300.0
M101
G1 X-5.94 Y1.8 Z0.36 F1111.111 E9.072
G1 X-5.94 Y3.6 Z0.36 F1111.111 E9.122
G1 X5.94 Y3.6 Z0.36 F1111.111 E9.447
G1 X5.94 Y5.4 Z0.36 F1111.111 E9.496
G1 X-5.94 Y5.4 Z0.36 F1111.111 E9.821
G1 X-5.94 Y7.2 Z0.36 F1111.111 E9.87
G1 X5.94 Y7.2 Z0.36 F1111.111 E10.195
G1 F1200.0
G1 E9.195
G1 F1111.111
M103
M73 P11 (display progress)
;M108 R28.0
(</layer>)
(<layer> 0.544 )
G1 X-5.94 Y0.0 Z0.54 F3300.0
G1 F1200.0
G1 E10.195
G1 F3300.0
M101
G1 X5.94 Y0.0 Z0.54 F1111.111 E10.52
G1 X5.94 Y-1.8 Z0.54 F1111.111 E10.569
G1 X-5.94 Y-1.8 Z0.54 F1111.111 E10.894
G1 X-5.94 Y-3.6 Z0.54 F1111.111 E10.943
G1 X5.94 Y-3.6 Z0.54 F1111.111 E11.268
G1 X5.94 Y-5.4 Z0.54 F1111.111 E11.317
G1 X-5.94 Y-5.4 Z0.54 F1111.111 E11.642
G1 X-5.94 Y-7.2 Z0.54 F1111.111 E11.691
G1 X5.94 Y-7.2 Z0.54 F1111.111 E12.016
G1 F1200.0
G1 E11.016
G1 F1111.111
M103
G1 X5.94 Y1.8 Z0.54 F3300.0
G1 F1200.0
G1 E12.016
G1 F3300.0
M73 P12 (display progress)
M101
G1 X-5.94 Y1.8 Z0.54 F1111.111 E12.341
G1 X-5.94 Y3.6 Z0.54 F1111.111 E12.39
G1 X5.94 Y3.6 Z0.54 F1111.111 E12.715
G1 X5.94 Y5.4 Z0.54 F1111.111 E12.764
G1 X-5.94 Y5.4 Z0.54 F1111.111 E13.089
G1 X-5.94 Y7.2 Z0.54 F1111.111 E13.138
G1 X5.94 Y7.2 Z0.54 F1111.111 E13.463
G1 F1200.0
G1 E12.463
G1 F1111.111
M103
;M108 R14.05
(</layer>)
(<raftLayerEnd> </raftLayerEnd>)
(<layer> 0.63 )
(<supportLayer>)
G1 X-3.9 Y-5.4 Z0.63 F3300.0
G1 F1200.0
G1 E13.463
G1 F3300.0
M101
G1 X-0.73 Y-5.4 Z0.63 F1355.206 E13.499
G1 F1200.0
G1 E13.04
M73 P13 (display progress)
G1 F1355.206
M103
G1 X0.73 Y-5.4 Z0.63 F3300.0
G1 F1200.0
G1 E13.499
G1 F3300.0
M101
G1 X3.9 Y-5.4 Z0.63 F1355.206 E13.535
G1 X3.9 Y-3.6 Z0.63 F1355.206 E13.555
G1 X0.73 Y-3.6 Z0.63 F1355.206 E13.59
G1 F1200.0
G1 E13.131
G1 F1355.206
M103
G1 X-0.07 Y-3.6 Z0.63 F3300.0
G1 X0.07 Y-3.6 Z0.63 F3300.0
G1 X-0.73 Y-3.6 Z0.63 F3300.0
G1 F1200.0
G1 E13.59
G1 F3300.0
M101
G1 X-3.9 Y-3.6 Z0.63 F1355.206 E13.626
G1 X-3.9 Y-1.8 Z0.63 F1355.206 E13.646
G1 X-0.73 Y-1.8 Z0.63 F1355.206 E13.682
G1 F1200.0
G1 E13.223
M73 P14 (display progress)
G1 F1355.206
M103
G1 X0.07 Y-1.8 Z0.63 F3300.0
G1 X-0.07 Y-1.8 Z0.63 F3300.0
G1 X0.73 Y-1.8 Z0.63 F3300.0
G1 F1200.0
G1 E13.682
G1 F3300.0
M101
G1 X3.9 Y-1.8 Z0.63 F1355.206 E13.718
G1 X3.9 Y0.0 Z0.63 F1355.206 E13.738
G1 X0.73 Y0.0 Z0.63 F1355.206 E13.774
G1 F1200.0
G1 E13.315
G1 F1355.206
M103
G1 X-0.07 Y0.0 Z0.63 F3300.0
G1 X0.07 Y0.0 Z0.63 F3300.0
G1 X-0.73 Y0.0 Z0.63 F3300.0
G1 F1200.0
G1 E13.774
G1 F3300.0
M101
G1 X-3.9 Y0.0 Z0.63 F1355.206 E13.809
G1 X-3.9 Y1.8 Z0.63 F1355.206 E13.83
M73 P15 (display progress)
G1 X-0.73 Y1.8 Z0.63 F1355.206 E13.865
G1 F1200.0
G1 E13.406
G1 F1355.206
M103
G1 X0.07 Y1.8 Z0.63 F3300.0
G1 X-0.07 Y1.8 Z0.63 F3300.0
G1 X0.73 Y1.8 Z0.63 F3300.0
G1 F1200.0
G1 E13.865
G1 F3300.0
M101
G1 X3.9 Y1.8 Z0.63 F1355.206 E13.901
G1 X3.9 Y3.6 Z0.63 F1355.206 E13.921
G1 X0.73 Y3.6 Z0.63 F1355.206 E13.957
G1 F1200.0
G1 E13.498
G1 F1355.206
M103
G1 X-0.07 Y3.6 Z0.63 F3300.0
G1 X0.07 Y3.6 Z0.63 F3300.0
G1 X-0.73 Y3.6 Z0.63 F3300.0
G1 F1200.0
G1 E13.957
G1 F3300.0
M73 P16 (display progress)
M101
G1 X-3.9 Y3.6 Z0.63 F1355.206 E13.993
G1 X-3.9 Y5.4 Z0.63 F1355.206 E14.013
G1 X-0.73 Y5.4 Z0.63 F1355.206 E14.049
G1 F1200.0
G1 E13.59
G1 F1355.206
M103
G1 X0.73 Y5.4 Z0.63 F3300.0
G1 F1200.0
G1 E14.049
G1 F3300.0
M101
G1 X3.9 Y5.4 Z0.63 F1355.206 E14.084
G1 F1200.0
G1 E13.084
G1 F1355.206
M103
;M108 R11.29
(</supportLayer>)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.325 Y-5.291 Z0.63 </boundaryPoint>)
(<boundaryPoint> X0.061 Y-5.31 Z0.63 </boundaryPoint>)
(<boundaryPoint> X0.33 Y-5.261 Z0.63 </boundaryPoint>)
M73 P17 (display progress)
(<boundaryPoint> X0.33 Y5.261 Z0.63 </boundaryPoint>)
(<boundaryPoint> X0.061 Y5.31 Z0.63 </boundaryPoint>)
(<boundaryPoint> X-0.325 Y5.291 Z0.63 </boundaryPoint>)
(<edge> outer )
G1 X-0.13 Y-4.98 Z0.63 F3300.0
G1 F1200.0
G1 E14.084
G1 F3300.0
M101
G1 X-0.13 Y-5.1 Z0.63 F677.603 E14.086
G1 X0.05 Y-5.11 Z0.63 F677.603 E14.09
G1 X0.13 Y-5.09 Z0.63 F677.603 E14.091
G1 X0.13 Y5.09 Z0.63 F677.603 E14.275
G1 X0.05 Y5.11 Z0.63 F677.603 E14.277
G1 X-0.13 Y5.1 Z0.63 F677.603 E14.28
G1 X-0.13 Y-4.98 Z0.63 F677.603 E14.462
G1 F1200.0
G1 E13.462
G1 F677.603
M103
(</edge>)
(</boundaryPerimeter>)
(</nestedRing>)
(</rotation>)
;M108 R19.96
M73 P18 (display progress)
(</layer>)
(<layer> 0.73 )
(<supportLayer>)
G1 X-3.9 Y-5.4 Z0.73 F3300.0
G1 F1200.0
G1 E14.462
G1 F3300.0
M101
G1 X-0.97 Y-5.4 Z0.73 F1711.135 E14.499
G1 X-3.9 Y-3.6 Z0.73 F1711.135 E14.543
G1 X-0.97 Y-3.6 Z0.73 F1711.135 E14.58
G1 X-3.9 Y-1.8 Z0.73 F1711.135 E14.623
G1 X-0.97 Y-1.8 Z0.73 F1711.135 E14.66
G1 X-3.9 Y0.0 Z0.73 F1711.135 E14.704
G1 X-0.97 Y0.0 Z0.73 F1711.135 E14.741
G1 X-3.9 Y1.8 Z0.73 F1711.135 E14.784
G1 X-0.97 Y1.8 Z0.73 F1711.135 E14.822
G1 X-3.9 Y3.6 Z0.73 F1711.135 E14.865
G1 X-0.97 Y3.6 Z0.73 F1711.135 E14.902
G1 X-3.9 Y5.4 Z0.73 F1711.135 E14.946
G1 X-0.97 Y5.4 Z0.73 F1711.135 E14.983
G1 F1200.0
G1 E14.042
G1 F1711.135
M103
G1 X-0.04 Y5.01 Z0.73 F3300.0
M73 P19 (display progress)
G1 X0.06 Y5.01 Z0.73 F3300.0
G1 X0.97 Y5.4 Z0.73 F3300.0
G1 F1200.0
G1 E14.983
G1 F3300.0
M101
G1 X3.9 Y5.4 Z0.73 F1711.135 E15.02
G1 X3.9 Y3.6 Z0.73 F1711.135 E15.043
G1 X0.97 Y3.6 Z0.73 F1711.135 E15.08
G1 X3.9 Y1.8 Z0.73 F1711.135 E15.123
G1 X0.97 Y1.8 Z0.73 F1711.135 E15.16
G1 X3.9 Y0.0 Z0.73 F1711.135 E15.204
G1 X0.97 Y0.0 Z0.73 F1711.135 E15.241
G1 X3.9 Y-1.8 Z0.73 F1711.135 E15.285
G1 X0.97 Y-1.8 Z0.73 F1711.135 E15.322
G1 X3.9 Y-3.6 Z0.73 F1711.135 E15.365
G1 X0.97 Y-3.6 Z0.73 F1711.135 E15.403
G1 X3.9 Y-5.4 Z0.73 F1711.135 E15.446
G1 X0.97 Y-5.4 Z0.73 F1711.135 E15.483
G1 F1200.0
G1 E14.483
G1 F1711.135
M103
;M108 R14.26
(</supportLayer>)
M73 P20 (display progress)
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.57 Y-5.28 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-0.14 Y-5.403 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.081 Y-5.408 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.289 Y-5.371 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.567 Y-5.261 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.567 Y5.261 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.289 Y5.371 Z0.73 </boundaryPoint>)
(<boundaryPoint> X0.081 Y5.408 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-0.14 Y5.403 Z0.73 </boundaryPoint>)
(<boundaryPoint> X-0.57 Y5.28 Z0.73 </boundaryPoint>)
(<edge> outer )
G1 X-0.37 Y-4.7 Z0.73 F3300.0
G1 F1200.0
G1 E15.483
G1 F3300.0
M101
G1 X-0.37 Y-5.13 Z0.73 F855.567 E15.491
G1 X-0.11 Y-5.2 Z0.73 F855.567 E15.496
G1 X0.07 Y-5.21 Z0.73 F855.567 E15.499
G1 X0.23 Y-5.18 Z0.73 F855.567 E15.502
G1 X0.37 Y-5.13 Z0.73 F855.567 E15.505
G1 X0.37 Y5.13 Z0.73 F855.567 E15.69
M73 P21 (display progress)
G1 X0.23 Y5.18 Z0.73 F855.567 E15.693
G1 X0.07 Y5.21 Z0.73 F855.567 E15.696
G1 X-0.11 Y5.2 Z0.73 F855.567 E15.699
G1 X-0.37 Y5.13 Z0.73 F855.567 E15.704
G1 X-0.37 Y-4.7 Z0.73 F855.567 E15.882
G1 F1200.0
G1 E15.882
G1 F855.567
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.37 Y-5.129 Z0.15 </infillPoint>)
(<infillPoint> X-0.11 Y-5.204 Z0.15 </infillPoint>)
(<infillPoint> X0.066 Y-5.208 Z0.15 </infillPoint>)
(<infillPoint> X0.234 Y-5.178 Z0.15 </infillPoint>)
(<infillPoint> X0.367 Y-5.125 Z0.15 </infillPoint>)
(<infillPoint> X0.367 Y5.125 Z0.15 </infillPoint>)
(<infillPoint> X0.234 Y5.178 Z0.15 </infillPoint>)
(<infillPoint> X0.066 Y5.208 Z0.15 </infillPoint>)
(<infillPoint> X-0.11 Y5.204 Z0.15 </infillPoint>)
(<infillPoint> X-0.37 Y5.129 Z0.15 </infillPoint>)
(</infillBoundary>)
;M108 R28.52
G1 X-0.01 Y-4.8 Z0.73 F3300.0
M73 P22 (display progress)
G1 F1200.0
G1 E15.882
G1 F3300.0
M101
G1 X0.06 Y-4.8 Z0.73 F1711.135 E15.883
G1 X0.09 Y-4.4 Z0.73 F1711.135 E15.89
G1 X-0.09 Y-4.4 Z0.73 F1711.135 E15.894
G1 X-0.09 Y-4.0 Z0.73 F1711.135 E15.901
G1 X0.09 Y-4.0 Z0.73 F1711.135 E15.904
G1 X0.09 Y-3.6 Z0.73 F1711.135 E15.911
G1 X-0.09 Y-3.6 Z0.73 F1711.135 E15.914
G1 X-0.09 Y-3.2 Z0.73 F1711.135 E15.922
G1 X0.09 Y-3.2 Z0.73 F1711.135 E15.925
G1 X0.09 Y-2.8 Z0.73 F1711.135 E15.932
G1 X-0.09 Y-2.8 Z0.73 F1711.135 E15.935
G1 X-0.09 Y-2.4 Z0.73 F1711.135 E15.943
G1 X0.09 Y-2.4 Z0.73 F1711.135 E15.946
G1 X0.09 Y-2.0 Z0.73 F1711.135 E15.953
G1 X-0.09 Y-2.0 Z0.73 F1711.135 E15.956
G1 X-0.09 Y-1.6 Z0.73 F1711.135 E15.963
G1 X0.09 Y-1.6 Z0.73 F1711.135 E15.967
G1 X0.09 Y-1.2 Z0.73 F1711.135 E15.974
G1 X-0.09 Y-1.2 Z0.73 F1711.135 E15.977
G1 X-0.09 Y-0.8 Z0.73 F1711.135 E15.984
G1 X0.09 Y-0.8 Z0.73 F1711.135 E15.987
M73 P23 (display progress)
G1 X0.09 Y-0.4 Z0.73 F1711.135 E15.995
G1 X-0.09 Y-0.4 Z0.73 F1711.135 E15.998
G1 X-0.09 Y0.0 Z0.73 F1711.135 E16.005
G1 X0.09 Y-0.0 Z0.73 F1711.135 E16.008
G1 X-0.09 Y0.4 Z0.73 F1711.135 E16.016
G1 X0.09 Y0.4 Z0.73 F1711.135 E16.019
G1 X0.09 Y0.8 Z0.73 F1711.135 E16.027
G1 X-0.09 Y0.8 Z0.73 F1711.135 E16.03
G1 X-0.09 Y1.2 Z0.73 F1711.135 E16.037
G1 X0.09 Y1.2 Z0.73 F1711.135 E16.04
G1 X0.09 Y1.6 Z0.73 F1711.135 E16.048
G1 X-0.09 Y1.6 Z0.73 F1711.135 E16.051
G1 X-0.09 Y2.0 Z0.73 F1711.135 E16.058
G1 X0.09 Y2.0 Z0.73 F1711.135 E16.061
G1 X0.09 Y2.4 Z0.73 F1711.135 E16.068
G1 X-0.09 Y2.4 Z0.73 F1711.135 E16.072
G1 X-0.09 Y2.8 Z0.73 F1711.135 E16.079
G1 X0.09 Y2.8 Z0.73 F1711.135 E16.082
G1 X0.09 Y3.2 Z0.73 F1711.135 E16.089
G1 X-0.09 Y3.2 Z0.73 F1711.135 E16.093
G1 X-0.09 Y3.6 Z0.73 F1711.135 E16.1
G1 X0.09 Y3.6 Z0.73 F1711.135 E16.103
G1 X0.09 Y4.0 Z0.73 F1711.135 E16.11
G1 X-0.09 Y4.0 Z0.73 F1711.135 E16.113
G1 X-0.09 Y4.4 Z0.73 F1711.135 E16.121
M73 P24 (display progress)
G1 X0.09 Y4.4 Z0.73 F1711.135 E16.124
G1 X0.06 Y4.8 Z0.73 F1711.135 E16.131
G1 X-0.01 Y4.8 Z0.73 F1711.135 E16.132
G1 F1200.0
G1 E15.132
G1 F1711.135
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.782
(</layer>)
(<layer> 0.83 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.102 Y-5.506 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.102 Y-5.506 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.385 Y-5.435 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.723 Y-5.261 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.723 Y5.271 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.302 Y5.463 Z0.83 </boundaryPoint>)
(<boundaryPoint> X0.102 Y5.506 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-0.102 Y5.506 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-0.324 Y5.457 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-0.719 Y5.277 Z0.83 </boundaryPoint>)
M73 P25 (display progress)
(<boundaryPoint> X-0.719 Y-5.277 Z0.83 </boundaryPoint>)
(<boundaryPoint> X-0.324 Y-5.457 Z0.83 </boundaryPoint>)
(<edge> outer )
G1 X-0.46 Y-5.18 Z0.83 F3300.0
G1 F1200.0
G1 E16.132
G1 F3300.0
M101
G1 X-0.26 Y-5.27 Z0.83 F346.939 E16.136
G1 X-0.08 Y-5.31 Z0.83 F346.939 E16.14
G1 X0.08 Y-5.31 Z0.83 F346.939 E16.142
G1 X0.31 Y-5.25 Z0.83 F346.939 E16.147
G1 X0.52 Y-5.14 Z0.83 F346.939 E16.151
G1 X0.52 Y5.14 Z0.83 F346.939 E16.337
G1 X0.24 Y5.27 Z0.83 F346.939 E16.343
G1 X0.08 Y5.31 Z0.83 F346.939 E16.346
G1 X-0.08 Y5.31 Z0.83 F346.939 E16.349
G1 X-0.26 Y5.27 Z0.83 F346.939 E16.352
G1 X-0.52 Y5.15 Z0.83 F346.939 E16.357
G1 X-0.52 Y-5.15 Z0.83 F346.939 E16.543
G1 X-0.46 Y-5.18 Z0.83 F346.939 E16.545
G1 F1200.0
G1 E16.545
G1 F346.939
M103
M73 P26 (display progress)
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.08 Y-5.306 Z0.25 </infillPoint>)
(<infillPoint> X0.077 Y-5.306 Z0.25 </infillPoint>)
(<infillPoint> X0.314 Y-5.247 Z0.25 </infillPoint>)
(<infillPoint> X0.523 Y-5.139 Z0.25 </infillPoint>)
(<infillPoint> X0.523 Y5.142 Z0.25 </infillPoint>)
(<infillPoint> X0.239 Y5.272 Z0.25 </infillPoint>)
(<infillPoint> X0.081 Y5.306 Z0.25 </infillPoint>)
(<infillPoint> X-0.08 Y5.306 Z0.25 </infillPoint>)
(<infillPoint> X-0.26 Y5.266 Z0.25 </infillPoint>)
(<infillPoint> X-0.519 Y5.148 Z0.25 </infillPoint>)
(<infillPoint> X-0.519 Y-5.148 Z0.25 </infillPoint>)
(<infillPoint> X-0.26 Y-5.266 Z0.25 </infillPoint>)
(</infillBoundary>)
;M108 R11.56
G1 X-0.0 Y-5.03 Z0.83 F3300.0
G1 F1200.0
G1 E16.545
G1 F3300.0
M101
G1 X0.0 Y5.02 Z0.83 F693.879 E16.726
G1 F1200.0
M73 P27 (display progress)
G1 E15.726
G1 F693.879
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R7.95
(</layer>)
(<layer> 0.93 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.835 Y-5.261 Z0.93 </boundaryPoint>)
(<boundaryPoint> X0.835 Y5.261 Z0.93 </boundaryPoint>)
(<boundaryPoint> X0.572 Y5.434 Z0.93 </boundaryPoint>)
(<boundaryPoint> X0.308 Y5.556 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.302 Y5.556 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.504 Y5.471 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.835 Y5.261 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.835 Y-5.261 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.504 Y-5.471 Z0.93 </boundaryPoint>)
(<boundaryPoint> X-0.302 Y-5.556 Z0.93 </boundaryPoint>)
(<boundaryPoint> X0.308 Y-5.556 Z0.93 </boundaryPoint>)
(<boundaryPoint> X0.572 Y-5.434 Z0.93 </boundaryPoint>)
(<edge> outer )
G1 X-0.64 Y-4.91 Z0.93 F3300.0
M73 P28 (display progress)
G1 F1200.0
G1 E16.726
G1 F3300.0
M101
G1 X-0.64 Y-5.15 Z0.93 F477.026 E16.731
G1 X-0.41 Y-5.29 Z0.93 F477.026 E16.735
G1 X-0.26 Y-5.36 Z0.93 F477.026 E16.738
G1 X0.26 Y-5.36 Z0.93 F477.026 E16.748
G1 X0.47 Y-5.26 Z0.93 F477.026 E16.752
G1 X0.64 Y-5.15 Z0.93 F477.026 E16.755
G1 X0.64 Y5.15 Z0.93 F477.026 E16.942
G1 X0.47 Y5.26 Z0.93 F477.026 E16.945
G1 X0.26 Y5.36 Z0.93 F477.026 E16.95
G1 X-0.26 Y5.36 Z0.93 F477.026 E16.959
G1 X-0.41 Y5.29 Z0.93 F477.026 E16.962
G1 X-0.64 Y5.15 Z0.93 F477.026 E16.967
G1 X-0.64 Y-4.91 Z0.93 F477.026 E17.149
G1 F1200.0
G1 E16.149
G1 F477.026
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
M73 P29 (display progress)
(<infillPoint> X0.635 Y-5.153 Z0.35 </infillPoint>)
(<infillPoint> X0.635 Y5.153 Z0.35 </infillPoint>)
(<infillPoint> X0.475 Y5.259 Z0.35 </infillPoint>)
(<infillPoint> X0.264 Y5.356 Z0.35 </infillPoint>)
(<infillPoint> X-0.262 Y5.356 Z0.35 </infillPoint>)
(<infillPoint> X-0.411 Y5.293 Z0.35 </infillPoint>)
(<infillPoint> X-0.635 Y5.151 Z0.35 </infillPoint>)
(<infillPoint> X-0.635 Y-5.151 Z0.35 </infillPoint>)
(<infillPoint> X-0.411 Y-5.293 Z0.35 </infillPoint>)
(<infillPoint> X-0.262 Y-5.356 Z0.35 </infillPoint>)
(<infillPoint> X0.264 Y-5.356 Z0.35 </infillPoint>)
(<infillPoint> X0.475 Y-5.259 Z0.35 </infillPoint>)
(</infillBoundary>)
;M108 R15.9
G1 X0.35 Y-0.0 Z0.93 F3300.0
G1 F1200.0
G1 E17.149
G1 F3300.0
M101
G1 X-0.35 Y0.0 Z0.93 F954.051 E17.162
G1 X-0.35 Y-0.4 Z0.93 F954.051 E17.169
G1 X0.35 Y-0.4 Z0.93 F954.051 E17.182
G1 X0.35 Y-0.8 Z0.93 F954.051 E17.189
G1 X-0.35 Y-0.8 Z0.93 F954.051 E17.202
G1 X-0.35 Y-1.2 Z0.93 F954.051 E17.209
G1 X0.35 Y-1.2 Z0.93 F954.051 E17.222
M73 P30 (display progress)
G1 X0.35 Y-1.6 Z0.93 F954.051 E17.229
G1 X-0.35 Y-1.6 Z0.93 F954.051 E17.242
G1 X-0.35 Y-2.0 Z0.93 F954.051 E17.249
G1 X0.35 Y-2.0 Z0.93 F954.051 E17.262
G1 X0.35 Y-2.4 Z0.93 F954.051 E17.269
G1 X-0.35 Y-2.4 Z0.93 F954.051 E17.282
G1 X-0.35 Y-2.8 Z0.93 F954.051 E17.289
G1 X0.35 Y-2.8 Z0.93 F954.051 E17.302
G1 X0.35 Y-3.2 Z0.93 F954.051 E17.309
G1 X-0.35 Y-3.2 Z0.93 F954.051 E17.322
G1 X-0.35 Y-3.6 Z0.93 F954.051 E17.329
G1 X0.35 Y-3.6 Z0.93 F954.051 E17.342
G1 X0.35 Y-4.0 Z0.93 F954.051 E17.35
G1 X-0.35 Y-4.0 Z0.93 F954.051 E17.362
G1 X-0.35 Y-4.4 Z0.93 F954.051 E17.37
G1 X0.35 Y-4.4 Z0.93 F954.051 E17.382
G1 X0.35 Y-4.8 Z0.93 F954.051 E17.39
G1 X-0.35 Y-4.8 Z0.93 F954.051 E17.403
G1 F1200.0
G1 E16.403
G1 F954.051
M103
G1 X-0.35 Y0.4 Z0.93 F3300.0
G1 F1200.0
G1 E17.403
M73 P31 (display progress)
G1 F3300.0
M101
G1 X0.35 Y0.4 Z0.93 F954.051 E17.415
G1 X0.35 Y0.8 Z0.93 F954.051 E17.423
G1 X-0.35 Y0.8 Z0.93 F954.051 E17.435
G1 X-0.35 Y1.2 Z0.93 F954.051 E17.443
G1 X0.35 Y1.2 Z0.93 F954.051 E17.456
G1 X0.35 Y1.6 Z0.93 F954.051 E17.463
G1 X-0.35 Y1.6 Z0.93 F954.051 E17.476
G1 X-0.35 Y2.0 Z0.93 F954.051 E17.483
G1 X0.35 Y2.0 Z0.93 F954.051 E17.496
G1 X0.35 Y2.4 Z0.93 F954.051 E17.503
G1 X-0.35 Y2.4 Z0.93 F954.051 E17.516
G1 X-0.35 Y2.8 Z0.93 F954.051 E17.523
G1 X0.35 Y2.8 Z0.93 F954.051 E17.536
G1 X0.35 Y3.2 Z0.93 F954.051 E17.543
G1 X-0.35 Y3.2 Z0.93 F954.051 E17.556
G1 X-0.35 Y3.6 Z0.93 F954.051 E17.563
G1 X0.35 Y3.6 Z0.93 F954.051 E17.576
G1 X0.35 Y4.0 Z0.93 F954.051 E17.583
G1 X-0.35 Y4.0 Z0.93 F954.051 E17.596
G1 X-0.35 Y4.4 Z0.93 F954.051 E17.603
G1 X0.35 Y4.4 Z0.93 F954.051 E17.616
G1 X0.35 Y4.8 Z0.93 F954.051 E17.623
G1 X-0.35 Y4.8 Z0.93 F954.051 E17.636
M73 P32 (display progress)
G1 F1200.0
G1 E16.636
G1 F954.051
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.194
(</layer>)
(<layer> 1.03 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.922 Y5.261 Z1.03 </boundaryPoint>)
(<boundaryPoint> X0.498 Y5.556 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-0.495 Y5.556 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-0.924 Y5.261 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-0.924 Y-5.261 Z1.03 </boundaryPoint>)
(<boundaryPoint> X-0.495 Y-5.556 Z1.03 </boundaryPoint>)
(<boundaryPoint> X0.498 Y-5.556 Z1.03 </boundaryPoint>)
(<boundaryPoint> X0.922 Y-5.261 Z1.03 </boundaryPoint>)
(<edge> outer )
G1 X-0.51 Y-5.3 Z1.03 F3300.0
G1 F1200.0
G1 E17.636
G1 F3300.0
M73 P33 (display progress)
M101
G1 X-0.43 Y-5.36 Z1.03 F491.63 E17.638
G1 X0.43 Y-5.36 Z1.03 F491.63 E17.654
G1 X0.72 Y-5.16 Z1.03 F491.63 E17.66
G1 X0.72 Y5.16 Z1.03 F491.63 E17.847
G1 X0.43 Y5.36 Z1.03 F491.63 E17.853
G1 X-0.43 Y5.36 Z1.03 F491.63 E17.869
G1 X-0.72 Y5.16 Z1.03 F491.63 E17.875
G1 X-0.72 Y-5.16 Z1.03 F491.63 E18.062
G1 X-0.51 Y-5.3 Z1.03 F491.63 E18.066
G1 F1200.0
G1 E18.066
G1 F491.63
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.722 Y5.157 Z0.45 </infillPoint>)
(<infillPoint> X0.435 Y5.356 Z0.45 </infillPoint>)
(<infillPoint> X-0.433 Y5.356 Z0.45 </infillPoint>)
(<infillPoint> X-0.724 Y5.156 Z0.45 </infillPoint>)
(<infillPoint> X-0.724 Y-5.156 Z0.45 </infillPoint>)
(<infillPoint> X-0.433 Y-5.356 Z0.45 </infillPoint>)
(<infillPoint> X0.435 Y-5.356 Z0.45 </infillPoint>)
M73 P34 (display progress)
(<infillPoint> X0.722 Y-5.157 Z0.45 </infillPoint>)
(</infillBoundary>)
;M108 R16.39
G1 X0.4 Y-5.04 Z1.03 F3300.0
G1 F1200.0
G1 E18.066
G1 F3300.0
M101
G1 X0.4 Y5.04 Z1.03 F983.259 E18.248
G1 X0.0 Y5.08 Z1.03 F983.259 E18.256
G1 X-0.0 Y-5.08 Z1.03 F983.259 E18.439
G1 X-0.4 Y-5.04 Z1.03 F983.259 E18.447
G1 X-0.4 Y5.04 Z1.03 F983.259 E18.629
G1 F1200.0
G1 E17.629
G1 F983.259
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.99
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
(<layer> 1.13 )
(<rotation> (-1+1.22464679915e-16j) )
M73 P35 (display progress)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.997 Y5.261 Z1.13 </boundaryPoint>)
(<boundaryPoint> X0.62 Y5.556 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-0.622 Y5.556 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-0.993 Y5.261 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-0.993 Y-5.261 Z1.13 </boundaryPoint>)
(<boundaryPoint> X-0.622 Y-5.556 Z1.13 </boundaryPoint>)
(<boundaryPoint> X0.62 Y-5.556 Z1.13 </boundaryPoint>)
(<boundaryPoint> X0.997 Y-5.261 Z1.13 </boundaryPoint>)
(<edge> outer )
G1 X-0.79 Y-5.12 Z1.13 F3300.0
G1 F1200.0
G1 E18.629
G1 F3300.0
M101
G1 X-0.79 Y-5.17 Z1.13 F539.428 E18.63
G1 X-0.55 Y-5.36 Z1.13 F539.428 E18.635
G1 X0.55 Y-5.36 Z1.13 F539.428 E18.655
G1 X0.8 Y-5.16 Z1.13 F539.428 E18.661
G1 X0.8 Y5.16 Z1.13 F539.428 E18.848
G1 X0.55 Y5.36 Z1.13 F539.428 E18.854
G1 X-0.55 Y5.36 Z1.13 F539.428 E18.873
G1 X-0.79 Y5.17 Z1.13 F539.428 E18.879
G1 X-0.79 Y-5.12 Z1.13 F539.428 E19.065
G1 F1200.0
M73 P36 (display progress)
G1 E18.065
G1 F539.428
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.797 Y5.164 Z0.55 </infillPoint>)
(<infillPoint> X0.551 Y5.356 Z0.55 </infillPoint>)
(<infillPoint> X-0.552 Y5.356 Z0.55 </infillPoint>)
(<infillPoint> X-0.793 Y5.165 Z0.55 </infillPoint>)
(<infillPoint> X-0.793 Y-5.165 Z0.55 </infillPoint>)
(<infillPoint> X-0.552 Y-5.356 Z0.55 </infillPoint>)
(<infillPoint> X0.551 Y-5.356 Z0.55 </infillPoint>)
(<infillPoint> X0.797 Y-5.164 Z0.55 </infillPoint>)
(</infillBoundary>)
;M108 R17.98
G1 X0.52 Y-0.0 Z1.13 F3300.0
G1 F1200.0
G1 E19.065
G1 F3300.0
M101
G1 X-0.51 Y0.0 Z1.13 F1078.857 E19.084
G1 X-0.51 Y-0.4 Z1.13 F1078.857 E19.091
G1 X0.52 Y-0.4 Z1.13 F1078.857 E19.109
M73 P37 (display progress)
G1 X0.52 Y-0.8 Z1.13 F1078.857 E19.117
G1 X-0.51 Y-0.8 Z1.13 F1078.857 E19.135
G1 X-0.51 Y-1.2 Z1.13 F1078.857 E19.143
G1 X0.52 Y-1.2 Z1.13 F1078.857 E19.161
G1 X0.52 Y-1.6 Z1.13 F1078.857 E19.168
G1 X-0.51 Y-1.6 Z1.13 F1078.857 E19.187
G1 X-0.51 Y-2.0 Z1.13 F1078.857 E19.194
G1 X0.52 Y-2.0 Z1.13 F1078.857 E19.213
G1 X0.52 Y-2.4 Z1.13 F1078.857 E19.22
G1 X-0.51 Y-2.4 Z1.13 F1078.857 E19.239
G1 X-0.51 Y-2.8 Z1.13 F1078.857 E19.246
G1 X0.52 Y-2.8 Z1.13 F1078.857 E19.265
G1 X0.52 Y-3.2 Z1.13 F1078.857 E19.272
G1 X-0.51 Y-3.2 Z1.13 F1078.857 E19.291
G1 X-0.51 Y-3.6 Z1.13 F1078.857 E19.298
G1 X0.52 Y-3.6 Z1.13 F1078.857 E19.316
G1 X0.52 Y-4.0 Z1.13 F1078.857 E19.324
G1 X-0.51 Y-4.0 Z1.13 F1078.857 E19.342
G1 X-0.51 Y-4.4 Z1.13 F1078.857 E19.349
G1 X0.52 Y-4.4 Z1.13 F1078.857 E19.368
G1 X0.52 Y-4.8 Z1.13 F1078.857 E19.375
G1 X-0.51 Y-4.8 Z1.13 F1078.857 E19.394
G1 F1200.0
G1 E18.394
G1 F1078.857
M103
M73 P38 (display progress)
G1 X-0.51 Y0.4 Z1.13 F3300.0
G1 F1200.0
G1 E19.394
G1 F3300.0
M101
G1 X0.52 Y0.4 Z1.13 F1078.857 E19.413
G1 X0.52 Y0.8 Z1.13 F1078.857 E19.42
G1 X-0.51 Y0.8 Z1.13 F1078.857 E19.438
G1 X-0.51 Y1.2 Z1.13 F1078.857 E19.446
G1 X0.52 Y1.2 Z1.13 F1078.857 E19.464
G1 X0.52 Y1.6 Z1.13 F1078.857 E19.472
G1 X-0.51 Y1.6 Z1.13 F1078.857 E19.49
G1 X-0.51 Y2.0 Z1.13 F1078.857 E19.497
G1 X0.52 Y2.0 Z1.13 F1078.857 E19.516
G1 X0.52 Y2.4 Z1.13 F1078.857 E19.523
G1 X-0.51 Y2.4 Z1.13 F1078.857 E19.542
G1 X-0.51 Y2.8 Z1.13 F1078.857 E19.549
G1 X0.52 Y2.8 Z1.13 F1078.857 E19.568
G1 X0.52 Y3.2 Z1.13 F1078.857 E19.575
G1 X-0.51 Y3.2 Z1.13 F1078.857 E19.594
G1 X-0.51 Y3.6 Z1.13 F1078.857 E19.601
G1 X0.52 Y3.6 Z1.13 F1078.857 E19.62
G1 X0.52 Y4.0 Z1.13 F1078.857 E19.627
G1 X-0.51 Y4.0 Z1.13 F1078.857 E19.645
G1 X-0.51 Y4.4 Z1.13 F1078.857 E19.653
M73 P39 (display progress)
G1 X0.52 Y4.4 Z1.13 F1078.857 E19.671
G1 X0.52 Y4.8 Z1.13 F1078.857 E19.679
G1 X-0.51 Y4.8 Z1.13 F1078.857 E19.697
G1 F1200.0
G1 E18.697
G1 F1078.857
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.302
(</layer>)
(<layer> 1.23 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.052 Y-5.261 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-0.704 Y-5.556 Z1.23 </boundaryPoint>)
(<boundaryPoint> X0.703 Y-5.556 Z1.23 </boundaryPoint>)
(<boundaryPoint> X1.049 Y-5.261 Z1.23 </boundaryPoint>)
(<boundaryPoint> X1.049 Y5.261 Z1.23 </boundaryPoint>)
(<boundaryPoint> X0.703 Y5.556 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-0.704 Y5.556 Z1.23 </boundaryPoint>)
(<boundaryPoint> X-1.052 Y5.261 Z1.23 </boundaryPoint>)
(<edge> outer )
M73 P40 (display progress)
G1 X-0.85 Y-4.81 Z1.23 F3300.0
G1 F1200.0
G1 E19.697
G1 F3300.0
M101
G1 X-0.85 Y-5.17 Z1.23 F498.128 E19.704
G1 X-0.63 Y-5.36 Z1.23 F498.128 E19.709
G1 X0.63 Y-5.36 Z1.23 F498.128 E19.732
G1 X0.85 Y-5.17 Z1.23 F498.128 E19.737
G1 X0.85 Y5.17 Z1.23 F498.128 E19.924
G1 X0.63 Y5.36 Z1.23 F498.128 E19.929
G1 X-0.63 Y5.36 Z1.23 F498.128 E19.952
G1 X-0.85 Y5.17 Z1.23 F498.128 E19.957
G1 X-0.85 Y-4.81 Z1.23 F498.128 E20.138
G1 F1200.0
G1 E20.138
G1 F498.128
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.852 Y-5.168 Z0.65 </infillPoint>)
(<infillPoint> X-0.631 Y-5.356 Z0.65 </infillPoint>)
(<infillPoint> X0.629 Y-5.356 Z0.65 </infillPoint>)
(<infillPoint> X0.849 Y-5.169 Z0.65 </infillPoint>)
M73 P41 (display progress)
(<infillPoint> X0.849 Y5.169 Z0.65 </infillPoint>)
(<infillPoint> X0.629 Y5.356 Z0.65 </infillPoint>)
(<infillPoint> X-0.631 Y5.356 Z0.65 </infillPoint>)
(<infillPoint> X-0.852 Y5.168 Z0.65 </infillPoint>)
(</infillBoundary>)
;M108 R16.6
G1 X-0.4 Y-5.08 Z1.23 F3300.0
G1 F1200.0
G1 E20.138
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z1.23 F996.256 E20.321
G1 X0.0 Y5.08 Z1.23 F996.256 E20.328
G1 X-0.0 Y-5.08 Z1.23 F996.256 E20.512
G1 X0.4 Y-5.08 Z1.23 F996.256 E20.519
G1 X0.4 Y5.08 Z1.23 F996.256 E20.703
G1 F1200.0
G1 E19.703
G1 F996.256
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R9.65
(</layer>)
M73 P42 (display progress)
(<layer> 1.33 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.095 Y-5.261 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-0.769 Y-5.556 Z1.33 </boundaryPoint>)
(<boundaryPoint> X0.771 Y-5.556 Z1.33 </boundaryPoint>)
(<boundaryPoint> X1.097 Y-5.261 Z1.33 </boundaryPoint>)
(<boundaryPoint> X1.097 Y5.261 Z1.33 </boundaryPoint>)
(<boundaryPoint> X0.771 Y5.556 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-0.769 Y5.556 Z1.33 </boundaryPoint>)
(<boundaryPoint> X-1.095 Y5.261 Z1.33 </boundaryPoint>)
(<edge> outer )
G1 X-0.79 Y-5.26 Z1.33 F3300.0
G1 F1200.0
G1 E20.703
G1 F3300.0
M101
G1 X-0.69 Y-5.36 Z1.33 F579.013 E20.705
G1 X0.69 Y-5.36 Z1.33 F579.013 E20.73
G1 X0.9 Y-5.17 Z1.33 F579.013 E20.735
G1 X0.9 Y5.17 Z1.33 F579.013 E20.922
G1 X0.69 Y5.36 Z1.33 F579.013 E20.927
G1 X-0.69 Y5.36 Z1.33 F579.013 E20.952
G1 X-0.9 Y5.17 Z1.33 F579.013 E20.957
M73 P43 (display progress)
G1 X-0.9 Y-5.17 Z1.33 F579.013 E21.145
G1 X-0.79 Y-5.26 Z1.33 F579.013 E21.147
G1 F1200.0
G1 E20.147
G1 F579.013
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.895 Y-5.172 Z0.75 </infillPoint>)
(<infillPoint> X-0.692 Y-5.356 Z0.75 </infillPoint>)
(<infillPoint> X0.694 Y-5.356 Z0.75 </infillPoint>)
(<infillPoint> X0.897 Y-5.172 Z0.75 </infillPoint>)
(<infillPoint> X0.897 Y5.172 Z0.75 </infillPoint>)
(<infillPoint> X0.694 Y5.356 Z0.75 </infillPoint>)
(<infillPoint> X-0.692 Y5.356 Z0.75 </infillPoint>)
(<infillPoint> X-0.895 Y5.172 Z0.75 </infillPoint>)
(</infillBoundary>)
;M108 R19.3
G1 X0.62 Y-0.0 Z1.33 F3300.0
G1 F1200.0
G1 E21.147
G1 F3300.0
M101
G1 X-0.61 Y0.0 Z1.33 F1158.027 E21.169
M73 P44 (display progress)
G1 X-0.61 Y-0.4 Z1.33 F1158.027 E21.177
G1 X0.62 Y-0.4 Z1.33 F1158.027 E21.199
G1 X0.62 Y-0.8 Z1.33 F1158.027 E21.206
G1 X-0.61 Y-0.8 Z1.33 F1158.027 E21.228
G1 X-0.61 Y-1.2 Z1.33 F1158.027 E21.236
G1 X0.62 Y-1.2 Z1.33 F1158.027 E21.258
G1 X0.62 Y-1.6 Z1.33 F1158.027 E21.265
G1 X-0.61 Y-1.6 Z1.33 F1158.027 E21.287
G1 X-0.61 Y-2.0 Z1.33 F1158.027 E21.295
G1 X0.62 Y-2.0 Z1.33 F1158.027 E21.317
G1 X0.62 Y-2.4 Z1.33 F1158.027 E21.324
G1 X-0.61 Y-2.4 Z1.33 F1158.027 E21.346
G1 X-0.61 Y-2.8 Z1.33 F1158.027 E21.354
G1 X0.62 Y-2.8 Z1.33 F1158.027 E21.376
G1 X0.62 Y-3.2 Z1.33 F1158.027 E21.383
G1 X-0.61 Y-3.2 Z1.33 F1158.027 E21.405
G1 X-0.61 Y-3.6 Z1.33 F1158.027 E21.413
G1 X0.62 Y-3.6 Z1.33 F1158.027 E21.435
G1 X0.62 Y-4.0 Z1.33 F1158.027 E21.442
G1 X-0.61 Y-4.0 Z1.33 F1158.027 E21.465
G1 X-0.61 Y-4.4 Z1.33 F1158.027 E21.472
G1 X0.62 Y-4.4 Z1.33 F1158.027 E21.494
G1 X0.62 Y-4.8 Z1.33 F1158.027 E21.501
G1 X-0.61 Y-4.8 Z1.33 F1158.027 E21.524
G1 F1200.0
M73 P45 (display progress)
G1 E20.524
G1 F1158.027
M103
G1 X-0.61 Y0.4 Z1.33 F3300.0
G1 F1200.0
G1 E21.524
G1 F3300.0
M101
G1 X0.62 Y0.4 Z1.33 F1158.027 E21.546
G1 X0.62 Y0.8 Z1.33 F1158.027 E21.553
G1 X-0.61 Y0.8 Z1.33 F1158.027 E21.575
G1 X-0.61 Y1.2 Z1.33 F1158.027 E21.583
G1 X0.62 Y1.2 Z1.33 F1158.027 E21.605
G1 X0.62 Y1.6 Z1.33 F1158.027 E21.612
G1 X-0.61 Y1.6 Z1.33 F1158.027 E21.634
G1 X-0.61 Y2.0 Z1.33 F1158.027 E21.642
G1 X0.62 Y2.0 Z1.33 F1158.027 E21.664
G1 X0.62 Y2.4 Z1.33 F1158.027 E21.671
G1 X-0.61 Y2.4 Z1.33 F1158.027 E21.693
G1 X-0.61 Y2.8 Z1.33 F1158.027 E21.701
G1 X0.62 Y2.8 Z1.33 F1158.027 E21.723
G1 X0.62 Y3.2 Z1.33 F1158.027 E21.73
G1 X-0.61 Y3.2 Z1.33 F1158.027 E21.752
G1 X-0.61 Y3.6 Z1.33 F1158.027 E21.76
G1 X0.62 Y3.6 Z1.33 F1158.027 E21.782
G1 X0.62 Y4.0 Z1.33 F1158.027 E21.789
M73 P46 (display progress)
G1 X-0.61 Y4.0 Z1.33 F1158.027 E21.812
G1 X-0.61 Y4.4 Z1.33 F1158.027 E21.819
G1 X0.62 Y4.4 Z1.33 F1158.027 E21.841
G1 X0.62 Y4.8 Z1.33 F1158.027 E21.848
G1 X-0.61 Y4.8 Z1.33 F1158.027 E21.871
G1 F1200.0
G1 E20.871
G1 F1158.027
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.382
(</layer>)
(<layer> 1.43 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.13 Y-5.261 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-0.819 Y-5.556 Z1.43 </boundaryPoint>)
(<boundaryPoint> X0.817 Y-5.556 Z1.43 </boundaryPoint>)
(<boundaryPoint> X1.129 Y-5.261 Z1.43 </boundaryPoint>)
(<boundaryPoint> X1.129 Y5.261 Z1.43 </boundaryPoint>)
(<boundaryPoint> X0.817 Y5.556 Z1.43 </boundaryPoint>)
(<boundaryPoint> X-0.819 Y5.556 Z1.43 </boundaryPoint>)
M73 P47 (display progress)
(<boundaryPoint> X-1.13 Y5.261 Z1.43 </boundaryPoint>)
(<edge> outer )
G1 X-0.93 Y-5.01 Z1.43 F3300.0
G1 F1200.0
G1 E21.871
G1 F3300.0
M101
G1 X-0.93 Y-5.17 Z1.43 F502.933 E21.874
G1 X-0.74 Y-5.36 Z1.43 F502.933 E21.878
G1 X0.74 Y-5.36 Z1.43 F502.933 E21.905
G1 X0.93 Y-5.17 Z1.43 F502.933 E21.91
G1 X0.93 Y5.17 Z1.43 F502.933 E22.097
G1 X0.74 Y5.36 Z1.43 F502.933 E22.102
G1 X-0.74 Y5.36 Z1.43 F502.933 E22.129
G1 X-0.93 Y5.17 Z1.43 F502.933 E22.133
G1 X-0.93 Y-5.01 Z1.43 F502.933 E22.317
G1 F1200.0
G1 E22.317
G1 F502.933
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.93 Y-5.175 Z0.85 </infillPoint>)
M73 P48 (display progress)
(<infillPoint> X-0.739 Y-5.356 Z0.85 </infillPoint>)
(<infillPoint> X0.737 Y-5.356 Z0.85 </infillPoint>)
(<infillPoint> X0.929 Y-5.175 Z0.85 </infillPoint>)
(<infillPoint> X0.929 Y5.175 Z0.85 </infillPoint>)
(<infillPoint> X0.737 Y5.356 Z0.85 </infillPoint>)
(<infillPoint> X-0.739 Y5.356 Z0.85 </infillPoint>)
(<infillPoint> X-0.93 Y5.175 Z0.85 </infillPoint>)
(</infillBoundary>)
;M108 R16.76
G1 X-0.4 Y-5.08 Z1.43 F3300.0
G1 F1200.0
G1 E22.317
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z1.43 F1005.866 E22.501
G1 X0.0 Y5.08 Z1.43 F1005.866 E22.508
G1 X-0.0 Y-5.08 Z1.43 F1005.866 E22.692
G1 X0.4 Y-5.08 Z1.43 F1005.866 E22.699
G1 X0.4 Y5.08 Z1.43 F1005.866 E22.883
G1 F1200.0
G1 E21.883
G1 F1005.866
M103
(</infill>)
(</nestedRing>)
(</rotation>)
M73 P49 (display progress)
;M108 R9.983
(</layer>)
(<layer> 1.53 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.155 Y-5.261 Z1.53 </boundaryPoint>)
(<boundaryPoint> X-0.85 Y-5.556 Z1.53 </boundaryPoint>)
(<boundaryPoint> X0.851 Y-5.556 Z1.53 </boundaryPoint>)
(<boundaryPoint> X1.154 Y-5.261 Z1.53 </boundaryPoint>)
(<boundaryPoint> X1.154 Y5.261 Z1.53 </boundaryPoint>)
(<boundaryPoint> X0.851 Y5.556 Z1.53 </boundaryPoint>)
(<boundaryPoint> X-0.85 Y5.556 Z1.53 </boundaryPoint>)
(<boundaryPoint> X-1.155 Y5.261 Z1.53 </boundaryPoint>)
(<edge> outer )
G1 X-0.95 Y-4.7 Z1.53 F3300.0
G1 F1200.0
G1 E22.883
G1 F3300.0
M101
G1 X-0.95 Y-5.18 Z1.53 F599.008 E22.891
G1 X-0.77 Y-5.36 Z1.53 F599.008 E22.896
G1 X0.77 Y-5.36 Z1.53 F599.008 E22.924
G1 X0.95 Y-5.18 Z1.53 F599.008 E22.928
G1 X0.95 Y5.18 Z1.53 F599.008 E23.116
M73 P50 (display progress)
G1 X0.77 Y5.36 Z1.53 F599.008 E23.12
G1 X-0.77 Y5.36 Z1.53 F599.008 E23.148
G1 X-0.95 Y5.18 Z1.53 F599.008 E23.153
G1 X-0.95 Y-4.7 Z1.53 F599.008 E23.332
G1 F1200.0
G1 E22.332
G1 F599.008
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.955 Y-5.176 Z0.95 </infillPoint>)
(<infillPoint> X-0.769 Y-5.356 Z0.95 </infillPoint>)
(<infillPoint> X0.77 Y-5.356 Z0.95 </infillPoint>)
(<infillPoint> X0.954 Y-5.177 Z0.95 </infillPoint>)
(<infillPoint> X0.954 Y5.177 Z0.95 </infillPoint>)
(<infillPoint> X0.77 Y5.356 Z0.95 </infillPoint>)
(<infillPoint> X-0.769 Y5.356 Z0.95 </infillPoint>)
(<infillPoint> X-0.955 Y5.176 Z0.95 </infillPoint>)
(</infillBoundary>)
;M108 R19.97
G1 X0.67 Y-0.0 Z1.53 F3300.0
G1 F1200.0
G1 E23.332
M73 P51 (display progress)
G1 F3300.0
M101
G1 X-0.68 Y0.0 Z1.53 F1198.017 E23.356
G1 X-0.68 Y-0.4 Z1.53 F1198.017 E23.363
G1 X0.67 Y-0.4 Z1.53 F1198.017 E23.388
G1 X0.67 Y-0.8 Z1.53 F1198.017 E23.395
G1 X-0.68 Y-0.8 Z1.53 F1198.017 E23.419
G1 X-0.68 Y-1.2 Z1.53 F1198.017 E23.426
G1 X0.67 Y-1.2 Z1.53 F1198.017 E23.451
G1 X0.67 Y-1.6 Z1.53 F1198.017 E23.458
G1 X-0.68 Y-1.6 Z1.53 F1198.017 E23.483
G1 X-0.68 Y-2.0 Z1.53 F1198.017 E23.49
G1 X0.67 Y-2.0 Z1.53 F1198.017 E23.514
G1 X0.67 Y-2.4 Z1.53 F1198.017 E23.521
G1 X-0.68 Y-2.4 Z1.53 F1198.017 E23.546
G1 X-0.68 Y-2.8 Z1.53 F1198.017 E23.553
G1 X0.67 Y-2.8 Z1.53 F1198.017 E23.577
G1 X0.67 Y-3.2 Z1.53 F1198.017 E23.585
G1 X-0.68 Y-3.2 Z1.53 F1198.017 E23.609
G1 X-0.68 Y-3.6 Z1.53 F1198.017 E23.616
G1 X0.67 Y-3.6 Z1.53 F1198.017 E23.641
G1 X0.67 Y-4.0 Z1.53 F1198.017 E23.648
G1 X-0.68 Y-4.0 Z1.53 F1198.017 E23.672
G1 X-0.68 Y-4.4 Z1.53 F1198.017 E23.68
G1 X0.67 Y-4.4 Z1.53 F1198.017 E23.704
G1 X0.67 Y-4.8 Z1.53 F1198.017 E23.711
M73 P52 (display progress)
G1 X-0.68 Y-4.8 Z1.53 F1198.017 E23.736
G1 F1200.0
G1 E22.736
G1 F1198.017
M103
G1 X-0.68 Y0.4 Z1.53 F3300.0
G1 F1200.0
G1 E23.736
G1 F3300.0
M101
G1 X0.67 Y0.4 Z1.53 F1198.017 E23.76
G1 X0.67 Y0.8 Z1.53 F1198.017 E23.767
G1 X-0.68 Y0.8 Z1.53 F1198.017 E23.792
G1 X-0.68 Y1.2 Z1.53 F1198.017 E23.799
G1 X0.67 Y1.2 Z1.53 F1198.017 E23.823
G1 X0.67 Y1.6 Z1.53 F1198.017 E23.831
G1 X-0.68 Y1.6 Z1.53 F1198.017 E23.855
G1 X-0.68 Y2.0 Z1.53 F1198.017 E23.862
G1 X0.67 Y2.0 Z1.53 F1198.017 E23.887
G1 X0.67 Y2.4 Z1.53 F1198.017 E23.894
G1 X-0.68 Y2.4 Z1.53 F1198.017 E23.918
G1 X-0.68 Y2.8 Z1.53 F1198.017 E23.926
G1 X0.67 Y2.8 Z1.53 F1198.017 E23.95
G1 X0.67 Y3.2 Z1.53 F1198.017 E23.957
G1 X-0.68 Y3.2 Z1.53 F1198.017 E23.982
M73 P53 (display progress)
G1 X-0.68 Y3.6 Z1.53 F1198.017 E23.989
G1 X0.67 Y3.6 Z1.53 F1198.017 E24.013
G1 X0.67 Y4.0 Z1.53 F1198.017 E24.02
G1 X-0.68 Y4.0 Z1.53 F1198.017 E24.045
G1 X-0.68 Y4.4 Z1.53 F1198.017 E24.052
G1 X0.67 Y4.4 Z1.53 F1198.017 E24.076
G1 X0.67 Y4.8 Z1.53 F1198.017 E24.084
G1 X-0.68 Y4.8 Z1.53 F1198.017 E24.108
G1 F1200.0
G1 E23.108
G1 F1198.017
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.426
(</layer>)
(<layer> 1.63 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.874 Y5.556 Z1.63 </boundaryPoint>)
(<boundaryPoint> X-1.169 Y5.261 Z1.63 </boundaryPoint>)
(<boundaryPoint> X-1.169 Y-5.261 Z1.63 </boundaryPoint>)
(<boundaryPoint> X-0.874 Y-5.556 Z1.63 </boundaryPoint>)
M73 P54 (display progress)
(<boundaryPoint> X0.872 Y-5.556 Z1.63 </boundaryPoint>)
(<boundaryPoint> X1.17 Y-5.261 Z1.63 </boundaryPoint>)
(<boundaryPoint> X1.17 Y5.261 Z1.63 </boundaryPoint>)
(<boundaryPoint> X0.872 Y5.556 Z1.63 </boundaryPoint>)
(<edge> outer )
G1 X-0.95 Y-5.19 Z1.63 F3300.0
G1 F1200.0
G1 E24.108
G1 F3300.0
M101
G1 X-0.79 Y-5.36 Z1.63 F505.562 E24.112
G1 X0.79 Y-5.36 Z1.63 F505.562 E24.141
G1 X0.97 Y-5.18 Z1.63 F505.562 E24.145
G1 X0.97 Y5.18 Z1.63 F505.562 E24.333
G1 X0.79 Y5.36 Z1.63 F505.562 E24.337
G1 X-0.79 Y5.36 Z1.63 F505.562 E24.366
G1 X-0.97 Y5.18 Z1.63 F505.562 E24.371
G1 X-0.97 Y-5.18 Z1.63 F505.562 E24.558
G1 X-0.95 Y-5.19 Z1.63 F505.562 E24.558
G1 F1200.0
G1 E24.558
G1 F505.562
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
M73 P55 (display progress)
(<infillBoundary>)
(<infillPoint> X-0.791 Y5.356 Z1.05 </infillPoint>)
(<infillPoint> X-0.969 Y5.178 Z1.05 </infillPoint>)
(<infillPoint> X-0.969 Y-5.178 Z1.05 </infillPoint>)
(<infillPoint> X-0.791 Y-5.356 Z1.05 </infillPoint>)
(<infillPoint> X0.79 Y-5.356 Z1.05 </infillPoint>)
(<infillPoint> X0.97 Y-5.178 Z1.05 </infillPoint>)
(<infillPoint> X0.97 Y5.178 Z1.05 </infillPoint>)
(<infillPoint> X0.79 Y5.356 Z1.05 </infillPoint>)
(</infillBoundary>)
;M108 R16.85
G1 X-0.4 Y-5.08 Z1.63 F3300.0
G1 F1200.0
G1 E24.558
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z1.63 F1011.123 E24.742
G1 X0.0 Y5.08 Z1.63 F1011.123 E24.749
G1 X-0.0 Y-5.08 Z1.63 F1011.123 E24.933
G1 X0.4 Y-5.08 Z1.63 F1011.123 E24.94
G1 X0.4 Y5.08 Z1.63 F1011.123 E25.124
G1 F1200.0
G1 E24.124
G1 F1011.123
M103
M73 P56 (display progress)
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R10.14
(</layer>)
(<layer> 1.73 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.88 Y5.556 Z1.73 </boundaryPoint>)
(<boundaryPoint> X-1.179 Y5.261 Z1.73 </boundaryPoint>)
(<boundaryPoint> X-1.179 Y-5.261 Z1.73 </boundaryPoint>)
(<boundaryPoint> X-0.88 Y-5.556 Z1.73 </boundaryPoint>)
(<boundaryPoint> X0.881 Y-5.556 Z1.73 </boundaryPoint>)
(<boundaryPoint> X1.176 Y-5.261 Z1.73 </boundaryPoint>)
(<boundaryPoint> X1.176 Y5.261 Z1.73 </boundaryPoint>)
(<boundaryPoint> X0.881 Y5.556 Z1.73 </boundaryPoint>)
(<edge> outer )
G1 X-0.98 Y-4.89 Z1.73 F3300.0
G1 F1200.0
G1 E25.124
G1 F3300.0
M101
G1 X-0.98 Y-5.18 Z1.73 F608.656 E25.129
G1 X-0.8 Y-5.36 Z1.73 F608.656 E25.133
G1 X0.8 Y-5.36 Z1.73 F608.656 E25.162
M73 P57 (display progress)
G1 X0.98 Y-5.18 Z1.73 F608.656 E25.167
G1 X0.98 Y5.18 Z1.73 F608.656 E25.354
G1 X0.8 Y5.36 Z1.73 F608.656 E25.358
G1 X-0.8 Y5.36 Z1.73 F608.656 E25.387
G1 X-0.98 Y5.18 Z1.73 F608.656 E25.392
G1 X-0.98 Y-4.89 Z1.73 F608.656 E25.574
G1 F1200.0
G1 E24.574
G1 F608.656
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.798 Y5.356 Z1.15 </infillPoint>)
(<infillPoint> X-0.979 Y5.177 Z1.15 </infillPoint>)
(<infillPoint> X-0.979 Y-5.177 Z1.15 </infillPoint>)
(<infillPoint> X-0.798 Y-5.356 Z1.15 </infillPoint>)
(<infillPoint> X0.798 Y-5.356 Z1.15 </infillPoint>)
(<infillPoint> X0.976 Y-5.178 Z1.15 </infillPoint>)
(<infillPoint> X0.976 Y5.178 Z1.15 </infillPoint>)
(<infillPoint> X0.798 Y5.356 Z1.15 </infillPoint>)
(</infillBoundary>)
;M108 R20.29
G1 X0.7 Y-0.0 Z1.73 F3300.0
M73 P58 (display progress)
G1 F1200.0
G1 E25.574
G1 F3300.0
M101
G1 X-0.7 Y0.0 Z1.73 F1217.313 E25.599
G1 X-0.7 Y-0.4 Z1.73 F1217.313 E25.607
G1 X0.7 Y-0.4 Z1.73 F1217.313 E25.632
G1 X0.7 Y-0.8 Z1.73 F1217.313 E25.639
G1 X-0.7 Y-0.8 Z1.73 F1217.313 E25.664
G1 X-0.7 Y-1.2 Z1.73 F1217.313 E25.671
G1 X0.7 Y-1.2 Z1.73 F1217.313 E25.697
G1 X0.7 Y-1.6 Z1.73 F1217.313 E25.704
G1 X-0.7 Y-1.6 Z1.73 F1217.313 E25.729
G1 X-0.7 Y-2.0 Z1.73 F1217.313 E25.736
G1 X0.7 Y-2.0 Z1.73 F1217.313 E25.762
G1 X0.7 Y-2.4 Z1.73 F1217.313 E25.769
G1 X-0.7 Y-2.4 Z1.73 F1217.313 E25.794
G1 X-0.7 Y-2.8 Z1.73 F1217.313 E25.801
G1 X0.7 Y-2.8 Z1.73 F1217.313 E25.827
G1 X0.7 Y-3.2 Z1.73 F1217.313 E25.834
G1 X-0.7 Y-3.2 Z1.73 F1217.313 E25.859
G1 X-0.7 Y-3.6 Z1.73 F1217.313 E25.866
G1 X0.7 Y-3.6 Z1.73 F1217.313 E25.892
G1 X0.7 Y-4.0 Z1.73 F1217.313 E25.899
G1 X-0.7 Y-4.0 Z1.73 F1217.313 E25.924
M73 P59 (display progress)
G1 X-0.7 Y-4.4 Z1.73 F1217.313 E25.931
G1 X0.7 Y-4.4 Z1.73 F1217.313 E25.956
G1 X0.7 Y-4.8 Z1.73 F1217.313 E25.964
G1 X-0.7 Y-4.8 Z1.73 F1217.313 E25.989
G1 F1200.0
G1 E24.989
G1 F1217.313
M103
G1 X-0.7 Y0.4 Z1.73 F3300.0
G1 F1200.0
G1 E25.989
G1 F3300.0
M101
G1 X0.7 Y0.4 Z1.73 F1217.313 E26.014
G1 X0.7 Y0.8 Z1.73 F1217.313 E26.021
G1 X-0.7 Y0.8 Z1.73 F1217.313 E26.047
G1 X-0.7 Y1.2 Z1.73 F1217.313 E26.054
G1 X0.7 Y1.2 Z1.73 F1217.313 E26.079
G1 X0.7 Y1.6 Z1.73 F1217.313 E26.086
G1 X-0.7 Y1.6 Z1.73 F1217.313 E26.112
G1 X-0.7 Y2.0 Z1.73 F1217.313 E26.119
G1 X0.7 Y2.0 Z1.73 F1217.313 E26.144
G1 X0.7 Y2.4 Z1.73 F1217.313 E26.151
G1 X-0.7 Y2.4 Z1.73 F1217.313 E26.177
G1 X-0.7 Y2.8 Z1.73 F1217.313 E26.184
G1 X0.7 Y2.8 Z1.73 F1217.313 E26.209
M73 P60 (display progress)
G1 X0.7 Y3.2 Z1.73 F1217.313 E26.216
G1 X-0.7 Y3.2 Z1.73 F1217.313 E26.241
G1 X-0.7 Y3.6 Z1.73 F1217.313 E26.249
G1 X0.7 Y3.6 Z1.73 F1217.313 E26.274
G1 X0.7 Y4.0 Z1.73 F1217.313 E26.281
G1 X-0.7 Y4.0 Z1.73 F1217.313 E26.306
G1 X-0.7 Y4.4 Z1.73 F1217.313 E26.314
G1 X0.7 Y4.4 Z1.73 F1217.313 E26.339
G1 X0.7 Y4.8 Z1.73 F1217.313 E26.346
G1 X-0.7 Y4.8 Z1.73 F1217.313 E26.371
G1 F1200.0
G1 E25.371
G1 F1217.313
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.429
(</layer>)
(<layer> 1.83 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.173 Y-5.261 Z1.83 </boundaryPoint>)
(<boundaryPoint> X-0.881 Y-5.556 Z1.83 </boundaryPoint>)
M73 P61 (display progress)
(<boundaryPoint> X0.879 Y-5.556 Z1.83 </boundaryPoint>)
(<boundaryPoint> X1.177 Y-5.261 Z1.83 </boundaryPoint>)
(<boundaryPoint> X1.177 Y5.261 Z1.83 </boundaryPoint>)
(<boundaryPoint> X0.879 Y5.556 Z1.83 </boundaryPoint>)
(<boundaryPoint> X-0.881 Y5.556 Z1.83 </boundaryPoint>)
(<boundaryPoint> X-1.173 Y5.261 Z1.83 </boundaryPoint>)
(<edge> outer )
G1 X-0.59 Y-5.36 Z1.83 F3300.0
G1 F1200.0
G1 E26.371
G1 F3300.0
M101
G1 X0.8 Y-5.36 Z1.83 F505.732 E26.396
G1 X0.98 Y-5.18 Z1.83 F505.732 E26.401
G1 X0.98 Y5.18 Z1.83 F505.732 E26.588
G1 X0.8 Y5.36 Z1.83 F505.732 E26.593
G1 X-0.8 Y5.36 Z1.83 F505.732 E26.622
G1 X-0.97 Y5.18 Z1.83 F505.732 E26.626
G1 X-0.97 Y-5.18 Z1.83 F505.732 E26.814
G1 X-0.8 Y-5.36 Z1.83 F505.732 E26.818
G1 X-0.59 Y-5.36 Z1.83 F505.732 E26.822
G1 F1200.0
G1 E26.822
G1 F505.732
M103
M73 P62 (display progress)
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.973 Y-5.179 Z1.25 </infillPoint>)
(<infillPoint> X-0.798 Y-5.356 Z1.25 </infillPoint>)
(<infillPoint> X0.797 Y-5.356 Z1.25 </infillPoint>)
(<infillPoint> X0.977 Y-5.178 Z1.25 </infillPoint>)
(<infillPoint> X0.977 Y5.178 Z1.25 </infillPoint>)
(<infillPoint> X0.797 Y5.356 Z1.25 </infillPoint>)
(<infillPoint> X-0.798 Y5.356 Z1.25 </infillPoint>)
(<infillPoint> X-0.973 Y5.179 Z1.25 </infillPoint>)
(</infillBoundary>)
;M108 R16.86
G1 X-0.4 Y-5.08 Z1.83 F3300.0
G1 F1200.0
G1 E26.822
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z1.83 F1011.463 E27.006
G1 X0.0 Y5.08 Z1.83 F1011.463 E27.013
G1 X-0.0 Y-5.08 Z1.83 F1011.463 E27.196
G1 X0.4 Y-5.08 Z1.83 F1011.463 E27.204
G1 X0.4 Y5.08 Z1.83 F1011.463 E27.387
G1 F1200.0
G1 E26.387
M73 P63 (display progress)
G1 F1011.463
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R10.08
(</layer>)
(<layer> 1.93 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.168 Y-5.261 Z1.93 </boundaryPoint>)
(<boundaryPoint> X-0.864 Y-5.556 Z1.93 </boundaryPoint>)
(<boundaryPoint> X0.865 Y-5.556 Z1.93 </boundaryPoint>)
(<boundaryPoint> X1.163 Y-5.261 Z1.93 </boundaryPoint>)
(<boundaryPoint> X1.163 Y5.261 Z1.93 </boundaryPoint>)
(<boundaryPoint> X0.865 Y5.556 Z1.93 </boundaryPoint>)
(<boundaryPoint> X-0.864 Y5.556 Z1.93 </boundaryPoint>)
(<boundaryPoint> X-1.168 Y5.261 Z1.93 </boundaryPoint>)
(<edge> outer )
G1 X-0.97 Y-5.08 Z1.93 F3300.0
G1 F1200.0
G1 E27.387
G1 F3300.0
M101
M73 P64 (display progress)
G1 X-0.97 Y-5.18 Z1.93 F604.937 E27.389
G1 X-0.78 Y-5.36 Z1.93 F604.937 E27.394
G1 X0.78 Y-5.36 Z1.93 F604.937 E27.422
G1 X0.96 Y-5.18 Z1.93 F604.937 E27.427
G1 X0.96 Y5.18 Z1.93 F604.937 E27.614
G1 X0.78 Y5.36 Z1.93 F604.937 E27.619
G1 X-0.78 Y5.36 Z1.93 F604.937 E27.647
G1 X-0.97 Y5.18 Z1.93 F604.937 E27.652
G1 X-0.97 Y-5.08 Z1.93 F604.937 E27.837
G1 F1200.0
G1 E26.837
G1 F604.937
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.968 Y-5.176 Z1.35 </infillPoint>)
(<infillPoint> X-0.783 Y-5.356 Z1.35 </infillPoint>)
(<infillPoint> X0.783 Y-5.356 Z1.35 </infillPoint>)
(<infillPoint> X0.963 Y-5.178 Z1.35 </infillPoint>)
(<infillPoint> X0.963 Y5.178 Z1.35 </infillPoint>)
(<infillPoint> X0.783 Y5.356 Z1.35 </infillPoint>)
(<infillPoint> X-0.783 Y5.356 Z1.35 </infillPoint>)
(<infillPoint> X-0.968 Y5.176 Z1.35 </infillPoint>)
(</infillBoundary>)
M73 P65 (display progress)
;M108 R20.16
G1 X0.68 Y-0.0 Z1.93 F3300.0
G1 F1200.0
G1 E27.837
G1 F3300.0
M101
G1 X-0.69 Y0.0 Z1.93 F1209.875 E27.862
G1 X-0.69 Y-0.4 Z1.93 F1209.875 E27.869
G1 X0.68 Y-0.4 Z1.93 F1209.875 E27.894
G1 X0.68 Y-0.8 Z1.93 F1209.875 E27.901
G1 X-0.69 Y-0.8 Z1.93 F1209.875 E27.926
G1 X-0.69 Y-1.2 Z1.93 F1209.875 E27.933
G1 X0.68 Y-1.2 Z1.93 F1209.875 E27.958
G1 X0.68 Y-1.6 Z1.93 F1209.875 E27.965
G1 X-0.69 Y-1.6 Z1.93 F1209.875 E27.99
G1 X-0.69 Y-2.0 Z1.93 F1209.875 E27.997
G1 X0.68 Y-2.0 Z1.93 F1209.875 E28.022
G1 X0.68 Y-2.4 Z1.93 F1209.875 E28.029
G1 X-0.69 Y-2.4 Z1.93 F1209.875 E28.054
G1 X-0.69 Y-2.8 Z1.93 F1209.875 E28.061
G1 X0.68 Y-2.8 Z1.93 F1209.875 E28.086
G1 X0.68 Y-3.2 Z1.93 F1209.875 E28.093
G1 X-0.69 Y-3.2 Z1.93 F1209.875 E28.118
G1 X-0.69 Y-3.6 Z1.93 F1209.875 E28.125
G1 X0.68 Y-3.6 Z1.93 F1209.875 E28.15
M73 P66 (display progress)
G1 X0.68 Y-4.0 Z1.93 F1209.875 E28.157
G1 X-0.69 Y-4.0 Z1.93 F1209.875 E28.182
G1 X-0.69 Y-4.4 Z1.93 F1209.875 E28.189
G1 X0.68 Y-4.4 Z1.93 F1209.875 E28.214
G1 X0.68 Y-4.8 Z1.93 F1209.875 E28.221
G1 X-0.69 Y-4.8 Z1.93 F1209.875 E28.246
G1 F1200.0
G1 E27.246
G1 F1209.875
M103
G1 X-0.69 Y0.4 Z1.93 F3300.0
G1 F1200.0
G1 E28.246
G1 F3300.0
M101
G1 X0.68 Y0.4 Z1.93 F1209.875 E28.271
G1 X0.68 Y0.8 Z1.93 F1209.875 E28.278
G1 X-0.69 Y0.8 Z1.93 F1209.875 E28.303
G1 X-0.69 Y1.2 Z1.93 F1209.875 E28.31
G1 X0.68 Y1.2 Z1.93 F1209.875 E28.335
G1 X0.68 Y1.6 Z1.93 F1209.875 E28.342
G1 X-0.69 Y1.6 Z1.93 F1209.875 E28.367
G1 X-0.69 Y2.0 Z1.93 F1209.875 E28.374
G1 X0.68 Y2.0 Z1.93 F1209.875 E28.399
G1 X0.68 Y2.4 Z1.93 F1209.875 E28.406
M73 P67 (display progress)
G1 X-0.69 Y2.4 Z1.93 F1209.875 E28.431
G1 X-0.69 Y2.8 Z1.93 F1209.875 E28.438
G1 X0.68 Y2.8 Z1.93 F1209.875 E28.463
G1 X0.68 Y3.2 Z1.93 F1209.875 E28.47
G1 X-0.69 Y3.2 Z1.93 F1209.875 E28.495
G1 X-0.69 Y3.6 Z1.93 F1209.875 E28.502
G1 X0.68 Y3.6 Z1.93 F1209.875 E28.527
G1 X0.68 Y4.0 Z1.93 F1209.875 E28.534
G1 X-0.69 Y4.0 Z1.93 F1209.875 E28.559
G1 X-0.69 Y4.4 Z1.93 F1209.875 E28.566
G1 X0.68 Y4.4 Z1.93 F1209.875 E28.591
G1 X0.68 Y4.8 Z1.93 F1209.875 E28.598
G1 X-0.69 Y4.8 Z1.93 F1209.875 E28.623
G1 F1200.0
G1 E27.623
G1 F1209.875
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.393
(</layer>)
(<layer> 2.03 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
M73 P68 (display progress)
(<boundaryPoint> X-1.144 Y-5.261 Z2.03 </boundaryPoint>)
(<boundaryPoint> X-0.843 Y-5.556 Z2.03 </boundaryPoint>)
(<boundaryPoint> X0.84 Y-5.556 Z2.03 </boundaryPoint>)
(<boundaryPoint> X1.149 Y-5.261 Z2.03 </boundaryPoint>)
(<boundaryPoint> X1.149 Y5.261 Z2.03 </boundaryPoint>)
(<boundaryPoint> X0.84 Y5.556 Z2.03 </boundaryPoint>)
(<boundaryPoint> X-0.843 Y5.556 Z2.03 </boundaryPoint>)
(<boundaryPoint> X-1.144 Y5.261 Z2.03 </boundaryPoint>)
(<edge> outer )
G1 X-0.94 Y-4.78 Z2.03 F3300.0
G1 F1200.0
G1 E28.623
G1 F3300.0
M101
G1 X-0.94 Y-5.18 Z2.03 F503.594 E28.63
G1 X-0.76 Y-5.36 Z2.03 F503.594 E28.635
G1 X0.76 Y-5.36 Z2.03 F503.594 E28.663
G1 X0.95 Y-5.17 Z2.03 F503.594 E28.667
G1 X0.95 Y5.17 Z2.03 F503.594 E28.855
G1 X0.76 Y5.36 Z2.03 F503.594 E28.859
G1 X-0.76 Y5.36 Z2.03 F503.594 E28.887
G1 X-0.94 Y5.18 Z2.03 F503.594 E28.891
G1 X-0.94 Y-4.78 Z2.03 F503.594 E29.071
G1 F1200.0
G1 E29.071
M73 P69 (display progress)
G1 F503.594
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.944 Y-5.177 Z1.45 </infillPoint>)
(<infillPoint> X-0.761 Y-5.356 Z1.45 </infillPoint>)
(<infillPoint> X0.76 Y-5.356 Z1.45 </infillPoint>)
(<infillPoint> X0.949 Y-5.175 Z1.45 </infillPoint>)
(<infillPoint> X0.949 Y5.175 Z1.45 </infillPoint>)
(<infillPoint> X0.76 Y5.356 Z1.45 </infillPoint>)
(<infillPoint> X-0.761 Y5.356 Z1.45 </infillPoint>)
(<infillPoint> X-0.944 Y5.177 Z1.45 </infillPoint>)
(</infillBoundary>)
;M108 R16.79
G1 X-0.4 Y-5.08 Z2.03 F3300.0
G1 F1200.0
G1 E29.071
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z2.03 F1007.188 E29.255
G1 X0.0 Y5.08 Z2.03 F1007.188 E29.262
G1 X-0.0 Y-5.08 Z2.03 F1007.188 E29.446
G1 X0.4 Y-5.08 Z2.03 F1007.188 E29.453
M73 P70 (display progress)
G1 X0.4 Y5.08 Z2.03 F1007.188 E29.637
G1 F1200.0
G1 E28.637
G1 F1007.188
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R9.786
(</layer>)
(<layer> 2.13 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.119 Y-5.261 Z2.13 </boundaryPoint>)
(<boundaryPoint> X-0.799 Y-5.556 Z2.13 </boundaryPoint>)
(<boundaryPoint> X0.799 Y-5.556 Z2.13 </boundaryPoint>)
(<boundaryPoint> X1.116 Y-5.261 Z2.13 </boundaryPoint>)
(<boundaryPoint> X1.116 Y5.261 Z2.13 </boundaryPoint>)
(<boundaryPoint> X0.799 Y5.556 Z2.13 </boundaryPoint>)
(<boundaryPoint> X-0.799 Y5.556 Z2.13 </boundaryPoint>)
(<boundaryPoint> X-1.119 Y5.261 Z2.13 </boundaryPoint>)
(<edge> outer )
G1 X-0.85 Y-5.24 Z2.13 F3300.0
G1 F1200.0
G1 E29.637
M73 P71 (display progress)
G1 F3300.0
M101
G1 X-0.72 Y-5.36 Z2.13 F587.16 E29.64
G1 X0.72 Y-5.36 Z2.13 F587.16 E29.666
G1 X0.92 Y-5.17 Z2.13 F587.16 E29.671
G1 X0.92 Y5.17 Z2.13 F587.16 E29.858
G1 X0.72 Y5.36 Z2.13 F587.16 E29.863
G1 X-0.72 Y5.36 Z2.13 F587.16 E29.889
G1 X-0.92 Y5.17 Z2.13 F587.16 E29.894
G1 X-0.92 Y-5.17 Z2.13 F587.16 E30.081
G1 X-0.85 Y-5.24 Z2.13 F587.16 E30.083
G1 F1200.0
G1 E29.083
G1 F587.16
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.919 Y-5.173 Z1.55 </infillPoint>)
(<infillPoint> X-0.721 Y-5.356 Z1.55 </infillPoint>)
(<infillPoint> X0.72 Y-5.356 Z1.55 </infillPoint>)
(<infillPoint> X0.916 Y-5.174 Z1.55 </infillPoint>)
(<infillPoint> X0.916 Y5.174 Z1.55 </infillPoint>)
(<infillPoint> X0.72 Y5.356 Z1.55 </infillPoint>)
M73 P72 (display progress)
(<infillPoint> X-0.721 Y5.356 Z1.55 </infillPoint>)
(<infillPoint> X-0.919 Y5.173 Z1.55 </infillPoint>)
(</infillBoundary>)
;M108 R19.57
G1 X0.64 Y-0.0 Z2.13 F3300.0
G1 F1200.0
G1 E30.083
G1 F3300.0
M101
G1 X-0.64 Y0.0 Z2.13 F1174.319 E30.106
G1 X-0.64 Y-0.4 Z2.13 F1174.319 E30.113
G1 X0.64 Y-0.4 Z2.13 F1174.319 E30.136
G1 X0.64 Y-0.8 Z2.13 F1174.319 E30.143
G1 X-0.64 Y-0.8 Z2.13 F1174.319 E30.167
G1 X-0.64 Y-1.2 Z2.13 F1174.319 E30.174
G1 X0.64 Y-1.2 Z2.13 F1174.319 E30.197
G1 X0.64 Y-1.6 Z2.13 F1174.319 E30.204
G1 X-0.64 Y-1.6 Z2.13 F1174.319 E30.227
G1 X-0.64 Y-2.0 Z2.13 F1174.319 E30.234
G1 X0.64 Y-2.0 Z2.13 F1174.319 E30.257
G1 X0.64 Y-2.4 Z2.13 F1174.319 E30.265
G1 X-0.64 Y-2.4 Z2.13 F1174.319 E30.288
G1 X-0.64 Y-2.8 Z2.13 F1174.319 E30.295
G1 X0.64 Y-2.8 Z2.13 F1174.319 E30.318
G1 X0.64 Y-3.2 Z2.13 F1174.319 E30.325
G1 X-0.64 Y-3.2 Z2.13 F1174.319 E30.348
M73 P73 (display progress)
G1 X-0.64 Y-3.6 Z2.13 F1174.319 E30.356
G1 X0.64 Y-3.6 Z2.13 F1174.319 E30.379
G1 X0.64 Y-4.0 Z2.13 F1174.319 E30.386
G1 X-0.64 Y-4.0 Z2.13 F1174.319 E30.409
G1 X-0.64 Y-4.4 Z2.13 F1174.319 E30.416
G1 X0.64 Y-4.4 Z2.13 F1174.319 E30.439
G1 X0.64 Y-4.8 Z2.13 F1174.319 E30.446
G1 X-0.64 Y-4.8 Z2.13 F1174.319 E30.469
G1 F1200.0
G1 E29.469
G1 F1174.319
M103
G1 X-0.64 Y0.4 Z2.13 F3300.0
G1 F1200.0
G1 E30.469
G1 F3300.0
M101
G1 X0.64 Y0.4 Z2.13 F1174.319 E30.493
G1 X0.64 Y0.8 Z2.13 F1174.319 E30.5
G1 X-0.64 Y0.8 Z2.13 F1174.319 E30.523
G1 X-0.64 Y1.2 Z2.13 F1174.319 E30.53
G1 X0.64 Y1.2 Z2.13 F1174.319 E30.553
G1 X0.64 Y1.6 Z2.13 F1174.319 E30.56
G1 X-0.64 Y1.6 Z2.13 F1174.319 E30.583
G1 X-0.64 Y2.0 Z2.13 F1174.319 E30.591
M73 P74 (display progress)
G1 X0.64 Y2.0 Z2.13 F1174.319 E30.614
G1 X0.64 Y2.4 Z2.13 F1174.319 E30.621
G1 X-0.64 Y2.4 Z2.13 F1174.319 E30.644
G1 X-0.64 Y2.8 Z2.13 F1174.319 E30.651
G1 X0.64 Y2.8 Z2.13 F1174.319 E30.674
G1 X0.64 Y3.2 Z2.13 F1174.319 E30.682
G1 X-0.64 Y3.2 Z2.13 F1174.319 E30.705
G1 X-0.64 Y3.6 Z2.13 F1174.319 E30.712
G1 X0.64 Y3.6 Z2.13 F1174.319 E30.735
G1 X0.64 Y4.0 Z2.13 F1174.319 E30.742
G1 X-0.64 Y4.0 Z2.13 F1174.319 E30.765
G1 X-0.64 Y4.4 Z2.13 F1174.319 E30.772
G1 X0.64 Y4.4 Z2.13 F1174.319 E30.796
G1 X0.64 Y4.8 Z2.13 F1174.319 E30.803
G1 X-0.64 Y4.8 Z2.13 F1174.319 E30.826
G1 F1200.0
G1 E29.826
G1 F1174.319
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.333
(</layer>)
(<layer> 2.23 )
M73 P75 (display progress)
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.078 Y-5.261 Z2.23 </boundaryPoint>)
(<boundaryPoint> X-0.749 Y-5.556 Z2.23 </boundaryPoint>)
(<boundaryPoint> X0.749 Y-5.556 Z2.23 </boundaryPoint>)
(<boundaryPoint> X1.081 Y-5.261 Z2.23 </boundaryPoint>)
(<boundaryPoint> X1.081 Y5.261 Z2.23 </boundaryPoint>)
(<boundaryPoint> X0.749 Y5.556 Z2.23 </boundaryPoint>)
(<boundaryPoint> X-0.749 Y5.556 Z2.23 </boundaryPoint>)
(<boundaryPoint> X-1.078 Y5.261 Z2.23 </boundaryPoint>)
(<edge> outer )
G1 X-0.88 Y-4.96 Z2.23 F3300.0
G1 F1200.0
G1 E30.826
G1 F3300.0
M101
G1 X-0.88 Y-5.17 Z2.23 F500.006 E30.83
G1 X-0.67 Y-5.36 Z2.23 F500.006 E30.835
G1 X0.67 Y-5.36 Z2.23 F500.006 E30.859
G1 X0.88 Y-5.17 Z2.23 F500.006 E30.864
G1 X0.88 Y5.17 Z2.23 F500.006 E31.051
G1 X0.67 Y5.36 Z2.23 F500.006 E31.056
G1 X-0.67 Y5.36 Z2.23 F500.006 E31.08
G1 X-0.88 Y5.17 Z2.23 F500.006 E31.085
G1 X-0.88 Y-4.96 Z2.23 F500.006 E31.269
M73 P76 (display progress)
G1 F1200.0
G1 E31.269
G1 F500.006
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.878 Y-5.172 Z1.65 </infillPoint>)
(<infillPoint> X-0.672 Y-5.356 Z1.65 </infillPoint>)
(<infillPoint> X0.673 Y-5.356 Z1.65 </infillPoint>)
(<infillPoint> X0.881 Y-5.171 Z1.65 </infillPoint>)
(<infillPoint> X0.881 Y5.171 Z1.65 </infillPoint>)
(<infillPoint> X0.673 Y5.356 Z1.65 </infillPoint>)
(<infillPoint> X-0.672 Y5.356 Z1.65 </infillPoint>)
(<infillPoint> X-0.878 Y5.172 Z1.65 </infillPoint>)
(</infillBoundary>)
;M108 R16.67
G1 X-0.4 Y-5.08 Z2.23 F3300.0
G1 F1200.0
G1 E31.269
G1 F3300.0
M101
G1 X-0.4 Y5.08 Z2.23 F1000.011 E31.452
G1 X0.0 Y5.08 Z2.23 F1000.011 E31.46
M73 P77 (display progress)
G1 X-0.0 Y-5.08 Z2.23 F1000.011 E31.643
G1 X0.4 Y-5.08 Z2.23 F1000.011 E31.65
G1 X0.4 Y5.08 Z2.23 F1000.011 E31.834
G1 F1200.0
G1 E30.834
G1 F1000.011
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R9.225
(</layer>)
(<layer> 2.33 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-1.03 Y-5.261 Z2.33 </boundaryPoint>)
(<boundaryPoint> X-0.672 Y-5.556 Z2.33 </boundaryPoint>)
(<boundaryPoint> X0.671 Y-5.556 Z2.33 </boundaryPoint>)
(<boundaryPoint> X1.028 Y-5.261 Z2.33 </boundaryPoint>)
(<boundaryPoint> X1.028 Y5.261 Z2.33 </boundaryPoint>)
(<boundaryPoint> X0.671 Y5.556 Z2.33 </boundaryPoint>)
(<boundaryPoint> X-0.672 Y5.556 Z2.33 </boundaryPoint>)
(<boundaryPoint> X-1.03 Y5.261 Z2.33 </boundaryPoint>)
(<edge> outer )
M73 P78 (display progress)
G1 X-0.61 Y-5.35 Z2.33 F3300.0
G1 F1200.0
G1 E31.834
G1 F3300.0
M101
G1 X-0.6 Y-5.36 Z2.33 F553.521 E31.834
G1 X0.6 Y-5.36 Z2.33 F553.521 E31.856
G1 X0.83 Y-5.17 Z2.33 F553.521 E31.861
G1 X0.83 Y5.17 Z2.33 F553.521 E32.048
G1 X0.6 Y5.36 Z2.33 F553.521 E32.054
G1 X-0.6 Y5.36 Z2.33 F553.521 E32.075
G1 X-0.83 Y5.17 Z2.33 F553.521 E32.081
G1 X-0.83 Y-5.17 Z2.33 F553.521 E32.268
G1 X-0.61 Y-5.35 Z2.33 F553.521 E32.273
G1 F1200.0
G1 E31.273
G1 F553.521
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.83 Y-5.167 Z1.75 </infillPoint>)
(<infillPoint> X-0.6 Y-5.356 Z1.75 </infillPoint>)
(<infillPoint> X0.599 Y-5.356 Z1.75 </infillPoint>)
(<infillPoint> X0.828 Y-5.167 Z1.75 </infillPoint>)
M73 P79 (display progress)
(<infillPoint> X0.828 Y5.167 Z1.75 </infillPoint>)
(<infillPoint> X0.599 Y5.356 Z1.75 </infillPoint>)
(<infillPoint> X-0.6 Y5.356 Z1.75 </infillPoint>)
(<infillPoint> X-0.83 Y5.167 Z1.75 </infillPoint>)
(</infillBoundary>)
;M108 R18.45
G1 X0.55 Y-0.0 Z2.33 F3300.0
G1 F1200.0
G1 E32.273
G1 F3300.0
M101
G1 X-0.55 Y0.0 Z2.33 F1107.041 E32.293
G1 X-0.55 Y-0.4 Z2.33 F1107.041 E32.3
G1 X0.55 Y-0.4 Z2.33 F1107.041 E32.32
G1 X0.55 Y-0.8 Z2.33 F1107.041 E32.327
G1 X-0.55 Y-0.8 Z2.33 F1107.041 E32.347
G1 X-0.55 Y-1.2 Z2.33 F1107.041 E32.354
G1 X0.55 Y-1.2 Z2.33 F1107.041 E32.374
G1 X0.55 Y-1.6 Z2.33 F1107.041 E32.381
G1 X-0.55 Y-1.6 Z2.33 F1107.041 E32.401
G1 X-0.55 Y-2.0 Z2.33 F1107.041 E32.408
G1 X0.55 Y-2.0 Z2.33 F1107.041 E32.428
G1 X0.55 Y-2.4 Z2.33 F1107.041 E32.435
G1 X-0.55 Y-2.4 Z2.33 F1107.041 E32.455
G1 X-0.55 Y-2.8 Z2.33 F1107.041 E32.463
M73 P80 (display progress)
G1 X0.55 Y-2.8 Z2.33 F1107.041 E32.482
G1 X0.55 Y-3.2 Z2.33 F1107.041 E32.49
G1 X-0.55 Y-3.2 Z2.33 F1107.041 E32.51
G1 X-0.55 Y-3.6 Z2.33 F1107.041 E32.517
G1 X0.55 Y-3.6 Z2.33 F1107.041 E32.537
G1 X0.55 Y-4.0 Z2.33 F1107.041 E32.544
G1 X-0.55 Y-4.0 Z2.33 F1107.041 E32.564
G1 X-0.55 Y-4.4 Z2.33 F1107.041 E32.571
G1 X0.55 Y-4.4 Z2.33 F1107.041 E32.591
G1 X0.55 Y-4.8 Z2.33 F1107.041 E32.598
G1 X-0.55 Y-4.8 Z2.33 F1107.041 E32.618
G1 F1200.0
G1 E31.618
G1 F1107.041
M103
G1 X-0.55 Y0.4 Z2.33 F3300.0
G1 F1200.0
G1 E32.618
G1 F3300.0
M101
G1 X0.55 Y0.4 Z2.33 F1107.041 E32.638
G1 X0.55 Y0.8 Z2.33 F1107.041 E32.645
G1 X-0.55 Y0.8 Z2.33 F1107.041 E32.665
G1 X-0.55 Y1.2 Z2.33 F1107.041 E32.672
G1 X0.55 Y1.2 Z2.33 F1107.041 E32.692
M73 P81 (display progress)
G1 X0.55 Y1.6 Z2.33 F1107.041 E32.699
G1 X-0.55 Y1.6 Z2.33 F1107.041 E32.719
G1 X-0.55 Y2.0 Z2.33 F1107.041 E32.726
G1 X0.55 Y2.0 Z2.33 F1107.041 E32.746
G1 X0.55 Y2.4 Z2.33 F1107.041 E32.753
G1 X-0.55 Y2.4 Z2.33 F1107.041 E32.773
G1 X-0.55 Y2.8 Z2.33 F1107.041 E32.78
G1 X0.55 Y2.8 Z2.33 F1107.041 E32.8
G1 X0.55 Y3.2 Z2.33 F1107.041 E32.808
G1 X-0.55 Y3.2 Z2.33 F1107.041 E32.827
G1 X-0.55 Y3.6 Z2.33 F1107.041 E32.835
G1 X0.55 Y3.6 Z2.33 F1107.041 E32.855
G1 X0.55 Y4.0 Z2.33 F1107.041 E32.862
G1 X-0.55 Y4.0 Z2.33 F1107.041 E32.882
G1 X-0.55 Y4.4 Z2.33 F1107.041 E32.889
G1 X0.55 Y4.4 Z2.33 F1107.041 E32.909
G1 X0.55 Y4.8 Z2.33 F1107.041 E32.916
G1 X-0.55 Y4.8 Z2.33 F1107.041 E32.936
G1 F1200.0
G1 E31.936
G1 F1107.041
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.229
M73 P82 (display progress)
(</layer>)
(<layer> 2.43 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.967 Y-5.261 Z2.43 </boundaryPoint>)
(<boundaryPoint> X-0.571 Y-5.556 Z2.43 </boundaryPoint>)
(<boundaryPoint> X0.573 Y-5.556 Z2.43 </boundaryPoint>)
(<boundaryPoint> X0.969 Y-5.261 Z2.43 </boundaryPoint>)
(<boundaryPoint> X0.969 Y5.261 Z2.43 </boundaryPoint>)
(<boundaryPoint> X0.573 Y5.556 Z2.43 </boundaryPoint>)
(<boundaryPoint> X-0.571 Y5.556 Z2.43 </boundaryPoint>)
(<boundaryPoint> X-0.967 Y5.261 Z2.43 </boundaryPoint>)
(<edge> outer )
G1 X-0.77 Y-5.14 Z2.43 F3300.0
G1 F1200.0
G1 E32.936
G1 F3300.0
M101
G1 X-0.77 Y-5.16 Z2.43 F493.745 E32.936
G1 X-0.51 Y-5.36 Z2.43 F493.745 E32.942
G1 X0.51 Y-5.36 Z2.43 F493.745 E32.96
G1 X0.77 Y-5.16 Z2.43 F493.745 E32.966
G1 X0.77 Y5.16 Z2.43 F493.745 E33.153
G1 X0.51 Y5.36 Z2.43 F493.745 E33.159
M73 P83 (display progress)
G1 X-0.51 Y5.36 Z2.43 F493.745 E33.177
G1 X-0.77 Y5.16 Z2.43 F493.745 E33.183
G1 X-0.77 Y-5.14 Z2.43 F493.745 E33.369
G1 F1200.0
G1 E33.369
G1 F493.745
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.767 Y-5.161 Z1.85 </infillPoint>)
(<infillPoint> X-0.505 Y-5.356 Z1.85 </infillPoint>)
(<infillPoint> X0.507 Y-5.356 Z1.85 </infillPoint>)
(<infillPoint> X0.769 Y-5.161 Z1.85 </infillPoint>)
(<infillPoint> X0.769 Y5.161 Z1.85 </infillPoint>)
(<infillPoint> X0.507 Y5.356 Z1.85 </infillPoint>)
(<infillPoint> X-0.505 Y5.356 Z1.85 </infillPoint>)
(<infillPoint> X-0.767 Y5.161 Z1.85 </infillPoint>)
(</infillBoundary>)
;M108 R16.46
G1 X-0.4 Y-5.08 Z2.43 F3300.0
G1 F1200.0
G1 E33.369
G1 F3300.0
M101
M73 P84 (display progress)
G1 X-0.4 Y5.08 Z2.43 F987.491 E33.553
G1 X0.0 Y5.08 Z2.43 F987.491 E33.56
G1 X-0.0 Y-5.08 Z2.43 F987.491 E33.744
G1 X0.4 Y-5.08 Z2.43 F987.491 E33.751
G1 X0.4 Y5.08 Z2.43 F987.491 E33.935
G1 F1200.0
G1 E32.935
G1 F987.491
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.298
(</layer>)
(<layer> 2.53 )
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.892 Y5.261 Z2.53 </boundaryPoint>)
(<boundaryPoint> X-0.892 Y-5.261 Z2.53 </boundaryPoint>)
(<boundaryPoint> X-0.428 Y-5.556 Z2.53 </boundaryPoint>)
(<boundaryPoint> X0.432 Y-5.556 Z2.53 </boundaryPoint>)
(<boundaryPoint> X0.888 Y-5.261 Z2.53 </boundaryPoint>)
(<boundaryPoint> X0.888 Y5.261 Z2.53 </boundaryPoint>)
(<boundaryPoint> X0.432 Y5.556 Z2.53 </boundaryPoint>)
M73 P85 (display progress)
(<boundaryPoint> X-0.428 Y5.556 Z2.53 </boundaryPoint>)
(<edge> outer )
G1 X-0.69 Y-4.82 Z2.53 F3300.0
G1 F1200.0
G1 E33.935
G1 F3300.0
M101
G1 X-0.69 Y-5.15 Z2.53 F497.874 E33.941
G1 X-0.37 Y-5.36 Z2.53 F497.874 E33.948
G1 X0.37 Y-5.36 Z2.53 F497.874 E33.961
G1 X0.69 Y-5.15 Z2.53 F497.874 E33.968
G1 X0.69 Y5.15 Z2.53 F497.874 E34.154
G1 X0.37 Y5.36 Z2.53 F497.874 E34.161
G1 X-0.37 Y5.36 Z2.53 F497.874 E34.175
G1 X-0.69 Y5.15 Z2.53 F497.874 E34.182
G1 X-0.69 Y-4.82 Z2.53 F497.874 E34.362
G1 F1200.0
G1 E33.362
G1 F497.874
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.692 Y5.151 Z1.95 </infillPoint>)
M73 P86 (display progress)
(<infillPoint> X-0.692 Y-5.151 Z1.95 </infillPoint>)
(<infillPoint> X-0.37 Y-5.356 Z1.95 </infillPoint>)
(<infillPoint> X0.373 Y-5.356 Z1.95 </infillPoint>)
(<infillPoint> X0.688 Y-5.152 Z1.95 </infillPoint>)
(<infillPoint> X0.688 Y5.152 Z1.95 </infillPoint>)
(<infillPoint> X0.373 Y5.356 Z1.95 </infillPoint>)
(<infillPoint> X-0.37 Y5.356 Z1.95 </infillPoint>)
(</infillBoundary>)
;M108 R16.6
G1 X0.41 Y-0.0 Z2.53 F3300.0
G1 F1200.0
G1 E34.362
G1 F3300.0
M101
G1 X-0.41 Y0.0 Z2.53 F995.748 E34.377
G1 X-0.41 Y-0.4 Z2.53 F995.748 E34.384
G1 X0.41 Y-0.4 Z2.53 F995.748 E34.399
G1 X0.41 Y-0.8 Z2.53 F995.748 E34.406
G1 X-0.41 Y-0.8 Z2.53 F995.748 E34.421
G1 X-0.41 Y-1.2 Z2.53 F995.748 E34.428
G1 X0.41 Y-1.2 Z2.53 F995.748 E34.443
G1 X0.41 Y-1.6 Z2.53 F995.748 E34.45
G1 X-0.41 Y-1.6 Z2.53 F995.748 E34.465
G1 X-0.41 Y-2.0 Z2.53 F995.748 E34.472
G1 X0.41 Y-2.0 Z2.53 F995.748 E34.487
G1 X0.41 Y-2.4 Z2.53 F995.748 E34.494
M73 P87 (display progress)
G1 X-0.41 Y-2.4 Z2.53 F995.748 E34.509
G1 X-0.41 Y-2.8 Z2.53 F995.748 E34.516
G1 X0.41 Y-2.8 Z2.53 F995.748 E34.531
G1 X0.41 Y-3.2 Z2.53 F995.748 E34.539
G1 X-0.41 Y-3.2 Z2.53 F995.748 E34.553
G1 X-0.41 Y-3.6 Z2.53 F995.748 E34.561
G1 X0.41 Y-3.6 Z2.53 F995.748 E34.575
G1 X0.41 Y-4.0 Z2.53 F995.748 E34.583
G1 X-0.41 Y-4.0 Z2.53 F995.748 E34.598
G1 X-0.41 Y-4.4 Z2.53 F995.748 E34.605
G1 X0.41 Y-4.4 Z2.53 F995.748 E34.62
G1 X0.41 Y-4.8 Z2.53 F995.748 E34.627
G1 X-0.41 Y-4.8 Z2.53 F995.748 E34.642
G1 F1200.0
G1 E33.642
G1 F995.748
M103
G1 X-0.41 Y0.4 Z2.53 F3300.0
G1 F1200.0
G1 E34.642
G1 F3300.0
M101
G1 X0.41 Y0.4 Z2.53 F995.748 E34.656
G1 X0.41 Y0.8 Z2.53 F995.748 E34.664
G1 X-0.41 Y0.8 Z2.53 F995.748 E34.679
M73 P88 (display progress)
G1 X-0.41 Y1.2 Z2.53 F995.748 E34.686
G1 X0.41 Y1.2 Z2.53 F995.748 E34.701
G1 X0.41 Y1.6 Z2.53 F995.748 E34.708
G1 X-0.41 Y1.6 Z2.53 F995.748 E34.723
G1 X-0.41 Y2.0 Z2.53 F995.748 E34.73
G1 X0.41 Y2.0 Z2.53 F995.748 E34.745
G1 X0.41 Y2.4 Z2.53 F995.748 E34.752
G1 X-0.41 Y2.4 Z2.53 F995.748 E34.767
G1 X-0.41 Y2.8 Z2.53 F995.748 E34.774
G1 X0.41 Y2.8 Z2.53 F995.748 E34.789
G1 X0.41 Y3.2 Z2.53 F995.748 E34.796
G1 X-0.41 Y3.2 Z2.53 F995.748 E34.811
G1 X-0.41 Y3.6 Z2.53 F995.748 E34.818
G1 X0.41 Y3.6 Z2.53 F995.748 E34.833
G1 X0.41 Y4.0 Z2.53 F995.748 E34.84
G1 X-0.41 Y4.0 Z2.53 F995.748 E34.855
G1 X-0.41 Y4.4 Z2.53 F995.748 E34.862
G1 X0.41 Y4.4 Z2.53 F995.748 E34.877
G1 X0.41 Y4.8 Z2.53 F995.748 E34.884
G1 X-0.41 Y4.8 Z2.53 F995.748 E34.899
G1 F1200.0
G1 E33.899
G1 F995.748
M103
(</infill>)
M73 P89 (display progress)
(</nestedRing>)
(</rotation>)
;M108 R5.871
(</layer>)
(<layer> 2.63 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.799 Y-5.271 Z2.63 </boundaryPoint>)
(<boundaryPoint> X0.799 Y5.271 Z2.63 </boundaryPoint>)
(<boundaryPoint> X0.3 Y5.523 Z2.63 </boundaryPoint>)
(<boundaryPoint> X0.141 Y5.556 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.148 Y5.556 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.339 Y5.508 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.79 Y5.275 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.79 Y-5.277 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.305 Y-5.519 Z2.63 </boundaryPoint>)
(<boundaryPoint> X-0.148 Y-5.556 Z2.63 </boundaryPoint>)
(<boundaryPoint> X0.141 Y-5.556 Z2.63 </boundaryPoint>)
(<boundaryPoint> X0.3 Y-5.523 Z2.63 </boundaryPoint>)
(<edge> outer )
G1 X-0.44 Y-5.23 Z2.63 F3300.0
G1 F1200.0
G1 E34.899
G1 F3300.0
M101
M73 P90 (display progress)
G1 X-0.24 Y-5.33 Z2.63 F352.254 E34.903
G1 X-0.13 Y-5.36 Z2.63 F352.254 E34.906
G1 X0.12 Y-5.36 Z2.63 F352.254 E34.91
G1 X0.23 Y-5.33 Z2.63 F352.254 E34.912
G1 X0.6 Y-5.15 Z2.63 F352.254 E34.919
G1 X0.6 Y5.15 Z2.63 F352.254 E35.106
G1 X0.23 Y5.33 Z2.63 F352.254 E35.113
G1 X0.12 Y5.36 Z2.63 F352.254 E35.115
G1 X-0.12 Y5.36 Z2.63 F352.254 E35.12
G1 X-0.27 Y5.32 Z2.63 F352.254 E35.122
G1 X-0.59 Y5.15 Z2.63 F352.254 E35.129
G1 X-0.59 Y-5.15 Z2.63 F352.254 E35.315
G1 X-0.44 Y-5.23 Z2.63 F352.254 E35.318
G1 F1200.0
G1 E35.318
G1 F352.254
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.599 Y-5.148 Z2.05 </infillPoint>)
(<infillPoint> X0.599 Y5.148 Z2.05 </infillPoint>)
(<infillPoint> X0.233 Y5.333 Z2.05 </infillPoint>)
(<infillPoint> X0.12 Y5.356 Z2.05 </infillPoint>)
M73 P91 (display progress)
(<infillPoint> X-0.123 Y5.356 Z2.05 </infillPoint>)
(<infillPoint> X-0.268 Y5.32 Z2.05 </infillPoint>)
(<infillPoint> X-0.59 Y5.153 Z2.05 </infillPoint>)
(<infillPoint> X-0.59 Y-5.153 Z2.05 </infillPoint>)
(<infillPoint> X-0.237 Y-5.33 Z2.05 </infillPoint>)
(<infillPoint> X-0.125 Y-5.356 Z2.05 </infillPoint>)
(<infillPoint> X0.12 Y-5.356 Z2.05 </infillPoint>)
(<infillPoint> X0.233 Y-5.333 Z2.05 </infillPoint>)
(</infillBoundary>)
;M108 R11.74
G1 X-0.0 Y-5.07 Z2.63 F3300.0
G1 F1200.0
G1 E35.318
G1 F3300.0
M101
G1 X0.0 Y5.07 Z2.63 F704.507 E35.502
G1 F1200.0
G1 E34.502
G1 F704.507
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R6.853
(</layer>)
(<layer> 2.73 )
M73 P92 (display progress)
(<rotation> (-1+1.22464679915e-16j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.666 Y5.261 Z2.73 </boundaryPoint>)
(<boundaryPoint> X0.34 Y5.414 Z2.73 </boundaryPoint>)
(<boundaryPoint> X0.115 Y5.465 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.094 Y5.467 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.417 Y5.385 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.669 Y5.261 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.669 Y-5.261 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.294 Y-5.427 Z2.73 </boundaryPoint>)
(<boundaryPoint> X-0.094 Y-5.467 Z2.73 </boundaryPoint>)
(<boundaryPoint> X0.115 Y-5.465 Z2.73 </boundaryPoint>)
(<boundaryPoint> X0.34 Y-5.414 Z2.73 </boundaryPoint>)
(<boundaryPoint> X0.666 Y-5.261 Z2.73 </boundaryPoint>)
(<edge> outer )
G1 X-0.47 Y-4.99 Z2.73 F3300.0
G1 F1200.0
G1 E35.502
G1 F3300.0
M101
G1 X-0.47 Y-5.13 Z2.73 F411.206 E35.504
G1 X-0.23 Y-5.24 Z2.73 F411.206 E35.509
G1 X-0.07 Y-5.27 Z2.73 F411.206 E35.512
G1 X0.09 Y-5.26 Z2.73 F411.206 E35.515
M73 P93 (display progress)
G1 X0.28 Y-5.22 Z2.73 F411.206 E35.518
G1 X0.47 Y-5.13 Z2.73 F411.206 E35.522
G1 X0.47 Y5.13 Z2.73 F411.206 E35.708
G1 X0.28 Y5.22 Z2.73 F411.206 E35.712
G1 X0.09 Y5.26 Z2.73 F411.206 E35.715
G1 X-0.07 Y5.27 Z2.73 F411.206 E35.718
G1 X-0.35 Y5.2 Z2.73 F411.206 E35.723
G1 X-0.47 Y5.14 Z2.73 F411.206 E35.726
G1 X-0.47 Y-4.99 Z2.73 F411.206 E35.909
G1 F1200.0
G1 E34.909
G1 F411.206
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.466 Y5.134 Z2.15 </infillPoint>)
(<infillPoint> X0.275 Y5.224 Z2.15 </infillPoint>)
(<infillPoint> X0.092 Y5.265 Z2.15 </infillPoint>)
(<infillPoint> X-0.07 Y5.267 Z2.15 </infillPoint>)
(<infillPoint> X-0.347 Y5.196 Z2.15 </infillPoint>)
(<infillPoint> X-0.469 Y5.137 Z2.15 </infillPoint>)
(<infillPoint> X-0.469 Y-5.131 Z2.15 </infillPoint>)
(<infillPoint> X-0.233 Y-5.235 Z2.15 </infillPoint>)
M73 P94 (display progress)
(<infillPoint> X-0.075 Y-5.267 Z2.15 </infillPoint>)
(<infillPoint> X0.092 Y-5.265 Z2.15 </infillPoint>)
(<infillPoint> X0.275 Y-5.224 Z2.15 </infillPoint>)
(<infillPoint> X0.466 Y-5.134 Z2.15 </infillPoint>)
(</infillBoundary>)
;M108 R13.71
G1 X0.19 Y-0.0 Z2.73 F3300.0
G1 F1200.0
G1 E35.909
G1 F3300.0
M101
G1 X-0.19 Y0.0 Z2.73 F822.412 E35.916
G1 X-0.19 Y-0.4 Z2.73 F822.412 E35.923
G1 X0.19 Y-0.4 Z2.73 F822.412 E35.93
G1 X0.19 Y-0.8 Z2.73 F822.412 E35.937
G1 X-0.19 Y-0.8 Z2.73 F822.412 E35.944
G1 X-0.19 Y-1.2 Z2.73 F822.412 E35.951
G1 X0.19 Y-1.2 Z2.73 F822.412 E35.958
G1 X0.19 Y-1.6 Z2.73 F822.412 E35.965
G1 X-0.19 Y-1.6 Z2.73 F822.412 E35.972
G1 X-0.19 Y-2.0 Z2.73 F822.412 E35.979
G1 X0.19 Y-2.0 Z2.73 F822.412 E35.986
G1 X0.19 Y-2.4 Z2.73 F822.412 E35.993
G1 X-0.19 Y-2.4 Z2.73 F822.412 E36.0
G1 X-0.19 Y-2.8 Z2.73 F822.412 E36.007
G1 X0.19 Y-2.8 Z2.73 F822.412 E36.014
M73 P95 (display progress)
G1 X0.19 Y-3.2 Z2.73 F822.412 E36.021
G1 X-0.19 Y-3.2 Z2.73 F822.412 E36.028
G1 X-0.19 Y-3.6 Z2.73 F822.412 E36.035
G1 X0.19 Y-3.6 Z2.73 F822.412 E36.042
G1 X0.19 Y-4.0 Z2.73 F822.412 E36.049
G1 X-0.19 Y-4.0 Z2.73 F822.412 E36.056
G1 X-0.19 Y-4.4 Z2.73 F822.412 E36.063
G1 X0.19 Y-4.4 Z2.73 F822.412 E36.07
G1 X0.14 Y-4.8 Z2.73 F822.412 E36.077
G1 X-0.19 Y-4.8 Z2.73 F822.412 E36.083
G1 F1200.0
G1 E35.083
G1 F822.412
M103
G1 X-0.19 Y0.4 Z2.73 F3300.0
G1 F1200.0
G1 E36.083
G1 F3300.0
M101
G1 X0.19 Y0.4 Z2.73 F822.412 E36.09
G1 X0.19 Y0.8 Z2.73 F822.412 E36.097
G1 X-0.19 Y0.8 Z2.73 F822.412 E36.104
G1 X-0.19 Y1.2 Z2.73 F822.412 E36.111
G1 X0.19 Y1.2 Z2.73 F822.412 E36.118
G1 X0.19 Y1.6 Z2.73 F822.412 E36.125
M73 P96 (display progress)
G1 X-0.19 Y1.6 Z2.73 F822.412 E36.132
G1 X-0.19 Y2.0 Z2.73 F822.412 E36.139
G1 X0.19 Y2.0 Z2.73 F822.412 E36.146
G1 X0.19 Y2.4 Z2.73 F822.412 E36.153
G1 X-0.19 Y2.4 Z2.73 F822.412 E36.16
G1 X-0.19 Y2.8 Z2.73 F822.412 E36.167
G1 X0.19 Y2.8 Z2.73 F822.412 E36.174
G1 X0.19 Y3.2 Z2.73 F822.412 E36.181
G1 X-0.19 Y3.2 Z2.73 F822.412 E36.188
G1 X-0.19 Y3.6 Z2.73 F822.412 E36.195
G1 X0.19 Y3.6 Z2.73 F822.412 E36.202
G1 X0.19 Y4.0 Z2.73 F822.412 E36.209
G1 X-0.19 Y4.0 Z2.73 F822.412 E36.216
G1 X-0.19 Y4.4 Z2.73 F822.412 E36.223
G1 X0.19 Y4.4 Z2.73 F822.412 E36.23
G1 X0.14 Y4.8 Z2.73 F822.412 E36.237
G1 X-0.16 Y4.8 Z2.73 F822.412 E36.243
G1 F1200.0
G1 E35.243
G1 F822.412
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.508
M73 P97 (display progress)
(</layer>)
(<layer> 2.83 )
(<rotation> (6.12323399574e-17+1j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.487 Y5.279 Z2.83 </boundaryPoint>)
(<boundaryPoint> X0.141 Y5.364 Z2.83 </boundaryPoint>)
(<boundaryPoint> X-0.222 Y5.349 Z2.83 </boundaryPoint>)
(<boundaryPoint> X-0.5 Y5.261 Z2.83 </boundaryPoint>)
(<boundaryPoint> X-0.5 Y-5.279 Z2.83 </boundaryPoint>)
(<boundaryPoint> X-0.077 Y-5.369 Z2.83 </boundaryPoint>)
(<boundaryPoint> X0.148 Y-5.362 Z2.83 </boundaryPoint>)
(<boundaryPoint> X0.487 Y-5.279 Z2.83 </boundaryPoint>)
(<edge> outer )
G1 X-0.3 Y-4.67 Z2.83 F3300.0
G1 F1200.0
G1 E36.243
G1 F3300.0
M101
G1 X-0.3 Y-5.12 Z2.83 F330.462 E36.251
G1 X-0.06 Y-5.17 Z2.83 F330.462 E36.255
G1 X0.12 Y-5.16 Z2.83 F330.462 E36.259
G1 X0.29 Y-5.12 Z2.83 F330.462 E36.262
G1 X0.29 Y5.12 Z2.83 F330.462 E36.447
G1 X0.12 Y5.16 Z2.83 F330.462 E36.45
G1 X-0.19 Y5.15 Z2.83 F330.462 E36.456
M73 P98 (display progress)
G1 X-0.3 Y5.12 Z2.83 F330.462 E36.458
G1 X-0.3 Y-4.67 Z2.83 F330.462 E36.635
G1 F1200.0
G1 E36.635
G1 F330.462
M103
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.287 Y5.122 Z2.25 </infillPoint>)
(<infillPoint> X0.121 Y5.163 Z2.25 </infillPoint>)
(<infillPoint> X-0.187 Y5.15 Z2.25 </infillPoint>)
(<infillPoint> X-0.3 Y5.115 Z2.25 </infillPoint>)
(<infillPoint> X-0.3 Y-5.117 Z2.25 </infillPoint>)
(<infillPoint> X-0.059 Y-5.168 Z2.25 </infillPoint>)
(<infillPoint> X0.121 Y-5.163 Z2.25 </infillPoint>)
(<infillPoint> X0.287 Y-5.122 Z2.25 </infillPoint>)
(</infillBoundary>)
;M108 R11.02
G1 X-0.0 Y-4.89 Z2.83 F3300.0
G1 F1200.0
G1 E36.635
G1 F3300.0
M101
M73 P99 (display progress)
G1 X0.0 Y4.88 Z2.83 F660.925 E36.812
G1 F1200.0
G1 E35.812
G1 F660.925
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R40.0
(</layer>)
(</crafting>)
M104 S0
;M113 S0.0
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
